### ISSUE TITLE
move notes between notebooks

### ISSUE THREAD

**Issue by ghost** [zim-desktop-wiki/zim-desktop-wiki#942] opened 2019-09-30 18:08 UTC
i haven't found a way to do this?

ideally drag and drop would do it (currently dragging and dropping creates a link, which is also a desirable feature). 

'move note' in the context menu in the index pane doesn't support the 'notebook?note' linking syntax. likewise, copying a note from the same menu copies it as a link.

**Comment by zwieblum** [comment] 2019-10-18 13:22
Not exactly "move note", but works: Open both notebooks, open the page you want to copy. Press : 
<ctrl>+<a> <ctrl>+<c>
Go to the other notebook, create a new page, <ctrl>+<v>

**Comment by introt** [comment] 2021-12-15 09:27
Duplicate of #823

**Closed by introt** 2021-12-15 09:27 UTC
