### ISSUE TITLE
Code blocks rendering/positioning is broken

### ISSUE THREAD

**Issue by alk0** [zim-desktop-wiki/zim-desktop-wiki#721] opened 2019-03-28 22:45 UTC
Linux Mint 19.1 Cinnamon, zim 0.70~ubuntu18.04.1 from `ppa:jaap.karssenberg/zim`

Code blocks rendering/**positioning** is badly broken for pages longer than a few "pagedowns".

(0.69 didn't render code blocks properly with line numbers turned on, 0.70 doesn't render them well regardless of line numbers.)

Source text (multiple copies of the same "text followed by a code block" fragment) - [sandbox3.txt](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/3020365/sandbox3.txt)

Partial screenshot below >>

![Screenshot from 2019-03-29 03-31-15](https://user-images.githubusercontent.com/10332037/55197086-40e1cd00-51d3-11e9-9cf6-475c3842ba7d.png)

<< End of screenshot.

**Comment by PierreRust** [comment] 2019-03-29 08:12
I believe this is a duplicate of #642 
I've tried to investigate this issue but I could find any explanation for this behavior :(

**Comment by jaap-karssenberg** [comment] 2019-04-01 12:01
Duplicate

**Closed by jaap-karssenberg** 2019-04-01 12:01 UTC
