### ISSUE TITLE
Zim's page sorting is regularly confusing and makes no sense

### ISSUE THREAD

**Issue by pfalcon** [zim-desktop-wiki/zim-desktop-wiki#1442] opened 2021-04-11 19:10 UTC
Attached screenshot shows a typical case:

![Screenshot at 2021-04-11 22-05-20](https://user-images.githubusercontent.com/500451/114317715-15a84d00-9b12-11eb-825f-4b29772400cb.png)

It shows result of filtering Journal pages by a tag (indeed, Journal pages is where this issue happens almost universally). Specifically, the screenshot shows pages being ordered as:

```
Journal:2018:03:12
Journal:2020:10:12
Journal:2018:08:20
```

**Comment by pfalcon** [comment] 2021-04-11 19:44
So, seeing ordering like that, the first idea is that Zim simply doesn't sort pages in various lists, but just uses order from the filesystem and/or database (usually stable but effectively random). The more unpleasantly surprising to find out that Zim actually goes a long way to sort page names in contra-logical and buggy manner.

Key facts:
1. For various page lists, like filtered by tag case above, the page list is gotten from DB and sorted by `pages.sortkey`.
2. The initial ingredient of `sortkey` is "base page name", which already fails to work properly for Zim's builtin Journal functionality - indeed, looking at the example above, it's indeed "sorted" by last day: 12, 12, 20, but given that actually the full page name is shown (and the full page name is **the** page name from user's PoV), that makes no sense.
3. But it only starts there. Function natural_sort_key() https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/master/zim/utils.py#L115 does some quite unobvious, and by now apparently erroneous, processing.

It apparently was written for Python2, judging by `bytestring = locale.strxfrm(string)` statement. In Python3, `locale.strxfrm()` doesn't produce "bytestring", it produces a normal (unicode) strings, contents of which is quite an utter crap (as actually produced by libc, in this case glibc):

```
>>> import locale
>>> locale.setlocale(locale.LC_ALL, "")
'en_US.UTF-8'
>>> locale.strxfrm("1")
'Ř\x01\x1d\x01\x02\x01\x01屯'
```

That crap however still gets passed thru `key = ''.join(["%02x" % ord(c) for c in bytestring])`, but unlike originally expected, it doesn't produce exactly 2 hex digit for crap-"character" of `locale.strxfrm()`, but may produce 3, 4, perhaps more digits in some case. Such encoded `sortkey`s are still get compared character by character, which can easily lead to quite unexpected sort order. I don't actually have a repro case for this condition, but I dread to aware face such a case in real situation, and of course it'll happen.

Reference: https://www.py4u.net/discuss/189759 . This is about only reference I was able to find which explains the locale.strxfrm() (and stuff below it) mess:

> In Python 3.x, the function locale.strxfrm(s) internally uses the POSIX C function wcsxfrm(),

>>     The transformation shall be such that if wcscmp() ...

> This definition can be implemented in multiple ways, and doesn't even require that the resulting string is readable.

> On Python 2.7 the error is not raised because its locale.strxfrm() implementation is based on strxfrm() C function.

**Comment by pfalcon** [comment] 2021-04-11 19:56
Now my humble ideas on working around this mess:

Ideally, would need to switch `sortkey` to be based off the full page name. But I see that contrary to its name, the **sortkey** is actually used to **query** the database, e.g.:
```
                                c = self.db.execute(
                                        'SELECT name, id FROM pages '
                                        'WHERE sortkey=? '
                                        'ORDER BY name DESC',
                                        (anchor_key,)
                                ) # sort longest first
```

Then yep, changing sortkey derivation won't work easily, and it's easier to stop using it as a sort key, with patches like:

```
-                               ORDER BY sortkey DESC, name DESC LIMIT 20 OFFSET ?
+                               ORDER BY name DESC LIMIT 20 OFFSET ?
```

And of course, it goes without a saying that locale.strxfrm() and ambiguous hex encoding should be removed from sortkey derivation. It's better to rely on sqlite3 as single point for string collation than multiple failure points like buggy libc's and apps.

**Comment by jaap-karssenberg** [comment] 2023-01-05 13:27
Duplicate of #1632

**Closed** 2023-01-05 13:28 UTC
Labels: needs triage
