### ISSUE TITLE
Regression on .74.3: going 'back' in history to a previous page loses last saved position, opens at the top of the page

### ISSUE THREAD

**Issue by quesada** [zim-desktop-wiki/zim-desktop-wiki#1871] opened 2022-01-15 23:39 UTC
**Describe the bug**
Regression on .74.3: going 'back' in history to a previous page loses last saved position, opens at the top of the page

**To Reproduce**
1. Go to 'a page'. Scroll down, add text so the cursor position is not at the top
2. Click on 'another page. Or create a new one'
3. Go back with alt + left arrow
4. See that the cursor position is a the top of the page

**Expected behavior**
the cursor position is not at the top, but at the last edit position

**Environment (please complete the following information):**
 - Version [e.g. 0.74.3] 
 - OS: [e.g. linux/manjaro KDE]
 - Language: especially for errors that might relate to character encoding or other locale specific issues
EN

**Comment by introt** [comment] 2022-01-16 15:04
Thanks for the report!

The correct cursor position seems to be saved (try using the cursor with arrow keys; should trigger a scroll), so this only concerns the scroll position.

**Comment by introt** [comment] 2022-01-16 15:08
Seems to be a duplicate of #1624, which itself looks like a duplicate of #1276. Closing this one.

**Closed by introt** 2022-01-16 15:08 UTC
Labels: bug

**Comment by introt** [comment] 2022-01-16 15:13
@quesada One question though: you called this a regression; could you name the version where this used to work? Thanks!
