### ISSUE TITLE
source visualizer color scheme

### ISSUE THREAD

**Issue by e-belair** [zim-desktop-wiki/zim-desktop-wiki#695] opened 2019-03-04 09:35 UTC
Hi, Is that possible to custom the color scheme on the source visualizer plugin?
I'm using a dark theme and some of code is hard to see like this example:
![image](https://user-images.githubusercontent.com/596562/53723964-2123e700-3e69-11e9-97fc-a2cdcb16282b.png)
The blues line is hard to see

**Comment by Self-Perfection** [comment] 2019-03-04 21:38
Looks like a duplicate of #544

**Closed** 2019-03-05 07:29 UTC
