### ISSUE TITLE
Support tel: links

### ISSUE THREAD

**Issue by thejeshgn** [zim-desktop-wiki/zim-desktop-wiki#1257] opened 2020-09-10 11:53 UTC
May we can support bunch of operating system deep links (URI). Popular ones are

1. maito:   already supported
2. git://
3. webcal

Official list is here. https://en.wikipedia.org/wiki/List_of_URI_schemes

May be we can allow user to add/edit just like emojis or wiki urls.

**Comment by Self-Perfection** [comment] 2021-01-24 19:59
Related discussion: [Can't use geo: URI in links (or any arbitrary URI scheme)](https://bugs.launchpad.net/zim/+bug/1572542)

**Comment by introt** [comment] 2021-12-15 16:54
Duplicate of #513

**Closed by introt** 2021-12-15 16:54 UTC
