### ISSUE TITLE
High CPU usage in Windows due to calling external application

### ISSUE THREAD

**Issue by SooDesuNe** [zim-desktop-wiki/zim-desktop-wiki#1697] opened 2021-10-21 02:07 UTC
Zim uses 15% of my CPU for long periods of time, resulting in my computer heating up and the laptop fan running continuously.  I am running Windows 10 on a fairly new laptop and have the latest version (0.74.2) installed.  My notebook contains around 6000 pages.

This has been an issue for at least a couple of versions, but wasn't an issue in the more distant past.  Could it somehow be related to the upgrade in the GTK library?  If Zim is continuously indexing, I would love a way to turn this off.

**Comment by jaap-karssenberg** [comment] 2021-10-21 09:28
Can you have a look at the debug log to see if some background processing
is going on?

Op do 21 okt. 2021 04:07 schreef SooDesuNe ***@***.***>:

**Comment by jaap-karssenberg** [comment] 2023-01-05 13:45
Confirmed that there is an issue with calling external applications on windows. Needs investigation.

**Comment by roman-yepishev** [comment] 2023-08-19 16:30
Hi folks,

This appears to be an issue with the GLib (or the generated bindings) invalidating the returned pid "handle" and not Zim itself. A similar failure can be observed with this:

```python
from gi.repository import GLib


def spawn(loop):
    def quit(pid, status, m_loop):
        print(f"Done: {pid}")
        GLib.spawn_close_pid(pid)
        m_loop.quit()

    flags = GLib.SpawnFlags.SEARCH_PATH | GLib.SpawnFlags.DO_NOT_REAP_CHILD
    argv = [
        'C:\\Windows\\notepad.exe']
    pid, stdin, stdout, stderr = GLib.spawn_async(argv, flags=flags)
    print(f"Handle: {pid}")

    GLib.child_watch_add(pid, quit, loop)


def main():
    loop = GLib.MainLoop()

    GLib.idle_add(spawn, loop)

    loop.run()


if __name__ == "__main__":
    main()
```

It looks like after spawn() is executed, pid.close() is called (or in some other way the handle is invalidated, thus causing WaitForMultipleObjectsEx to complain about the handle and then interpreter gets into some sort of a busy waiting loop.

```
C:/msys64/mingw64/lib/python3.10/site-packages/gi/overrides/GLib.py:497: Warning: WaitForMultipleObjectsEx failed: The handle is invalid.
  super(MainLoop, self).run()
```

**Comment by bkidwell** [comment] 2023-11-29 04:31
I tried @roman-yepishev 's patch just now on my local machine (executed from the output of `windows/build.sh`) and it appears to solve the problem. Thank you so much for working around this bug that's been causing me trouble for years!

Here is the build on my OneDrive: [zim-desktop-wiki-0.75.2-setup-w64_x86-pullrequest-2455.exe](https://1drv.ms/u/s!AptAlaueilCWkQO6pbSkTeTzc1HW?e=gzx2C6). No warranty; don't complain to me if this kills your goldfish. If the file is gone, probably I deleted it because the PR was merged and a Release has been published with the fix.

**Closed** 2024-01-04 12:22 UTC
Labels: bug, fix available, needs investigation, Windows
