### ISSUE TITLE
Reindex error across Master and Develop branches

### ISSUE THREAD

**Issue by releve1403** [zim-desktop-wiki/zim-desktop-wiki#2089] opened 2022-06-21 17:20 UTC
When switching from "master branch" to "develop branch", I noticed two entries marked "conflicted" in the journal. 

Tried to erase them within Zim but it didn't work; pages were still ther. 

Just erased the files directly in file manager. Then reindexing gave this crash error below.

Maybe it isn't really a bug, as the messages appears to be related to tasklist. And, as there is many differences between Master and Develop about tasklist, this is just kind of normal... Don't know.

This is zim 0.74.3
Platform: posix
Locale: fr_CA UTF-8
FS encoding: utf-8
Python: (3, 8, 10, 'final', 0)
PyGObject: (3, 36, 0)

**Traceback**
```
  File "/usr/lib/python3/dist-packages/zim/actions.py", line 159, in _on_activate
	self.call()
  File "/usr/lib/python3/dist-packages/zim/actions.py", line 130, in call
	return self._action.func(self._instance, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/zim/plugins/tasklist/init.py", line 172, in show_task_list
	self._task_list_window = self._show_task_window(selection_state=None)
  File "/usr/lib/python3/dist-packages/zim/plugins/tasklist/init.py", line 181, in _show_task_window
	window = TaskListWindow(notebook, index, navigation, properties, self.plugin.preferences['show_inbox_next'])
  File "/usr/lib/python3/dist-packages/zim/plugins/init.py", line 111, in _init_wrapper
	orig_init(self, *arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/plugins/tasklist/gui.py", line 338, in init
	swindow = self._create_tasklisttreeview(navigation, properties)
  File "/usr/lib/python3/dist-packages/zim/plugins/tasklist/gui.py", line 96, in _create_tasklisttreeview
	self.tasklisttreeview = TaskListTreeView(
  File "/usr/lib/python3/dist-packages/zim/plugins/tasklist/gui.py", line 801, in init
	self.refresh()
  File "/usr/lib/python3/dist-packages/zim/plugins/tasklist/gui.py", line 851, in refresh
	self._append_tasks(self.taskselection.list_tasks(), None)
  File "/usr/lib/python3/dist-packages/zim/plugins/tasklist/gui.py", line 863, in _append_tasks
	for prio_sort_int, row in enumerate(task_iter):
  File "/usr/lib/python3/dist-packages/zim/plugins/tasklist/indexer.py", line 284, in list_tasks
	for row in self.db.execute('''
OperationalError: no such column: tasklist.status
```

Thanks
--Renaud L.

```

**Comment by introt** [comment] 2022-06-22 18:10
Hi, and thanks for the report!

These things should be ironed out before the next release, but in the meantime, does deleting the index database manually solve the issue?

**Comment by releve1403** [comment] 2022-06-24 15:10
Yes, deleting the "index.db" file force a successful rebuild. No problem there.
However, deleting conflicted pages can still be accomplished only outside Zim.
Thanks for the reply.
--Renaud

**Comment by introt** [comment] 2022-07-02 12:10
Hi, could you please elaborate on the "conflicted pages"? How are they "marked", and what happens when you try to open or edit them? Please attach screenshots, thanks!

**Comment by releve1403** [comment] 2022-07-08 02:23
Hi. Sorry for the late reply.
![Capture de 2022-07-07 22:15:46](https://user-images.githubusercontent.com/98767445/177903371-e5ddd651-0909-469e-bb8c-6cd170a39fff.png)
Here is how it looks in the pages index.
Maybe it is caused by the fact that I switched from Master to Develop branches? Or could it be caused by the fact that the Zim repertory is synchronized on pCloud?
And now, with the master branch, even though I deleted the "index.db" file, everytime I call the tasklist, I got this error : 
---
This is zim 0.74.3
Platform: posix
Locale: fr_CA UTF-8
FS encoding: utf-8
Python: (3, 8, 10, 'final', 0)
PyGObject: (3, 36, 0)

======= Traceback =======
  File "/home/renaud/zim-desktop-wiki-master/zim/actions.py", line 159, in _on_activate
    self.__call__()
  File "/home/renaud/zim-desktop-wiki-master/zim/actions.py", line 130, in __call__
    return self._action.func(self._instance, *args, **kwargs)
  File "/home/renaud/zim-desktop-wiki-master/zim/plugins/tasklist/__init__.py", line 168, in show_task_list
    dialog = TaskListDialog.unique(self, self.pageview, tasksview, properties)
  File "/home/renaud/zim-desktop-wiki-master/zim/gui/widgets.py", line 2827, in unique
    dialog = klass(*args, **opts)
  File "/home/renaud/zim-desktop-wiki-master/zim/plugins/__init__.py", line 115, in _init_wrapper
    orig_init(self, *arg, **kwarg)
  File "/home/renaud/zim-desktop-wiki-master/zim/plugins/tasklist/gui.py", line 134, in __init__
    self.task_list = TaskListTreeView(
  File "/home/renaud/zim-desktop-wiki-master/zim/plugins/tasklist/gui.py", line 501, in __init__
    self.refresh()
  File "/home/renaud/zim-desktop-wiki-master/zim/plugins/tasklist/gui.py", line 531, in refresh
    self._append_tasks(None, None, {})
  File "/home/renaud/zim-desktop-wiki-master/zim/plugins/tasklist/gui.py", line 566, in _append_tasks
    for prio_sort_int, row in enumerate(tasks):
  File "/home/renaud/zim-desktop-wiki-master/zim/plugins/tasklist/indexer.py", line 221, in list_open_tasks
    for row in self.db.execute('''
OperationalError: no such column: tasklist.open
---
Thanks,
Renaud

**Comment by introt** [comment] 2022-07-09 10:18
Thanks Renaud!

> Or could it be caused by the fact that the Zim repertory is synchronized on pCloud?

Do you mean `/home/renaud/zim-desktop-wiki-master/`? Switching between code branches using regular git, regardless of whether you're using the same notebook, though especially then, can lead to cryptic errors, so I'd advice against having your installation in any sort of cloud. Zim may try to load invalid `__pycache__` files etc, so maybe try re-downloading Zim into a non-synced dir besides deleting your caches & index db

**Comment by releve1403** [comment] 2022-07-10 01:51
Hi introt,
I wasn't precise enough in my last explanation... 
The Zim application is local on my laptop, and so is also my notebooks. But, for backup and for the possibility of consulting my notes from my cell phone and tablet, my local notebook is synchronized on pCloud, as they are just text files. 
I hope this is more clear now.
Thanks
--Renaud

**Comment by introt** [comment] 2022-07-10 18:09
Hi, thanks for clearing that up. Could you share the contents of your `notebook.zim` file, and whether there's a hidden `.zim` directory residing in the same directory? Also, what's your operating system?

**Comment by releve1403** [comment] 2022-07-11 02:43
Hi,
Here is the content of my "notebook.zim" file : 
```
[Notebook]
version=0.4
name=Perso
interwiki=
home=Affaires courantes
icon=
document_root=/media/RENAUDEPOT/maison/ZimNotesPerso
short_links=False
shared=False
endofline=unix
disable_trash=False
default_file_format=zim-wiki
default_file_extension=.txt
notebook_layout=files
profile=

[TaskListPlugin]
all_checkboxes=True
labels=FIXME, TODO
integrate_with_journal=due
included_subtrees=
excluded_subtrees=
nonactionable_tags=inactif, en_attente, en_suspens
tag_by_page=True
use_workweek=False
waiting_labels=en_attente, en_suspens
show_pages=True

[JournalPlugin]
namespace=Journal
granularity=Jour

```
---
Also, yes, there is a hidden ".zim" directory and I've joined what it looks like.
![Capture de 2022-07-10 22:35:25](https://user-images.githubusercontent.com/98767445/178178393-3d742cb6-781d-4f90-8850-f97084f7ab5a.png)

And, finally, I'm on Linux (Budgie Desktop). Here is the content of "lsb_release -a" : 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```
Thanks

**Comment by introt** [comment] 2022-07-16 18:27
Hi,

Thanks for your thorough reply. My interpretation is that your pCloud synchronization program is the one creating these `(conflicted)` files, as I'm not aware of nor could I find any code that'd do that on our side - in other words, those pages aren't "marked as conflicted" by Zim, but are named as such by the synchronization program and just happen to show up in the index as they're valid wiki files (except for the space in the filename; this explains why they can't be deleted inside Zim, because it expects 1:1 underscores for "illegal" characters - see the screenshot below, there is no underscore in the real filename).

![image](https://user-images.githubusercontent.com/26069787/179367437-f524d8e9-6b00-41cd-a0f8-86d44b4e0a88.png)


As for the tasklist related error, try editing `shared=False` to `shared=True` in the notebook.zim config file - this will make Zim write the index.db and state.conf files inside your home directory instead of the cloud mount, which is probably responsible for the OperationalError.

Please let me know if changing the above config value & clearing the cache (including that hidden `.zim` dir) solves your issue - I'll open a separate ticket for the underscore thing afterwards if there isn't one already.

**Comment by releve1403** [comment] 2022-07-18 17:38
Hi introt,
2 things : 
1. You were right about "conflicted" files : the problem is caused by the pCloud sync process. Here is a text from the pCloud site : 

> `Whenever you are syncing or backing up certain files, which are utilized by a system frequently, conflicted copies might occur. A conflicted copy is a second version of a file that's being modified too frequently during the sync/backup. You will be able to recognize a conflicted copy of your file, as it will have the same name of the original version with the attachment "conflicted". We do NOT advise syncing the following file types...

2. After flushing the ".zim" cache directory and lauching Zim, the tasklist plugin is working again. Instead of deleting the ".zim" directory, I first tried "zim --flush" at command prompt and it results in the following error : 
--
renaud@renaud-ThinkPad-T430s:~$ zim --flush
Gtk-Message: 12:39:09.732: Failed to load module "appmenu-gtk-module"
ERROR: Exception in main()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 936, in main
    ZIM_APPLICATION.run(*argv[1:])
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 706, in run
    cmd = build_command(args, **kwargs)
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 622, in build_command
    obj.parse_options(*args)
  File "/usr/lib/python3/dist-packages/zim/main/command.py", line 81, in parse_options
    optlist, args = gnu_getopt(args, options, long_options)
  File "/usr/lib/python3.8/getopt.py", line 136, in gnu_getopt
    opts, args = do_longs(opts, args[0][2:], longopts, args[1:])
  File "/usr/lib/python3.8/getopt.py", line 157, in do_longs
    has_arg, opt = long_has_args(opt, longopts)
  File "/usr/lib/python3.8/getopt.py", line 174, in long_has_args
    raise GetoptError(_('option --%s not recognized') % opt, opt)
getopt.GetoptError: option --flush not recognized
--

I have uninstalled and reinstalled Zim from Ubuntu repository (official version) and the behavior stay the same.
Thanks again.
--R

**Comment by introt** [comment] 2022-07-20 15:49
Hi @releve1403,

> After flushing the ".zim" cache directory and lauching Zim, the tasklist plugin is working again.

Glad to hear your original issue was resolved.

> I first tried "zim --flush" at command prompt and it results in the following error

Seems like `-f`/`--flush` is broken _and_ our arg parser is very verbose about unrecognized options, which means I get to open two new tickets - yay! Thanks for reporting this, I've been looking forward to refactoring our `command` module implementation with [`argparse`](https://docs.python.org/3/library/argparse.html).

**Closed** 2022-07-20 15:49 UTC
Labels: candidate for removal

**Comment by introt** [comment] 2022-07-20 15:56
My bad, flushing _does_ work - the correct invocation is as follows: `zim --index Perso --flush` and results in output similar to the following:

```
INFO: Connecting to database file: /home/introt/.cache/zim/notebook-home_introt_Notebooks_Demo/index.db
INFO: Flushing index
INFO: (Re-)Initializing database for index
INFO: Index folder: /home/introt/Notebooks/Demo
```

**Comment by releve1403** [comment] 2022-07-23 14:00
Hi introt.
Yes, the "--flush" parameter just worked as you mentioned. Problem solved.
Thanks
--Renaud

**Comment by jaap-karssenberg** [comment] 2022-10-11 09:10
The "conflicted" files are not caused by zim, there is no such mechanism in
our code.  I highly suspect it is due to cloud syncing or similar.

The database conflicts in the tasklist plugin are an issue but can't really
see what goes wrong. The plugin keeps a version number in the index, so in
theory it should notice you switched between master and develop and trigger
an update of the database with the right version of the table definition.

However, in this cause that update did not happen for some reason. Maybe
you had a running zim instance open when you did the switch over? Or is the
database file also in the cloud share and not synced properly ? Any other
hints on what is happening ?

--- Jaap

**Comment by releve1403** [comment] 2022-10-13 13:22
Hi Jaap, 

About "conflicted", it is caused by my pCloud sync application. See my comment to "introt" on July 18th. 

About the tasklist plugin, it goes well (i.e. reindex) when I switch from Master to Develop. Tasks shows correctly. But when I get back to Master from Develop, Zim opens but I don't see the update window running and I get the following error when I call the tasklist plugin :

----
This is zim 0.74.3
Platform: posix
Locale: fr_CA UTF-8
FS encoding: utf-8
Python: (3, 10, 6, 'final', 0)
PyGObject: (3, 42, 1)

Traceback
  File "/usr/lib/python3/dist-packages/zim/actions.py", line 159, in _on_activate
	self.call()
  File "/usr/lib/python3/dist-packages/zim/actions.py", line 130, in call
	return self._action.func(self._instance, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/zim/plugins/tasklist/init.py", line 168, in show_task_list
	dialog = TaskListDialog.unique(self, self.pageview, tasksview, properties)
  File "/usr/lib/python3/dist-packages/zim/gui/widgets.py", line 2827, in unique
	dialog = klass(*args, **opts)
  File "/usr/lib/python3/dist-packages/zim/plugins/init.py", line 115, in _init_wrapper
	orig_init(self, *arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/plugins/tasklist/gui.py", line 134, in init
	self.task_list = TaskListTreeView(
  File "/usr/lib/python3/dist-packages/zim/plugins/tasklist/gui.py", line 501, in init
	self.refresh()
  File "/usr/lib/python3/dist-packages/zim/plugins/tasklist/gui.py", line 531, in refresh
	self._append_tasks(None, None, {})
  File "/usr/lib/python3/dist-packages/zim/plugins/tasklist/gui.py", line 566, in _append_tasks
	for prio_sort_int, row in enumerate(tasks):
  File "/usr/lib/python3/dist-packages/zim/plugins/tasklist/indexer.py", line 221, in list_open_tasks
	for row in self.db.execute('''
OperationalError: no such column: tasklist.open

----
The only way I found to make it work is calling Zim and forcing reindex with flush option.

And I had only one instance opened.

Thanks
--Renaud

**Comment by jaap-karssenberg** [comment] 2022-10-14 07:45
OK, since release of last week both branches are synced, so should no occur
anymore.

-- Jaap
