### ISSUE TITLE
Last Bullet Point in List lost

### ISSUE THREAD

**Issue by fdt-dev** [zim-desktop-wiki/zim-desktop-wiki#594] opened 2018-12-30 14:59 UTC
Sometimes (possibly when Zim has been running continuously for a long time) the last bullet point in a list is lost.
Imagine a list of bullet points present in a file. Then add a new entry by placing the cursor at the end of the last bullet point entry and hitting <enter>. A new bullet point appears in the line below as expected. After writing some text or adding a link in the same line after the bullet point, selecting another page and navigating back (or hitting Ctrl-R while on the same page) will remove the bullet point; the text remains.

If my description isn't clear, please tell me, I'll try to clarify. This happens with Zim 0.68 and 0.69 under Linux and with Zim 0.68 under Windows (0.69 not tested under Windows; potentially contains the same bug).

**Comment by jaap-karssenberg** [comment] 2019-02-11 19:52
I tried it in different ways with zim 0.70 branch but can't reproduce.

**Comment by fdt-dev** [comment] 2019-02-12 06:15
Thank you for checking. The bug is difficult to even encounter, I know. I'm sorry.
I haven't yet had the chance to test with 0.70, will do later. Is there any way for me to debug it or run a log? I am willing to do testing to this effect. My guess is that Zim somehow "forgets" to save the bullet point into the file. Which code part would be a likely suspect for that? I'll take a look at it.
It seems to happen with numbered lists and checkboxes, too, but not as often (not that it happens often anyway; only if the application has been running for a long time).

**Comment by jaap-karssenberg** [comment] 2021-12-13 12:45
Will move to close this bug unless there is new info.

**Comment by fdt-dev** [comment] 2021-12-15 12:27
I'm sorry. I wasn't able to reliably reproduce the bug. It sometimes happens, sometimes it doesn't. I am under the impression that it happens in Zim Wikis which are old and have pages which were created across several versions of Zim. It's not very specific. I'm sorry.
I think this bug persists in 0.74.3 -- reproducable at least in the Windows version (but not reliably, like I said)

Following steps:
1. Create new empty page
2. Fill the page with a list of entries with bullet points
3. Save the page
4. Add another entry to the bullet point list
5. Hit Ctrl-R
6. Last bullet point vanishes (only the bullet point; not the entry itself)

But it's difficult to reproduce, I so far don't understand under which circumstances it happens at all. I just know that it sometimes happens. Therefore I'd understand completely if you preferred to close the issue.

**Comment by jaap-karssenberg** [comment] 2021-12-15 12:47
How do you add the bullet exactly step by step ? (What key strokes / mouse
clicks )

Could it e.g. matter if the line ends with a newline (so empty line below)
versions no newline (last cursor possition on the buffer is end of bullet
item)

-- Jaap

**Comment by fdt-dev** [comment] 2021-12-15 12:54
Thank you for these questions:
I add the bullet point by typing an asterisk '*' and a space. Then I continue to add the first entry. After that the bullet points are automatically created by hitting enter at the end of the previous entry. That's as expected.
The last bullet point entry ... it can happen with both methods: either by creating the bullet point by hitting enter on the previous line or by again typing an asterisk.

One thing to add: It seems to happen most whenever all the entries are links to attachments. I don't know whether that's significant.

The page ends in a newline.

**Closed** 2022-08-30 18:28 UTC
Labels: needs testing, candidate for removal
