### ISSUE TITLE
AssertionError: BUG: processing empty string

### ISSUE THREAD

**Issue by muaadelsharif** [zim-desktop-wiki/zim-desktop-wiki#1384] opened 2021-01-31 13:57 UTC
This is zim 0.73.4
Platform: nt
Locale: en_US cp1256
FS encoding: utf-8
Python: (3, 8, 5, 'final', 0)
PyGObject: (3, 38, 0)

======= Traceback =======
  File "zim/gui/pageview.py", line 5617, in set_page
  File "zim/notebook/page.py", line 577, in get_parsetree
  File "zim/formats/wiki.py", line 639, in parse
  File "zim/formats/wiki.py", line 191, in __call__
  File "zim/parser.py", line 405, in __call__
AssertionError: BUG: processing empty string

**Comment by jaap-karssenberg** [comment] 2021-02-01 14:35
Could you add some page content that allows to reproduce this - what did
you type just prior to this error ?

**Comment by muaadelsharif** [comment] 2021-02-01 17:54
I had pages copied from an earlier version of Zim. I copy the whole year directory to make making the journal easier. When I did so the program crashed and showed the error message. Once I deleted the 2021 folder it came back to normal.
Typing anything triggers the bug.

Content-Type: text/x-zim-wiki
Wiki-Format: zim 0.4
Creation-Date: 2018-01-01T11:19:24+02:00

This is the content for all 365 pages.

**Comment by jaap-karssenberg** [comment] 2021-02-02 08:16
Ah, now I understand - the body of the page is empty, that causes the
error. The fix would be to have a bit more content in the files, e.g.
follow the headers with an empty line and a single line of text llike "..."

Hope that helps.

Probably should make the parser more robust for this case.

-- Jaap

**Comment by introt** [comment] 2021-12-15 17:47
I vaguely recall a commit message about fixing this - is this fixed?

**Comment by jaap-karssenberg** [comment] 2021-12-16 08:17
Yes, duplicate of 1645, fixed in 19c94a693a15944c14bd659916e2afb2824f4c8b

**Closed** 2021-12-16 08:18 UTC
Labels: needs testing
