### ISSUE TITLE
Download link for windows is NOT working

### ISSUE THREAD

**Issue by passionate2023** [zim-desktop-wiki/zim-desktop-wiki#2327] opened 2023-02-27 19:55 UTC
Throws the following error

Forbidden
You don't have permission to access this resource.

https://zim-wiki.org/downloads

**Comment by dehesselle** [comment] 2023-02-27 19:58
Duplicate of https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/2326

**Closed as not planned by dehesselle** 2023-02-27 19:58 UTC
Labels: bug, needs triage
