### ISSUE TITLE
Visible area jumps around

### ISSUE THREAD

**Issue by hansiglaser** [zim-desktop-wiki/zim-desktop-wiki#2580] opened 2024-03-01 09:10 UTC
**Describe the bug**
For long Zim pages, i.e., where scrolling is needed to walk around, under certain circumstances, Zim randomly scrolls to parts of the page, which are far off the intended place. The cursor (for text entry) is at the correct place, but the scrolled (and visible) part is somewhere else.

This happens reproducably when switching between pages (using the breadcrumbs). It also sometimes happens when I select text with the mouse.

**Expected behavior**
Correct scroll bar position

**Environment (please complete the following information):**
Zim version 0.75.2 on Windows. The older version 0.69 did not have this problem.

**Comment by introt** [comment] 2024-05-04 12:42
Duplicate of #1624

**Closed as not planned by introt** 2024-05-04 12:42 UTC
Labels: bug, needs triage
