### ISSUE TITLE
GUI freeze & high CPU load 

### ISSUE THREAD

**Issue by timmie** [zim-desktop-wiki/zim-desktop-wiki#405] opened 2018-04-01 23:48 UTC
Copied from:
[LP: GUI freeze & high CPU load ](https://bugs.launchpad.net/zim/+bug/1760511)

On Linux Mint with version 0.68 I often get very high CPU load.

After the following actions, the GUI completely freezes or bumps CPU to 99%:
* copy&paste text from a browser into Zim
* insert a new tag
* insert a URL

Similar happens with the portableapps version on Windows 10.

How can I help in debugging?

===

zim -D
INFO: This is zim 0.68
DEBUG: Python version is sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0)
DEBUG: Platform is posix
DEBUG: No bzr version-info found
DEBUG: Not running from a source dir
DEBUG: Set XDG_DATA_HOME to /home/HOME/.local/share
DEBUG: Set XDG_DATA_DIRS to [<Dir: /usr/share/cinnamon>, <Dir: /usr/share/gnome>, <Dir: /home/HOME/.local/share/flatpak/exports/share>, <Dir: /var/lib/flatpak/exports/share>, <Dir: /usr/local/share>, <Dir: /usr/share>, <Dir: /usr/share/mdm>]
DEBUG: Set XDG_CONFIG_HOME to /home/HOME/.config
DEBUG: Set XDG_CONFIG_DIRS to [<Dir: /etc/xdg/xdg-cinnamon>, <Dir: /etc/xdg>]
DEBUG: Set XDG_CACHE_HOME to /home/HOME/.cache
DEBUG: Connecting to /tmp/zim-HOME/primary-0.68-e63203e4
DEBUG: Dispatched command (u'-D',)

P.S.: is this project now migrated from Launchpad to Github?

**Comment by Osndok** [comment] 2018-04-02 02:57
Is this a huge notebook? With oodles of pages & links? If so, I can account for the two insert "embarrassing pauses" (they are tied to the live suggestion algo)... I haven't experienced such an issue with pasting, though.

**Comment by 1xPdd** [comment] 2018-04-09 17:37
You might try deleting and regenerating your index. I have several very large notebooks that would have strange performance issues; however 0.68 and new indexes have largely resolved these (so long as I don't have the tag plugin enabled).

**Comment by Osndok** [comment] 2018-04-09 20:11
Sometimes I'll get a random one-minute-hang (i.e. it clears itself), and usually involves a zim process deleting it's RPC socket (so it's always an indicator to me that zim needs to be restarted).

**Comment by timmie** [comment] 2018-05-14 22:47
Thanks to all responders.

I tried to re-create the index. 
Still, the thing hangs a lot.
Especially when copy&paste as well as any tag creation.
So I find myself often using a simple text editor :-(

**Comment by jaap-karssenberg** [comment] 2019-02-06 05:01
Please re-test with zim 0.70 or newer

**Comment by timmie** [comment] 2019-02-16 11:39
Hello @jaap-karssenberg 

I am now using packages from:
https://launchpad.net/~jaap.karssenberg/+archive/ubuntu/zim-snapshots

Unfortunately, the update rendered existing notebooks unusable.
They put CPU to 99% and freeze while updating the index.
I then just removed the old index but the problem persists.

**Comment by sngreen** [comment] 2019-05-13 06:38
Does anyone know which version works on Ubuntu 18?
Or does anyone know what alternatives to zim are out there? Pitty I wasted so much time on collecting notes.

**Comment by jaap-karssenberg** [comment] 2019-05-13 13:13
I have not observed this on any of my systems. Any information on the exact platform etc. that can help narrow it down is welcome.

**Comment by timmie** [comment] 2019-05-13 13:24
@jaap-karssenberg 
Seems that the orginal poster of today's comment removed his comment again. 
The mail said Ubuntu 18 was used. I am also in Mint using the Ubuntu LTS (18.04.) base.
I will test again with the latest repo snapshots and report back!

**Comment by sngreen** [comment] 2019-05-13 13:29
Ok, apologies, I did remove my comment. Posted in anger, and then thought better of it. 
The issue is with the code block view line numbers. If line-numbering is enabled the page will freeze. The only way to get around it is to disable the line numbering (right-click -> Show Line Numbers [unchecked]). 

I did try several zim versions, they all behaved the same. Appear to be fine on windows.

**Comment by jaap-karssenberg** [comment] 2019-05-13 13:41
@sngreen did your testing include the latest version zim 0.71? I'm on Ubuntu 18 myself and the issues with code blocks I was aware of are resolved with 0.71. Toggling line numbers on code blocks works fine for me. Or do you have pages with extreme numbers of code blocks on a single page?

@timmie when zim updates the index after starting a new version, a dialog should appear with progress bar. Does this happen for you?

**Comment by sngreen** [comment] 2019-05-24 06:24
Tried on 0.71 and 0.71_1, left panel did not show. Created the new books (well, tired to), re-imported the previous ones (also tried), to no avail. Reverted back to 0.68.

**Comment by jaap-karssenberg** [comment] 2019-05-24 06:42
In 0.71 you need to enable the "pageindex" plugin to have the side
panel.This should be enabled automatically when you upgrade, but under some
conditions that fails and you have to enable in the preferences plugin menu.

See also: https://zim-wiki.org/manual/Help/Migrating_to_latest_version.html

Regards,

Jaap

**Comment by Auerilas** [comment] 2019-09-13 17:03
I just want to say that I am experiencing the same issue. It occurs mostly when I either try to move into a new subpage or create a new page/subpage. Restarting Zim solves the issue for a bit.

```
Here's my system info:
System:    Host: ralien Kernel: 4.15.0-62-generic x86_64 bits: 64 compiler: gcc v: 7.4.0 Desktop: Cinnamon 4.0.10 
           Distro: Linux Mint 19.1 Tessa base: Ubuntu 18.04 bionic 
Machine:   Type: Laptop System: Dell product: XPS 13 9360 v: N/A serial: <filter> 
           Mobo: Dell model: 05JK94 v: A00 serial: <filter> UEFI: Dell v: 2.8.1 date: 06/14/2018 
```

And I'm on Zim 0.68 rc-1. Apparently 0.70 or 0.71 aren't available in the channels for Mint yet.

Is there any info I can provide that might help diagnose?

**Comment by vossenjp** [comment] 2019-09-13 17:15
@Auerilas there are Zim PPAs for Ubuntu that work for Mint-18 and 19, at least.  I'm running `zim-0.72.0-t201909031900~ubuntu16.04.1` from PPA on the Mint-18.3 I'm typing this from.

**Comment by Auerilas** [comment] 2019-09-13 18:01
@vossenjp thanks! I've just updated to 0.72. Will let you know if this issue continues to occur.

**Comment by sngreen** [comment] 2019-09-15 05:27
On Linux 0.71.1 (what was available at that time) has fixed the problem for me. I had to enable "pageindex" plugin first. On Windows it seems it does not matter (0.65 works fine).
@jaap-karssenberg - thank you!

**Comment by Auerilas** [comment] 2019-09-15 15:23
@vossenjp @jaap-karssenberg the problem appears to be resolved with me as well. The page index plugin was enabled by default on my system, and now it updates the index regularly. I'll report back if something happens.

**Comment by itsnotsaved** [comment] 2021-06-07 08:33
https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1489

**Closed** 2022-05-22 08:50 UTC
Labels: bug
