### ISSUE TITLE
Linking by dragging pages from index pane to current page not working in Ubuntu Bionic

### ISSUE THREAD

**Issue by bazzvn** [zim-desktop-wiki/zim-desktop-wiki#782] opened 2019-04-11 04:04 UTC
In Zim 0.68 it was possible to create links to another page in a notebook by dragging that page from the index pane into an open page in the page view. This doesn't seen to work in Zim 0.7 on Ubuntu 18.04 based distros (Mint 19.1 xfce and KDE Neon).  It does work with Zim 0.7 on Manjaro KDE.

**Comment by Self-Perfection** [comment] 2019-04-11 07:56
Probably duplicate of #669

**Comment by jaap-karssenberg** [comment] 2019-04-11 18:26
Duplicate of #390

**Closed by jaap-karssenberg** 2019-04-11 18:26 UTC
