### ISSUE TITLE
Sort page hierarchy for Roman numerals

### ISSUE THREAD

**Issue by Aelthien** [zim-desktop-wiki/zim-desktop-wiki#2366] opened 2023-05-26 08:29 UTC
Trying to sort things by roman numerals is not possible as it defaults to alphabetical only. Perhaps have an option to manually sort pages and subpages too?

As you can see in the picture below IX which is 9 should be after VIII but it's sorted alphabetically.

![bb2f336ce63cb07ad064332795bf0480](https://github.com/zim-desktop-wiki/zim-desktop-wiki/assets/1349527/b7ab919d-1290-4fdf-9657-8c1e2d6f4a4a)

**Comment by k4nzdroid** [comment] 2023-05-26 08:38
The Unicode !!! hahahahaha
https://symbl.cc/en/collections/roman-numerals/
![image](https://github.com/zim-desktop-wiki/zim-desktop-wiki/assets/40691275/eda33e8f-6d5d-4411-8247-1c1c40b8fba1)

**Comment by Aelthien** [comment] 2023-05-26 08:42
> 

![bb2f336ce63cb07ad064332795bf0480](https://github.com/zim-desktop-wiki/zim-desktop-wiki/assets/1349527/605bfef9-700d-4e1a-bf79-d563b0a1eb18)

**Comment by introt** [comment] 2023-06-11 08:54
Thanks for the ticket, considering this a duplicate of #32. You may want to use a manual "table-of-contents" consisting of links in the meantime.

**Closed as not planned by introt** 2023-06-11 08:54 UTC
Labels: duplicate, enhancement
