### ISSUE TITLE
Double brackets iimage input cannot be disabled

### ISSUE THREAD

**Issue by Twiins** [zim-desktop-wiki/zim-desktop-wiki#602] opened 2019-01-11 20:36 UTC
The charachters {{ }} seems to replace images, but this option cannot be disabled.

**Comment by jaap-karssenberg** [comment] 2019-01-18 19:24
Yes, this is a feature, not a bug. Sorry WOn't fix.

**Closed by jaap-karssenberg** 2019-01-18 19:24 UTC

**Comment by Twiins** [comment] 2019-01-19 01:41
Thank you so much for your reply Jaap! I saw the update where you stated
you would add this in. Is there any way to disable the functionality?

I copy and paste a lot of notes from configuration files in a cloud
service. It includes many instances of this notation, and will
automatically convert my notes into a (!) for a missing image. Disabling
the Auto formatting optoins in the preferneces menu does not seem to help
with this. Anything you can offer would be helpful.

Thanks,
Joshua Baker
