### ISSUE TITLE
Change zim wiki tree structure

### ISSUE THREAD

**Issue by tecepe** [zim-desktop-wiki/zim-desktop-wiki#379] opened 2018-03-10 19:04 UTC
Hi,

This is a rather bold suggestion, I know. Please bear with me. 

I often struggle with the several files and folders in the base of my notebooks because the notes their related attachment folders are separated. File systems have limit for the number of files that can be stored in a folder (and notes in these notebooks tend to pile up with time). This suggestion also would take care of my other issue #378 .

The idea is to store each note in its own folder from the start. We could have a standard filename for the note (as  web does with `index`) or we could have a predictable behavior, such as the filename and the folder with same base name as it is today, but with the file inside the folder.

I believe this alternative wiki tree structure should be optional, due to several reasons.

**Comment by jaap-karssenberg** [comment] 2018-03-19 12:39
Open to supporting alternative tree structures - code is prepared to deal with that. I believe there is a previous idea in the tracker that suggests using "README" as the page file for each folder.

Would be configurable on creating the notebook. Would need an "import" function to convert existing notebooks.

**Comment by tecepe** [comment] 2018-03-19 13:27
Thanks for looking at this, @jaap-karssenberg ! I know you are investing a lot of effort in other areas of the zim notebook. I believe we are in the same page about this request. I don't have much spare time, but if you give me specific instructions, I'm interested to help to make this happen. I've reasonable Python skills.

**Comment by jaap-karssenberg** [comment] 2018-03-19 13:40
Good point - let me put some notes here for whoever wants to work on this:
- New work should be based on the Gtk3 / python3 "next" branch
- Step 1: implement an alternative of the notebook [layout class](https://github.com/jaap-karssenberg/zim-desktop-wiki/blob/270c844fcb4e085d70165239745e1b503220101b/zim/notebook/layout.py#L67) -- and a test case
- Step 2: instead of using hardcoded layout, check the notebook config and decide which one to use [here](https://github.com/jaap-karssenberg/zim-desktop-wiki/blob/270c844fcb4e085d70165239745e1b503220101b/zim/notebook/notebook.py#L246) -- please keep current implementation as default -- after this step you can start using / testing the new layout by manually modifying `notebook.zim`
- Step 3: add option in the ["new notebook" dialog](https://github.com/jaap-karssenberg/zim-desktop-wiki/blob/270c844fcb4e085d70165239745e1b503220101b/zim/gui/notebookdialog.py#L400) and hand it off to the `init_notebook` function for all places where this dialog is used -- preferable below an expander for "advanced options" or similar to avoid distracting non-technical users -- and update manual to document this option

**Comment by jaap-karssenberg** [comment] 2018-03-23 16:04
Duplicate of issue #54

**Closed** 2021-10-19 19:25 UTC
Labels: enhancement
