### ISSUE TITLE
Tableeditor: suggestion to add highlighting colors

### ISSUE THREAD

**Issue by happycamper31** [zim-desktop-wiki/zim-desktop-wiki#1415] opened 2021-03-08 11:54 UTC
Hello,
Currently it is only possible to highlight table entries with yellow color. Since that wasn't enough for me I 'enhanced' my tableedit a bit by adding some colors. I pretty much just copied the mark-entries in the list SYNTAX_WIKI_PANGO2 and edited the colors to my liking. -> To distinguish I inserted a number between the underscores (I tried adding underscores first, but that didn't work well). See the code attached at the bottom.
While I'm pretty sure my current solution isn't great to merge with the code, I'd be happy if more highlighting colors get added in new releases, regardless how it is implemented. This is the suggestion I came up with ;-)

example how it could look like:
`SYNTAX_WIKI_PANGO2 = [
	(r'<strong>\1</strong>', r'<b>\1</b>', r'**\1**'),
	(r'<mark>\1</mark>', r'<span background="yellow">\1</span>', r'__\1__'),
	(r'<mark>\1</mark>', r'<span background="purple">\1</span>', r'_1_\1_1_'),
	(r'<mark>\1</mark>', r'<span background="darkgreen">\1</span>', r'_2_\1_2_'),
	(r'<mark>\1</mark>', r'<span background="darkblue">\1</span>', r'_3_\1_3_'),
...
]`

BR happycamper

**Comment by introt** [comment] 2021-12-15 17:36
Hi! Syntax isn't limited to tables; considering this to be a duplicate of #268. Please continue the discussion there, thank you!

**Closed by introt** 2021-12-15 17:36 UTC
