### ISSUE TITLE
Source View plugin has no syntaxes

### ISSUE THREAD

**Issue by gabrielfreiberg** [zim-desktop-wiki/zim-desktop-wiki#685] opened 2019-02-26 16:03 UTC
I'm on macOS High Sierra 10.13.6 and have zim installed via homebrew.

`❯ brew info zim`

`
zim: stable 0.69 (bottled), HEAD
Graphical text editor used to maintain a collection of wiki pages
http://zim-wiki.org/
/usr/local/Cellar/zim/0.69 (580 files, 8.1MB) *
  Poured from bottle on 2019-02-26 at 08:28:47
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/zim.rb
==> Dependencies
Build: pkg-config ✔
Required: graphviz ✔, gtk+ ✔, pygobject ✔, pygtk ✔, pygtksourceview ✔, python@2 ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 110 (30 days), 442 (90 days), 1,429 (365 days)
install_on_request: 111 (30 days), 440 (90 days), 1,436 (365 days)
build_error: 0 (30 days)
`

Seems like all should be working but when I go to Insert Code Block, there are no syntaxes available.

![image](https://user-images.githubusercontent.com/1455224/53427036-23dc9300-39b6-11e9-9c8e-1fc67b86f9cf.png)

**Comment by Osndok** [comment] 2019-02-26 17:40
I would bet that it has to do with the brew script, it probably installs gtksourceview but no syntax plugins. I don't have a lot of time to devote to digging into this, but I am greatly interested in this b/c I would actually like to kern down the huge list of syntaxes (on my installations) to just a few that I commonly use... so I guess I have the opposite problem.

I'm on Linux, so I'm sure our paths will be different, but maybe this will help you?
```
$ rpm -ql gtksourceview2 | grep specs | head
/usr/share/gtksourceview-2.0/language-specs
/usr/share/gtksourceview-2.0/language-specs/R.lang
/usr/share/gtksourceview-2.0/language-specs/ada.lang
/usr/share/gtksourceview-2.0/language-specs/asp.lang
/usr/share/gtksourceview-2.0/language-specs/awk.lang
/usr/share/gtksourceview-2.0/language-specs/bibtex.lang
/usr/share/gtksourceview-2.0/language-specs/boo.lang
/usr/share/gtksourceview-2.0/language-specs/c.lang
/usr/share/gtksourceview-2.0/language-specs/cg.lang
/usr/share/gtksourceview-2.0/language-specs/changelog.lang
...
$ rpm -ql gtksourceview2 | grep specs | wc -l
84
$ rpm -ql gtksourceview3 | grep specs | wc -l
137
```

**Comment by gabrielfreiberg** [comment] 2019-02-26 17:50
I found the package and dug around the folder:

`❯ ls /usr/local/Cellar/gtksourceview/2.10.5_3/share/gtksourceview-2.0/language-specs
R.lang       changelog.lang  cuda.lang      dpatch.lang   gap.lang               idl.lang         libtool.lang   objc.lang    pkgconfig.lang  sparql.lang   verilog.lang
ada.lang     chdr.lang       d.lang         dtd.lang      glsl.lang              ini.lang         lua.lang       ocaml.lang   po.lang         sql.lang      vhdl.lang
asp.lang     check.sh        def.lang       eiffel.lang   gtk-doc.lang           java.lang        m4.lang        ocl.lang     prolog.lang     styles.rng    xml.lang
awk.lang     cmake.lang      desktop.lang   erlang.lang   gtkrc.lang             javascript.lang  makefile.lang  octave.lang  python.lang     t2t.lang      xslt.lang
bibtex.lang  convert.py      diff.lang      fcl.lang      haddock.lang           language.dtd     mallard.lang   ooc.lang     rpmspec.lang    tcl.lang      yacc.lang
boo.lang     cpp.lang        docbook.lang   forth.lang    haskell-literate.lang  language.rng     msil.lang      pascal.lang  ruby.lang       texinfo.lang
c.lang       csharp.lang     dosbatch.lang  fortran.lang  haskell.lang           language2.rng    nemerle.lang   perl.lang    scheme.lang     vala.lang
cg.lang      css.lang        dot.lang       fsharp.lang   html.lang              latex.lang       nsis.lang      php.lang     sh.lang         vbnet.lang`

**Comment by Osndok** [comment] 2019-02-26 18:13
I would bet, then, that the issue is that they are not found at runtime... a workaround might be as simple as a symlink.

**Comment by gabrielfreiberg** [comment] 2019-02-26 18:33
I've tried running zim in Debug mode and Verbose mode to determine the issue, but wasn't able to find it. I'm not sure yet how to determine *where* it's looking for those lang files.

**Comment by Osndok** [comment] 2019-02-26 18:58
I would suggest opening an issue with homebrew, and posting that ticket link here, as it is probably a packaging issue, and would be fixed on their side anyway.

**Comment by jaap-karssenberg** [comment] 2019-03-14 19:04
Afraid this is not a zim issue

**Closed by jaap-karssenberg** 2019-03-14 19:04 UTC
