### ISSUE TITLE
Icons disappear with Kubuntu20.04 dark theme

### ISSUE THREAD

**Issue by erichcavalcanti** [zim-desktop-wiki/zim-desktop-wiki#1178] opened 2020-07-12 05:15 UTC
If I activate the standard dark theme from kubuntu 20.04 some icons disappear at Zim.

**Comment by introt** [comment] 2021-12-15 15:55
Duplicate of another issue that's merged to the linked issue- please continue discussion there. Thanks!

**Closed by introt** 2021-12-15 15:55 UTC
