### ISSUE TITLE
Flushing page with unsaved changes

### ISSUE THREAD

**Issue by codingRubbish** [zim-desktop-wiki/zim-desktop-wiki#1391] opened 2021-02-07 14:43 UTC
Hello again,

First apologies if this isn't a bug. The bug window popped up again whilst I was editing a page with the message:

```
This is zim 0.73.4
Platform: nt
Locale: en_GB cp1252
FS encoding: utf-8
Python: (3, 8, 5, 'final', 0)
PyGObject: (3, 38, 0)

======= Traceback =======
  File "zim/actions.py", line 115, in do_activate
  File "zim/actions.py", line 98, in func
  File "zim/gui/mainwindow.py", line 923, in reload_page
  File "zim/notebook/operations.py", line 372, in wrapper
  File "zim/notebook/notebook.py", line 471, in flush_page_cache
AssertionError: BUG: Flushing page with unsaved changes
```

Not 100% sure what I was doing at the time but I was editing the source of a file in Notepad++ (having used ``Tootls > Edit Source``). I was editing a table I had inserted to format some of the cell contents as as Verbatim. I couldn't do this after I'd created the table as the formatting syntax showed in the cell contents (might be my lack of knowledge on how to do this from Zim).

When I'd finished, saved the file in Notepad++, and went back to Zim, I refreshed the page (``Ctrl R``)and the bug window popped up after that. This may or may not have something to do with the table being on the last line of the page, again forgive my ignorance.

Anyway I hope this may be a proper bug this time.

**Comment by dornstetter** [comment] 2021-04-11 10:25
Duplicate of #1119

**Closed** 2021-12-15 16:26 UTC
