### ISSUE TITLE
Problems after index: Right click broken in 'Index' and buttons in pop-up windows have different language

### ISSUE THREAD

**Issue by oldcreakyknees** [zim-desktop-wiki/zim-desktop-wiki#810] opened 2019-04-23 13:06 UTC
Hi,

My first time posting here, so I'll start off with saying "Thank you " for creating and maintaining Zim.

I'm running Zim as follows: 
Ubuntu 16.04
Installed from PPA: http://ppa.launchpad.net/jaap.karssenberg/zim/ubuntu
Installed version 0.70~ubuntu16.04.1

A couple of weeks ago an 'indexing' notification popped up in Zim (not sure if I inadvertently clicked a keyboard shortcut or whether Zim did it on its own) but with one of the buttons not in English (It was labelled 'Megse', I think). It took a few minutes to complete.

Since then, when I right click on a page in in the "Index" tab in the Side Pane, a pop-up appears with: "The application Zim Desktop Wiki has closed unexpectedly." (... although Zim still seems to run). This is from the Error report:
Title: 
Zim crashed with AttributeError in do_button_event():'Menu' object has no attribute 'popup_at_pointer'
Traceback:
File "/usr/lib/pythin3/dist-packages/zim/gui/widgets.py", line 563 do_button_press_evenet
menu.popup_at_pointer(event)
AttributeError: 'Menu' object has no attribute 'popup_at_pointer'

Also, since then buttons in modals(?) are now in a mixture of languages: eg 
Task list: Buttons are 'Nyomtatas' and 'Close'; 
New Page : Buttons are 'Megse' and 'OK';  
Select File : Buttons are 'Megse' and 'Open'

... and in the list of plug-ins: "Name: Oldalindex"

Any idea what might be going on and how to fix this? (Zim is still usable but not as straightforward as it was before this happened!)

All the best.

**Comment by oldcreakyknees** [comment] 2019-04-24 16:17
The second part of this "Also, since then buttons in modals(?) are now in a mixture of languages" seems to be addressed here: https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/6640

**Comment by tildagail** [comment] 2019-04-26 05:26
The right-click in index problem is probably #731 . Ubuntu 16.04 uses GTK version 3.18, while Zim 0.70 was built for 3.22. It might be fixed in 0.71 (hopefully!).

Alternatively, you can uninstall 0.70 and replace it with 0.69, which you can download from https://zim-wiki.org/downloads/ (this requires a bit of stuffing around with settings etc :( - I had to empty the Zim folder in .cache and delete the fullscreen settings from the main config file to make it work)

**Comment by jaap-karssenberg** [comment] 2019-04-26 18:35
Duplicate of #731 and #664

**Closed by jaap-karssenberg** 2019-04-26 18:35 UTC

**Comment by oldcreakyknees** [comment] 2019-04-26 22:34
... okay thanks.

So, dropped the PPA, backed up, uninstalled, re-installed from 16.04 
repos - now back to version 0.65!

Things are working again: right click menu and buttons in wrong 
language. So waiting for next release with bug fixes. I look forward to it!

(:
