### ISSUE TITLE
Minor: links ending with a closing square bracket

### ISSUE THREAD

**Issue by nelas** [zim-desktop-wiki/zim-desktop-wiki#596] opened 2019-01-03 09:24 UTC
When I create a link to a page name ending with a closing square bracket, this bracket is stripped off the text of the link like this:

![zim bracket](https://user-images.githubusercontent.com/361179/50630235-52069f00-0f40-11e9-9bb1-23941ad28e82.png)

This happens after navigating away from the page where the link was created and coming back to it. It does not happen upon saving or reloading the page. Also, it does not happen with other brackets.

When the linked page already exists, the `Link to:` value is unchanged - that is, the closing squared bracket is not stripped off and the link is not broken. But it seems that when creating a link to a page does not exists, the closing squared bracket is also removed from both `Link to:` and `Text:` fields.

**Comment by jaap-karssenberg** [comment] 2019-02-11 19:55
This is intended behavior, since we cannot distinguish the "]" from the "[[..]]" link markup when parsing the wiki source. Could refine by at least testing against "[" in the text part of the link and pulling matched brackets. But I really consider this an edge case.

**Comment by myrdd** [comment] 2019-05-13 17:28
> When the linked page already exists, the `Link to:` value is unchanged

not true for me. `[[+foo]]]` is interpreted as `[[+foo]]` + `]` after reloading, even if sub-page `foo]` exists. Using Zim v0.71.0.

> But I really consider this an edge case.

I agree. But somewhat related to your comment over there, regarding `#` in file links, e.g. `file:///tmp/test.html#anchor`: https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/488#issuecomment-462481199

**Comment by jaap-karssenberg** [comment] 2020-04-09 18:39
Committed a fix that will handle trailing "]" in the link text based on matching "[" brackets in the text.

E.g. "[[[foo]]]" = "[<link>foo</link>]" but "[[foo[bar]]]" = "<link>foo[bar]</link>

**Closed** 2020-06-06 13:20 UTC
Labels: enhancement, fix available
