### ISSUE TITLE
Initial size of newly added images / auto-resizing images

### ISSUE THREAD

**Issue by webdevelopers-eu** [zim-desktop-wiki/zim-desktop-wiki#2590] opened 2024-03-24 07:21 UTC
**Is your feature request related to a problem? Please describe.**

The issue arises when pasting images, which typically involves manually adjusting dimensions in the properties dialog. This process accounts for about 80% of the time spent, which is inefficient. Having to go through three extra steps (open, change, save) during simple image pasting is unsatisfactory, especially when trying to recall the ideal width I figured last time...

**Describe the solution you'd like**

I propose the addition of a "default maximum width" setting, which would define the width of newly pasted images. This setting would only adjust the width if the image exceeds it, while maintaining the aspect ratio by adjusting the height accordingly.

Optional: Additionally, providing the option to double-click an image to open it in an external preview program would enhance user experience. If implemented, the next logical step could involve utilizing keyboard modifiers when drag-dropping images from the Attachment pane, resulting in the insertion of small image thumbnails instead of the original or "maximum width" size. This feature would facilitate quick insertion of images into the Attachment pane, followed by CTRL+dragging them into content to create a small preview that can be double-clicked to display the full-size image, simplifying the process of working with image drafts and ideas.

**Describe alternatives you've considered**

I considered automatically resizing images to fit the available width of the panel which would be ideal. However, I believe implementing the suggested preset solution would be simpler and more likely to be accepted as a viable solution.

**Comment by introt** [comment] 2024-04-14 09:16
Hi! Thanks for the FR, afraid it's a duplicate of #1423. See also: https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1423#issuecomment-2052265493

**Closed as not planned by introt** 2024-04-14 09:16 UTC
Labels: duplicate
