### ISSUE TITLE
OperationalError: database is locked

### ISSUE THREAD

**Issue by scapharnaum** [zim-desktop-wiki/zim-desktop-wiki#2589] opened 2024-03-22 12:15 UTC
**Describe the bug**
A window "it seems that you have found a bug" appears

**To Reproduce**

**Expected behavior**
The problem occurs at the start of Kubuntu 18.04.

**Screenshots**
======= Traceback =======
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 921, in main
    ZIM_APPLICATION.run(*argv[1:])
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 684, in run
    self._run_cmd(cmd, args) # test seam
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 714, in _run_cmd
    self._run_main_loop(cmd)
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 756, in _run_main_loop
    w = cmd.run()
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 277, in run
    return self._run_new_window(notebook, page)
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 324, in _run_new_window
    **self.get_options('geometry', 'fullscreen')
  File "/usr/lib/python3/dist-packages/zim/plugins/__init__.py", line 100, in _init_wrapper
    orig_init(self, *arg, **kwarg)
  File "/usr/lib/python3/dist-packages/zim/gui/mainwindow.py", line 331, in __init__
    self.open_page(page)
  File "/usr/lib/python3/dist-packages/zim/gui/mainwindow.py", line 774, in open_page
    self.notebook.index.touch_current_page_placeholder(path)
  File "/usr/lib/python3/dist-packages/zim/notebook/index/__init__.py", line 275, in touch_current_page_placeholder
    (ROOT_ID,)
OperationalError: database is locked.

**Environment (please complete the following information):**
 This is zim 0.72.1
Platform: posix
Locale: fr_FR UTF-8
FS encoding: utf-8
Python: (3, 6, 9, 'final', 0)
PyGObject: (3, 26, 1)

**Additional context**
OS GNU/Linux Kubuntu KDE Plasma 18.04

**Comment by introt** [comment] 2024-03-22 19:43
I'm afraid we don't support Zim 0.72.1 anymore, please see if the problem is fixed in a later version and if not, open a new ticket.

**Closed as not planned by introt** 2024-03-22 19:43 UTC
Labels: bug, needs triage
