### ISSUE TITLE
Cursor slow, typing delay

### ISSUE THREAD

**Issue by sbic** [zim-desktop-wiki/zim-desktop-wiki#1542] opened 2021-08-11 13:47 UTC
Since I moved from python 2 to python 3 with zim the cursor is slow when typing or moving. And when I type a character it takes about 1 second until I see it on screen. The response time of other parts of the UI are also slow but the cursor / typing delay is the most annoying for me. 

I use zim since 10 years and love it, but this cursor delay makes it hard for me to use it. 

Do you have any idea what could be the problem?

I use zim 0.73.5 on MacOS 11.4 using Python 3.9.1. 
And on my machine gtk+ version 2.24.33 and gtk+3 version 3.24.24 is installed. Maybe this is important.

**Comment by jaap-karssenberg** [comment] 2021-08-11 14:56
I personally don't have MacOS experience but there have been reports in the
past suggesting disabling the "pathbar" plugin might help for performance
issues.

-- Jaap

**Comment by sbic** [comment] 2021-08-11 15:13
Thanks a lot. Disabling the pathbar plugin fixes the issue. This is great!

I find the pathbar very very helpful for navigating between the important files. Without the pathbar, I need to restructure my files so that the important ones are easily findable in the regular index tab.

**Comment by introt** [comment] 2021-08-11 17:07
> Without the pathbar, I need to restructure my files so that the important ones are easily findable in the regular index tab.

Does the BookmarkBar plugin suffer from the same issue? If it does, it should be investigated as well; if it doesn't, maybe it could be of use to you.

**Comment by sbic** [comment] 2021-08-11 19:11
Yes, unfortunately, the BookmarkBar suffers from the same issue.

It was already pointed out in some other thread that this is probably related to this issue: https://gitlab.gnome.org/GNOME/gtk/-/issues/3714

For me switching off pathbar and BookmarBar is fine. I just created a bookmark link list in the "Home"-document and use this as navigation hub.

**Comment by introt** [comment] 2021-08-12 05:12
> this is probably related to this issue: https://gitlab.gnome.org/GNOME/gtk/-/issues/3714

Seems so. Guess this should be tagged as `Upstream issue`.

I'm glad you've found a suitable alternative in the meantime!

**Comment by introt** [comment] 2021-12-15 18:32
@kjyv @sbic does the issue persist with the new MacOS installer?

**Comment by sbic** [comment] 2021-12-16 08:32
I installed zim 0.74.2 using the [mac installer from Rene de Hesselle](https://gitlab.com/dehesselle/zim_macos/-/releases).
The slowness problem that I described earlier is gone with this. I am fine now. Thank you.

**Comment by introt** [comment] 2021-12-20 15:42
@sbic You're welcome, glad that's resolved! Will wait a bit to hear from @kjyv before closing the issue.

**Comment by kjyv** [comment] 2021-12-20 20:26
0.74.3 from installer works ok on Monterey, Macbook with M1 and on Big Sur is better but still sluggish

**Comment by kjyv** [comment] 2021-12-21 10:47
It's similar on Monterey, usable but slightly slower than before. I guess the original issue is solved as typing is fine, but there still is noticeable delay when pressing enter for a new line and scrolling is a little bit sluggish.

**Comment by dehesselle** [comment] 2021-12-21 11:13
GTK 3.24.31 has just landed and includes the patch mentioned above. I'll create a new release later today and then close this issue. This will be as good as it gets.

**Comment by dehesselle** [comment] 2021-12-21 15:19
Scratch that, GTK 3.24.31 is broken and doesn't build at the moment.

**Comment by kjyv** [comment] 2021-12-23 17:20
Pity there is a problem with building GTK in case this version was supposed to fix things. The ticket mentions a specific gimp patch that has not made it upstream though and it's still open? Anyway, for now my feedback is that Zim can be used on Monterey using the installer. This ticket should still stay open though because editing notes simply does not feel right - the reactions to input are still slightly delayed. Sadly I managed to delete the 0.73.5 version which I believe was also an installer from @dehesselle from somewhere in the github issues - installing it with brew in Monterey produces a segfault now (as does the newest version).

**Comment by dehesselle** [comment] 2021-12-28 19:07
@kjyv Can you compare the perceived input delay between the following two development versions (development = not official releases, unsigned):

- Zim 0.73.5: https://gitlab.com/dehesselle/zim_macos/-/jobs/1925944702/artifacts/browse

- Zim 0.74.3: https://gitlab.com/dehesselle/zim_macos/-/jobs/1925763576/artifacts/browse

Everything is identical except the Zim version being used.

**Comment by kjyv** [comment] 2021-12-29 13:59
It's the same as previously mentioned, 0.73.5 is more or less instant with all interaction. 0.74.3 is the same as the current release version, something like 250-500ms delay when moving the cursor or pressing the return key for a new line.
I've noticed that (in both 0.74.3 builds), the cursor and new line delay is dependent on formatting in the text: if the cursor passes e.g. from bold to normal text (or vice versa) and the icon in the edit toolbar on the bottom is changing, the delay happens. Also when going over a link that shows the url on black background. Moving the cursor over a document without formatting, there are no delays.

**Comment by dehesselle** [comment] 2021-12-29 14:08
Thanks for testing. That confirms that the underlying issue is Zim itself. I am going to remove the upstream label as well as unassign myself from this issue, there is nothing I can do here.

**Comment by kjyv** [comment] 2021-12-29 14:18
Sure. Thanks for the 0.73.5 build ;) 
I guess it is possible that this is caused by new GTK features that the newer Zim version is using for the edit bar, same as the path bar and bookmark bar plugins which might only be fixed by using an updated GTK version once one is available. Otherwise it should probably show the same slowdowns on other OS'es if this was a pure Zim issue.

**Comment by dehesselle** [comment] 2021-12-29 20:26
Correct. Changes in Zim cause GTK to go into other code paths then before which are apparently not well optimized.

I have one final card to play. Do you notice any improvement with this one:
- https://gitlab.com/dehesselle/zim_macos/-/jobs/1928834757/artifacts/browse

This is a version with a lot of backward compatibility dropped, as many of the recent patches to GTK et al. are compile-time dependent on a more recent macOS versions.

---

Slightly off-topic:
The advice I've been given the most in regards to GTK 3 and macOS is "port to GTK 4". Performance-wise, it's actually in another galaxy on macOS compared to GTK 3. (That claim holds true, I've tested it.) But since there are behavioral changes, dropped functionalities etc. it's usually a lot of work to port to GTK 4.

**Comment by kjyv** [comment] 2021-12-29 20:53
Nice. It's still not as quick as 0.73.5 but it is noticeably better - I would roughly say the delay has been reduced by 25-50%.

GTK 4 is probably an effort that has to/will be done for Zim in general, not just for the macOS port at some point?

**Comment by kjyv** [comment] 2021-12-29 20:58
Another idea (@jaap-karssenberg): maybe whatever needs to be done to update the UI, e.g. show the bold button pressed, can be done async while moving the cursor so that it does not delay moving and editing?

**Comment by jaap-karssenberg** [comment] 2021-12-30 06:25
There is no real async option. You can schedule stuff on idle, but it will still get injected in between keyboard events. Might be worthwhile to try though.

**Comment by kjyv** [comment] 2022-01-04 16:20
I guess even delaying the update of the panel icons until the keyboard has not been touched for half a second or so would do the job. If the cursor is still moving I guess it would be ok if the button state is not immediately in sync?

**Comment by jaap-karssenberg** [comment] 2022-01-04 18:53
A patch to delay the callback should be straight forward. Please use
zim.signals.DelayedCallback to wrap the original callback.

**Comment by kjyv** [comment] 2022-10-09 10:44
This is still an issue in zim 0.75 - so far I've had the edit bar disabled and that was ok. Now in 0.75, it always gets enabled again when starting zim, resetting the preference value.

**Comment by introt** [comment] 2022-10-09 11:31
> Now in 0.75, it always gets enabled again when starting zim, resetting the preference value.

Linking #2184

**Comment by dehesselle** [comment] 2023-02-15 23:09
I'd like to close this. @kjyv you can give the newest release a spin, it uses newest versions of GTK and Cairo. Especially Cairo has gotten some improvements lately.

**Comment by kjyv** [comment] 2023-02-16 08:49
Great, just tried it and it's indeed fixed now and everything is snappy also with the edit bar enabled.

**Comment by dehesselle** [comment] 2023-02-16 09:01
Awesome. Thank you.

**Closed** 2023-02-16 09:50 UTC
Labels: candidate for removal
