### ISSUE TITLE
Zim version 0.75.0 for Windows crashes during startup

### ISSUE THREAD

**Issue by YuryDudorov** [zim-desktop-wiki/zim-desktop-wiki#2163] opened 2022-10-01 13:59 UTC
**Describe the bug**
Zim version 0.75.0 for Windows has been just installed over the previous version 0.74.3. The application has crashed during the first launch. The crash report is attached (**Zim-crash-report.log**). 

The problem did not come up before.

**To Reproduce**
I can reproduce the crash running the equivalent command from the command line.

[/c/Program Files/Zim Desktop Wiki][5186]% "C:/Program Files/Zim Desktop Wiki/zim.exe" --debug --verbose
[/c/Program Files/Zim Desktop Wiki][5187]%

I do not see any additional output.

Zim crashes while opening the default notebook. But it does not contain the string from the error message inside:

[/c/Program Files/Zim Desktop Wiki][5190]% find **e:/Tasks/GTD** -type f -name '*' -exec grep **'\\./SystemVision'** {} \\;
[/c/Program Files/Zim Desktop Wiki][5191]% 

I guess that the problem is caused by this string in the zim/config/zim/notebooks.list file:

[/c/Program Files/Zim Desktop Wiki][5200]% cd /c/Users/ydudorov/AppData/Roaming/
[/c/Users/ydudorov/AppData/Roaming][5202]% grep -B 4 -H **'\\./SystemVision'** **zim/config/zim/notebooks.list**
zim/config/zim/notebooks.list-[Notebook 7]
zim/config/zim/notebooks.list-uri=file:///**E:/Tasks/Tasks/SystemVision**
zim/config/zim/notebooks.list-name=SystemVision
zim/config/zim/notebooks.list-interwiki=SystemVision
zim/config/zim/notebooks.list:icon=**./SystemVision**
[/c/Users/ydudorov/AppData/Roaming][5203]%

The crash went away after replacing the problem line by the "icon=None" one. Zim has successfully started after this manual update. But the erroneous line was restored during Zim startup. So the next Zim launch has failed as expected.

The problem was fixed after manual updating the **E:\Tasks\Tasks\SystemVision\notebook.zim** file. The line **"icon=./SystemVision"** was replaced by the **"icon="** one.

**Environment (please complete the following information):**
 - Version 0.75.0
 - OS: Windows 10 Version 20H2

[Zim-crash-report.log](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/9690314/Zim-crash-report.log)

**Comment by volkman00** [comment] 2022-10-05 00:01
Yes. The problem was solved by setting "icon=something" to blank everywhere.
windows 10

**Comment by jaap-karssenberg** [comment] 2022-10-07 19:25
Duplicate of #2165

**Closed as completed by jaap-karssenberg** 2022-10-07 19:25 UTC
Labels: bug, needs triage
