### ISSUE TITLE
Source visualizer freeze

### ISSUE THREAD

**Issue by e-belair** [zim-desktop-wiki/zim-desktop-wiki#694] opened 2019-03-04 09:28 UTC
Hi, using zim 0.68-rc1 on xubuntu 18.04, I have a problem with the source visualizer plugin.
After inserted code in the wiki page, everything works fine. But If I leave the page, then come back on it. The code is not showed up correctly and the page is like frozen. I can't edit it anymore.

After inserting code:
![image](https://user-images.githubusercontent.com/596562/53723435-10bf3c80-3e68-11e9-8ae5-16bfc2d5f20e.png)

Leave and go back on the page, code not parsed and page frozen (no cursor):
![image](https://user-images.githubusercontent.com/596562/53723458-1f0d5880-3e68-11e9-94cb-0182aa28bc87.png)

EDIT: If on the page I update index, everything is going back ok. But if I leave and go back again, I get the same behavior.

**Comment by krisztianmukli** [comment] 2019-03-04 10:06
It's an old bug, I do not know it is fixed or not in the latest version. Resize the window, when freezing, or turn off line numbering in the sourceview's options.

**Comment by e-belair** [comment] 2019-03-04 10:26
Resizing do the trick. But I don't have line numbering option

**Comment by krisztianmukli** [comment] 2019-03-04 10:35
Sorry, for line numbering right click on the sourceview area on the page, not in the plugin settings.

**Comment by e-belair** [comment] 2019-03-04 11:10
Ha ok thanks!
So it's working if line numbering is disabled

**Comment by Self-Perfection** [comment] 2019-03-04 19:39
This is a duplicate of #296 
@e-belair I suggest closing this issue.

**Closed** 2019-03-05 07:31 UTC
