### ISSUE TITLE
SourceView: the horizontal scrollbar covers the last line.

### ISSUE THREAD

**Issue by k4nzdroid** [zim-desktop-wiki/zim-desktop-wiki#1342] opened 2020-12-25 03:13 UTC
### Problem Description

Plugin: Source View
Text wrap mode: Never wrap lines

For now, it works properly:
![image](https://user-images.githubusercontent.com/40691275/103115487-ac551900-469d-11eb-9fdb-3d1eb883af68.png)

After appending one more letter, The last line is covered by the horizontal scrollbar.
![image](https://user-images.githubusercontent.com/40691275/103115563-1077dd00-469e-11eb-919c-057959215d55.png)

### Cause Analysis

The implementation of the ScrolledWindow cause it.

### My Solution

This is not a Zim bug, but we may need a workaround.

We could let the horizontal scrollbar always visible: `win = ScrolledWindow(self.view, Gtk.PolicyType.ALWAYS, Gtk.PolicyType.NEVER,...`

It's not perfect, but better than covered. :-)

### Update 2020/12/30

Another one solution: `GTK_OVERLAY_SCROLLING=1 zim`

Related Posts:
https://ubuntuhandbook.org/index.php/2019/09/make-scrollbar-always-visible-ubuntu-18-04/
https://www.linuxuprising.com/2019/09/how-to-disable-gnomes-overlay.html

**Comment by introt** [comment] 2021-12-15 17:22
Duplicate of #951; @ me if the issue persists on the latest version

**Closed by introt** 2021-12-15 17:22 UTC
