### ISSUE TITLE
On linux/KDE zim uses firefox, no matter what browser is the system default, when clicking on links

### ISSUE THREAD

**Issue by quesada** [zim-desktop-wiki/zim-desktop-wiki#1400] opened 2021-02-16 17:16 UTC
Checking the  'default applications' confirms the default is brave, but FF is launched when I click a link on zim.
This is dangerous as it usually sends my machine (16gb laptop) to swapping.

On zim preferences I see 'applications', but I can only set the default text editor

**Comment by roland-ruedenauer** [comment] 2021-02-19 23:34
Please provide detailed info about your system and the zim version you've installed.

**Comment by quesada** [comment] 2021-02-21 10:36
Manjaro KDE
zim 0.73.5

**Comment by roland-ruedenauer** [comment] 2021-02-21 17:42
Your observations would imply the fix done in commit 9aa08f1f7ba8a33be37eb9a582a8070014215e14 does not work for Manjaro KDE.

You might try setting the default appliction to open web pages as described on the Zim help page "Default Applications".
Just right-click on a link and try setting your preferred browser as default application in the "Customize..." dialog.

**Comment by quesada** [comment] 2021-02-22 14:06
Thanks so much, didn't know this feature existed! Fixed now!

**Comment by sanjarcode** [comment] 2021-02-28 09:57
Great! Can you close this issue now, @quesada?

**Comment by FredericoCoelhoNunes** [comment] 2021-06-22 08:41
When I click on the "Customize..." dialog, nothing happens. Ubuntu 18.04

**Comment by jaap-karssenberg** [comment] 2021-06-22 18:41
@FredericoCoelhoNunes please check the debug output for errors

**Comment by FredericoCoelhoNunes** [comment] 2021-06-23 13:24
Problem fixed itself on Zim restart! Thanks

**Comment by roland-ruedenauer** [comment] 2021-12-08 19:46
This old issue might be related to https://github.com/zim-desktop-wiki/zim-desktop-wiki/pull/1787

**Comment by jaap-karssenberg** [comment] 2021-12-09 12:47
Assume duplicate of #1531

**Closed** 2021-12-09 12:47 UTC
