### ISSUE TITLE
Zim Wiki fails to start after upgrade to 0.75 on Debian

### ISSUE THREAD

**Issue by ramesh-rv** [zim-desktop-wiki/zim-desktop-wiki#2208] opened 2022-10-25 05:21 UTC
**Describe the bug**
* I tried upgrading Zim Desktop Wiki downloading and installing the [zim_0.75.0_all.deb](https://zim-wiki.org/downloads/zim_0.75.0_all.deb) using dpkg utility on LMDE5 (Linux Mint Debian Version). Upgrade was successful without any errors.
* When I tried to launch Zim Desktop Wiki it fails to launch with the error message
```
This is zim 0.75.0
Platform: posix
Locale: en_US UTF-8
FS encoding: utf-8
Python: (3, 9, 2, 'final', 0)
PyGObject: (3, 38, 0)

======= Traceback =======
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 966, in main
    ZIM_APPLICATION.run(*argv[1:])
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 737, in run
    self._run_cmd(cmd, args) # test seam
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 768, in _run_cmd
    self._run_main_loop(cmd)
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 810, in _run_main_loop
    w = cmd.run()
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 272, in run
    notebook, pagelink = self.build_notebook()
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 234, in build_notebook
    notebookinfo = self.get_default_or_only_notebook()
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 133, in get_default_or_only_notebook
    notebooks = get_notebook_list()
  File "/usr/lib/python3/dist-packages/zim/notebook/info.py", line 26, in get_notebook_list
    return NotebookInfoList(file)
  File "/usr/lib/python3/dist-packages/zim/notebook/info.py", line 244, in __init__
    self.read()
  File "/usr/lib/python3/dist-packages/zim/notebook/info.py", line 255, in read
    self.parse(lines)
  File "/usr/lib/python3/dist-packages/zim/notebook/info.py", line 330, in parse
    info = NotebookInfo(**section)
  File "/usr/lib/python3/dist-packages/zim/notebook/info.py", line 164, in __init__
    self.icon = FilePath(icon).uri if icon else None
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 249, in __init__
    self.path = _joinabspath(self.pathnames, origpath=path)
  File "/usr/lib/python3/dist-packages/zim/newfs/base.py", line 193, in _joinabspath
    raise ValueError('Not an absolute path: %s' % (origpath or '/'.join(names)))
ValueError: Not an absolute path: ./new-logo.png
```

**To Reproduce**
1. Download  [zim_0.75.0_all.deb](https://zim-wiki.org/downloads/zim_0.75.0_all.deb) to the ~/Downloads directory
2. Open terminal. Run the command dpkg -i ~/Downloads/zim_0.75.0_all.deb 
3. Upgrade must be successful.
4. Click on the Zim-Desktop-Wiki icon to launch the wiki

**Expected behavior**
The desktop-wiki should launch without errors

**Screenshots**
* None
* Error  pasted above

**Environment (please complete the following information):**
 - Version [e.g. 0.74.0] -- 0.75.0 stable
 - OS: [e.g. linux/windows/mac os] - Linux Mint Debian 5 (LMDE5)
 ```
uname -a 
Linux desktop 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux
```
 - Language: English

**Additional context**
* Downgrading to 0.74.3 works. 
* I downloaded and installed 0.74.3 deb version and launched the wiki without any errors.

**Comment by jaap-karssenberg** [comment] 2022-10-25 18:47
Duplicate of #2165

**Closed as completed** 2022-10-25 18:47 UTC
Labels: bug, needs triage
