### ISSUE TITLE
move sub page to another page does not work activcates whoopsie bug report 0.73.1 xubuntu

### ISSUE THREAD

**Issue by galenthurber** [zim-desktop-wiki/zim-desktop-wiki#1136] opened 2020-06-20 13:16 UTC
this bug is still evident on my computers

Zim 0.73.1

while attempting to move a sub page to another page, the sub page is not moved
and 
whoopsie activates for my Xubuntu machines

Expect the move page function to work and not cause errors

please do not delete this report or mark invalid

**Comment by Nick222** [comment] 2020-06-20 13:20
I cannot understand...

Movie, please, if it possible...

**Comment by galenthurber** [comment] 2020-06-20 13:47
movie attached
mkv zip
[yt-2020-06-20_10.42.mkv.zip](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/4807970/yt-2020-06-20_10.42.mkv.zip)

zip

**Comment by Nick222** [comment] 2020-06-20 16:21
Not confirm
Xubuntu 20.04
Zim 0.73.1
[Zim-2020-06-20.zip](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/4808198/Zim-2020-06-20.zip)

**Comment by jaap-karssenberg** [comment] 2020-06-23 19:03
Also cannot reproduce the issue. Can you run zim with "zim -D" from a
terminal and see if there are error messages when you try the move?

Thanks,

Jaap

**Comment by galenthurber** [comment] 2020-07-04 12:25
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: Drag data requested, we have internal path "1st-page:galen email addresses"
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/__init__.py", line 512, in do_drag_data_received
    assert len(names) == 1
AssertionError

then it triggers whoopsie

**Comment by veghp** [comment] 2020-07-06 20:57
I can also confirm the existence of the problem in Zim 0.73.1 on Ubuntu 18.04. The file is moved to the root of the notebook.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/__init__.py", line 512, in do_drag_data_received
    assert len(names) == 1
AssertionError

```
This wasn't an issue in Zim 0.68-rc1

**Comment by veghp** [comment] 2020-07-06 21:10
When a new location is chosen from the dropdown menu in the box, the path is prepended by `+`, e.g. `+docs:today`.  If the `+` is removed (`docs:today`), then zim moves the note without a problem.

**Comment by jaap-karssenberg** [comment] 2020-07-10 15:53
@galenthurber this would be the issue tracked in #390

**Comment by jaap-karssenberg** [comment] 2020-07-10 15:54
@veghp your last comment seems to indicate an issue that is not drag-and-dropas described above, please use a new issue for this

**Comment by veghp** [comment] 2020-07-11 11:16
Thanks. I came across this while I was looking into the drag-and-dropping problem, but now I see it may be a different issue.

**Comment by galenthurber** [comment] 2020-12-14 14:53
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/__init__.py", line 514, in do_drag_data_received
    assert len(names) == 1, 'Could not get pagenames from: %r' % data
AssertionError: Could not get pagenames from: b''
DEBUG: Drag data requested, we have internal path "000:level2a:2 b moved"
DEBUG: Drag data recieved: b''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/zim/plugins/pageindex/__init__.py", line 514, in do_drag_data_received
    assert len(names) == 1, 'Could not get pagenames from: %r' % data
AssertionError: Could not get pagenames from: b''
DEBUG: Action: show_debug_log

**Comment by jaap-karssenberg** [comment] 2022-03-08 20:27
Duplicate of #390

**Closed by jaap-karssenberg** 2022-03-08 20:27 UTC
Labels: bug, needs triage
