### ISSUE TITLE
index sorting not consistent

### ISSUE THREAD

**Issue by kareliot** [zim-desktop-wiki/zim-desktop-wiki#528] opened 2018-09-12 10:14 UTC
Currently, the index of my notebook is no longer sorted alphabetically, or at least not consistently.
This seems to be a fairly recent issue as it was not the case earlier.

My index looks a bit like this:
- A-article [sorted alphabetically]
- B-article [sorted alphabetically]

- F-article [sorted alphabetically]
...
- Z-article [sorted alphabetically]
- **B-article [not sorted correctly]**
- **M-article [not sorted correctly]**
....
etc,
the incorrectly sorted pages are probably ones that have been added recently.

What could be the reason for this inconsistent sorting?

**Comment by stewit** [comment] 2018-10-02 08:53
I can confirm this. Maybe an update of system packages (probably related to the GTK Widget?) introducing a different sorting behaviour in the GTK component?

**Comment by kareliot** [comment] 2018-10-02 09:00
I just deleted the index in ~/.cache/zim/Notebook and let it rebuild itself. That helped and the issue has not returned so far

**Comment by stewit** [comment] 2018-10-02 09:12
Thank you, deleting the index solves this.

**Comment by sojusnik** [comment] 2018-11-06 11:46
Same here with Ubuntu 18.10 on Zim 0.68.
Search for `~/pathtoyournotebook/.zim/index.db` and delete it. The file will rebuild itself after Zim is launched.

**Comment by Self-Perfection** [comment] 2018-11-07 08:00
Have you tried **running Tools -> Update Index**? That action should resolve such issues without hassle of manual deletion of index file.

**Comment by sojusnik** [comment] 2018-11-07 08:40
Of course, but only deleting `index.db` helped.

**Comment by krf** [comment] 2018-11-27 11:38
Same problem here, Zim 0.68 from Ubuntu 18.10. Only rm'ing index.db helped. Running *Tools -> Update Index* did NOT.

**Comment by Bujiraso** [comment] 2018-12-16 18:15
Also having this.
I don't have an index.db -- so I could not delete it. I do not even have a .zim directory.
Update Index does not fix this.

It seems to be that when I rename a sub-page it suddenly wants to sort differently -- into a second category of "pages that have been renamed". This weirdness continues past restart of the application so it *must* be a *persisted* issue. Somewhere, something is getting written wrong so it can be read wrong again.
Can anyone confirm this step to reproduce? 

* Choose or create a  page that has never been renamed before.
* Verify it is well-sorted in the upper group of sorted pages (the "renamed" pages)
* Rename this well-sorted page and see what happens to its sorting.

**Comment by Osndok** [comment] 2019-01-30 15:21
@Bujiraso did you look under ```~/.cache/zim``` for the index?

**Comment by jaap-karssenberg** [comment] 2019-01-30 15:45
The index contains a "sortkey" field which determines the sorting in the
index view. What I think is happening here is that the way this sortkey is
determined changed between the intial setup of the notebook and the moment
in time when you renamed them. This could be the same root cause as seen
for issue #19 .

Looking over the code there is only a single point where this key is
updated, nothing special happens for a move with respect to creating a new
file.

If my suspicion is correct, this issue will not reproduce on a blank test
notebook or after removing the "index.db" file. (Alternative is to run zim
with "zim --index -V path/to/notebook" to force a full refresh.)

In the upcoming 0.70 release I've added an additional check to enforce the
sortkey is consistent compared to when the index was created, or the index
is rebuild on the fly. That should fix the issue.

-- Jaap

**Comment by jaap-karssenberg** [comment] 2019-02-11 12:31
Closign as I assume it to be fixed in 0.70. If similar is seen for 0.70 or newer, please re-open.

**Closed by jaap-karssenberg** 2019-02-11 12:31 UTC

**Comment by Bujiraso** [comment] 2019-02-22 21:39
(So far, looks good, btw)
