### ISSUE TITLE
Unresponsive pages containing code blocks without scrolling or resizing window

### ISSUE THREAD

**Issue by digilur** [zim-desktop-wiki/zim-desktop-wiki#296] opened 2018-01-22 00:58 UTC
I'm experiencing the same issue exactly as described in #160. Also running Mint 18.2, but with Zim 0.68-rc1. All pages that have a code block are unresponsive until I either scroll (if the page is long enough to do this) or resize the window. Actually, I picked up the resize the window tip from reading #160. Prior to that trick, I have been editing my page sources manually to put in enough blank lines to allow the page to scroll (if I forgot to do that when editing them initially).

Issue becomes most apparent when you have pages that aren't long enough to scroll which contain code blocks, since without the knowledge to resize the window, it appears as if the page is completely unresponsive. I've attached example source file, but you should be able to recreate by putting a code block on any page that isn't long enough to scroll.
[Compilers.txt](https://github.com/jaap-karssenberg/zim-desktop-wiki/files/1650406/Compilers.txt)

**Comment by Self-Perfection** [comment] 2018-01-26 18:34
Looks like you suffer from [this long-standing bug](https://bugs.launchpad.net/zim/+bug/1460386). There is a good chance that after porting to GTK+ 3 (#151) this bug would finally disappear. For now try to disable line numbers display for code snippets, this prevents bug from occurring on my system.

**Comment by digilur** [comment] 2018-01-27 05:33
Yes, I'd say that's the bug I'm suffering from. Can confirm that disabling line numbers in the source (linenumbers="False") prevents the bug from occurring on my system as well.

**Comment by edomato** [comment] 2018-05-21 02:09
Hi, I find this bug today and after reading about different issues and diagnostic, it seems that the problem is when rendering the sourceview widget.

As reported by others, if the content on the page is not large enough so the scroll bars appears for example, the page seems to freeze.

But I also find that with a small page with a code blocks that freeze when you open it, if resume rendering the sourceview if you, for example, change the size of the window.

I hope Gtk+3 version is released soon as it seems that the problem is solved there :smile: 

Thanks for all

**Comment by anophelesgreyhoe** [comment] 2018-06-14 19:12
I am afflicted by this same issue on my Debian Buster computer at home:
- zim 0.68-1
- python-gtksourceview2  2.10.1-2build1
- libgtksourceview2.0-0 2.10.5-3

However, I never experience it on my Ubuntu 16.04 workstation at work:
- zim 0.65-2
- python-gtksourceview2 2.10.1-2build1
- libgtksourceview2.0-0 2.10.5-2ubuntu2

**Comment by jaap-karssenberg** [comment] 2019-01-27 11:30
CLosing because I believe this to be fixed in the upcoming zim 0.70 release.

Please open a new ticket if similar behavior occurs in zim 0.70 or newer.

**Closed by jaap-karssenberg** 2019-01-27 11:30 UTC
