### ISSUE TITLE
drag & drop pages doesn't work 0.74.2 Win 10

### ISSUE THREAD

**Issue by osman1963** [zim-desktop-wiki/zim-desktop-wiki#1778] opened 2021-12-04 22:13 UTC
**Describe the bug**
When trying to drag & drop a page to make it subpage under a different parent for example it doesn't work. Clicking even doesn't have any effect. Moving it using the menu works fine though. 

**Environment (please complete the following information):**
 - Version0.74.2
 - OS: Windows 10
 
Thanks in advance and keep it up :)

**Comment by dehesselle** [comment] 2021-12-05 22:37
Possibly a duplicate of https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1699. Check if you have drag & drop enabled @osman1963

**Comment by osman1963** [comment] 2021-12-05 23:57
That was the problem indeed. Enabling it in Page Index plug-in solved the
problem. Thanks alot for your help

**Closed** 2021-12-05 23:58 UTC
Labels: bug, needs triage
