### ISSUE TITLE
Zim Windows 0.75 problem with "Umlaute äüöß" (mutated vowel) in German.

### ISSUE THREAD

**Issue by installat** [zim-desktop-wiki/zim-desktop-wiki#2195] opened 2022-10-14 16:53 UTC
Sorry i am not a programmer and my english is bad. But I want to report the following problem for version 0.75.0 in Windows:
If in the appendix directory is a document wich filename has "Umlaute" äöuß (mutaded vowel) the link to the file does not work. Message "the system cannot find the specified file" is displayed.

**Comment by dehesselle** [comment] 2022-10-15 00:20
This is a known issue / regression in 0.75.0 and will be fixed with the next release. You can either downgrade Zim or rename your files as possible workarounds for the time being.

Duplicate of https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/2168

**Closed as completed by dehesselle** 2022-10-15 00:20 UTC
Labels: duplicate
