### ISSUE TITLE
Zim main window does not tile/minimize with Win 10 command keys

### ISSUE THREAD

**Issue by pklausner** [zim-desktop-wiki/zim-desktop-wiki#2090] opened 2022-06-22 13:02 UTC
**Describe the bug**
Recent zim has a window frame which is styled unixy and does not behave like normal Windows any more.

**To Reproduce**
1. Click Meta-left
2. Click Meta-M
3. Compare window decoration of main window with jump or search box

**Expected behavior**
1. Window should fill left half of screen, but nothing happens
2. All windows minimize, but not the Zim window
3. Main Window has distinct Unix (Xfce?) look and feel, while jump/search box has normal Win 10 windows decoration

**Screenshots**
See differing window decoration:
<img width="374" alt="zim_windows_decoration" src="https://user-images.githubusercontent.com/224540/175033811-81ebe928-8694-468d-8b15-f07df45f1485.png">

**Environment (please complete the following information):**
 - Version 0.74.3, portable install
 - OS: Windows 10 21H2
 - Language: English

**Additional context**
 - Used to work before; definitely for version 0.64.

**Comment by introt** [comment] 2022-06-22 18:04
Hi, thanks for the report!

Sounds similar to the issues described/linked in https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/2007 - could you please confirm whether the instructions given therein solve these issues? Thanks!

**Comment by pklausner** [comment] 2022-06-22 21:27
Thanks @introt 

Indeed, the configuration change does work for Win10 as well. Apparently sneaking the buttons into Windows' title bar breaks its standard look & behaviour.

**Comment by introt** [comment] 2022-07-02 13:00
You're welcome! Gtk's client side decorations will be disabled by default on Windows in the future versions, so I'll close this as a duplicate of #2007.

**Closed by introt** 2022-07-02 13:00 UTC
Labels: bug, duplicate
