### ISSUE TITLE
crash on create new page

### ISSUE THREAD

**Issue by pedromgsanches** [zim-desktop-wiki/zim-desktop-wiki#903] opened 2019-07-30 11:18 UTC
Hi,
Have recently installed: Zim 0.69.1

Above error when creating new pages or editing existing ones:

This is zim 0.69.1
Platform: nt
Locale: pt_PT cp1252
FS encoding: mbcs
Python: (2, 7, 14, 'final', 0)
Gtk: (2, 24, 10)
Pygtk: (2, 24, 0)
No bzr version-info found

======= Traceback =======
  File "zim\gui\widgets.pyo", line 3202, in do_response
  File "zim\gui\__init__.pyo", line 2578, in do_response_ok
  File "zim\actions.pyo", line 140, in func
  File "zim\gui\__init__.pyo", line 730, in open_page
AssertionError: Could not close page

**Comment by introt** [comment] 2021-12-15 08:09
Hi! This bug is from a version earlier than 0.70 (and likely a duplicate of  #819) --> closing, please open a new issue if you're having the same problem on a later version.

**Closed by introt** 2021-12-15 08:09 UTC
