### ISSUE TITLE
Large code block narrows during scrolling in the middle

### ISSUE THREAD

**Issue by pchemguy** [zim-desktop-wiki/zim-desktop-wiki#2103] opened 2022-07-09 05:55 UTC
**Describe the bug**
I have a large code block (180 lines), which does not fit on the page. When I scroll through it and both the first and the last lines are outside of the visible frame, the code block narrows down as I scroll. Rendering is reset, when either the first or last lines become visible. Once I managed to completely collapse a code block into a verticle line.

**To Reproduce**
1. Insert a large code block (large enough to make it possible to hide both the beginning and end while in the middle.
2. Scroll back and force while staying in the middle section.
3. Observe code block getting narrower with each move.

**Expected behavior**
Nothing should happen to the code block.

**Screenshots**
![Zim](https://user-images.githubusercontent.com/39730837/178093585-1f1b2918-2496-4215-b113-501eaf667601.jpg)

**Environment (please complete the following information):**
 - Version 0.74.3
 - OS: Windows 10

**Comment by introt** [comment] 2022-07-09 10:09
Thanks for the report!

Duplicate of  #1761

**Closed by introt** 2022-07-09 10:09 UTC
Labels: bug, needs triage
