### ISSUE TITLE
Empty space in bookmarks bar area

### ISSUE THREAD

**Issue by sojusnik** [zim-desktop-wiki/zim-desktop-wiki#616] opened 2019-01-16 21:01 UTC
As you can see [here](https://i.imgur.com/xa5gvOE.png), the bookmarks bar looks out of place now.

Happens with Zim 0.70-rc1 on Ubuntu 18.10.

**Comment by jaap-karssenberg** [comment] 2019-01-18 20:13
Duplicate of #436

**Closed by jaap-karssenberg** 2019-01-18 20:13 UTC
