### ISSUE TITLE
Strange work of the spell checker

### ISSUE THREAD

**Issue by Nick222** [zim-desktop-wiki/zim-desktop-wiki#1596] opened 2021-09-19 09:19 UTC
The strange work of the spell checker: every other time - it works fine, then it underlines the allegedly incorrect words, but by right-clicking it only shows the language selection item in the mouse-menu, but does not show in it the option for replacing the incorrect word.

The package gir1.2-gtkspell3-3.0 is installed, but the spellcheck plugin settings still show an error for gtkspell.

Xubuntu 21.04
Zim 0.74.0
Language ru_RU
python3-gtkspellcheck 4.0.5-2
gir1.2-gtkspell3-3.0 3.0.10-1

**Comment by micha06de** [comment] 2021-10-05 16:04
Have you installed the (correct) dictionaries?

**Comment by Nick222** [comment] 2021-10-06 18:37
Yes
All worked very good before 0.74

**Comment by vossenjp** [comment] 2021-10-30 19:32
I'm seeing this or something similar.  For me, when I switch pages, the spell checker sometimes just stops working.  Incorrect words are not flagged, sometimes correct words are flagged.  Unchecking it in plugin prefs then re-checking it "fixes" the problem...until the next time.

**Comment by vossenjp** [comment] 2022-12-19 18:38
**tl;dr:** If Zim is very slow or if the spell checker is misbehaving, try removing `gtkspellcheck` and using `gtkspell` instead.  For Ubuntu, Mint, etc.:

* `sudo apt purge python3-enchant python3-gtkspellcheck`
* `sudo apt install gir1.2-gtkspell3-3.0 libgtkspell3-3-0`
* `sudo add-apt-repository ppa:jaap.karssenberg/zim && sudo apt update  && sudo apt install zim`

See more in https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1497#issuecomment-1358082581 or https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/2167#issuecomment-1358082355 (same details in both).

**Comment by jaap-karssenberg** [comment] 2023-01-05 13:36
For the moment consider this a duplicate of #2260

**Closed by jaap-karssenberg** 2023-01-05 13:36 UTC
Labels: bug, needs triage
