### ISSUE TITLE
Link on filename with german Umlaute äöü cannot be opened

### ISSUE THREAD

**Issue by CRZeiss** [zim-desktop-wiki/zim-desktop-wiki#2225] opened 2022-11-12 08:51 UTC
Links on files with german "Umlaute" (äöüÄÖÜ) cannot be opened.
System cannot find the file "W:\Dauerakte\Basis\Kontakte-Behörden-Steuern-PIN-SV.pdf"
There seems to be a problem with UTF-8 (in Zim-page) and ANSI (file-system)

See logfile:
DEBUG: Running ErrorDialog
DEBUG: Activate link: file:///W:/Dauerakte/Basis/Kontakte-Behörden-Steuern-PIN-SV.docx
DEBUG: open_file(W:\Dauerakte\Basis\Kontakte-Behörden-Steuern-PIN-SV.docx, None)
INFO: Opening with os.startfile: file:///W:/Dauerakte/Basis/Kontakte-Beh%C3%B6rden-Steuern-PIN-SV.docx
DEBUG: Exception during activate-link(('file:///W:/Dauerakte/Basis/Kontakte-Behörden-Steuern-PIN-SV.docx', {'new_window': False}))

Environment: Windows 11, German
Zim 0.75.0

**Comment by dehesselle** [comment] 2022-11-12 14:31
Please update to 0.75.1

Duplicate of #2195

**Closed as completed by dehesselle** 2022-11-12 14:31 UTC
Labels: duplicate
