### ISSUE TITLE
Suppress automatic creation of Pages

### ISSUE THREAD

**Issue by joe-pirat** [zim-desktop-wiki/zim-desktop-wiki#2259] opened 2022-12-19 16:42 UTC
**Zim automatic creation of pages and they cannot be deleted**

The fact that they cannot be deleted just makes the problem more annoying. But I just want to turn off this highly undesirable feature. 
Everyone I know who uses Zim is annoyed by it, and it's a strange aspect of open source software that I keep seeing, that developers like features but 99% of users don't, but they stay in the software. 
I would be willing to change a certain line of code after each update or something like that but how can I just stop that please? 
the problem has existed for about 4 years and on various computers and various versions of zim.  
Why every mail address and every URL does not become a new - unwanted - sub page is not clear to me - so I cannot describe the reproduction exactly but I think the problem is known.
i would like to stay with zim and am looking forward to a reply

**Comment by dehesselle** [comment] 2022-12-19 17:53
I don't follow. Since about 4 years
- you are doing "something" with URLs and/or eMail addresses
- which results in a new page being created
- which you do not want
- but you also cannot delete the page?

**Comment by introt** [comment] 2022-12-19 18:30
Have you tried turning off every "Automatically turn X into links" setting under Preferences > Editing?

If you're unable to describe the steps to reproduce, please send screenshots and/or wikitext examples and include the version of Zim you're using - otherwise we're unable to help you with your problem.

I'm labeling this as a "Candidate for removal" because this belongs in the Discussions. From the current description this is likely a duplicate of #499, #80 or  #1107 - if turning off the aforementioned settings doesn't help, the regex to modify can be found therein. Apparently "the situation is much better" on Zim 0.72+

**Comment by joe-pirat** [comment] 2022-12-19 20:52
thx for replay 
I have now turning off every "Automatically turn ... 
I will check it helps  or not. 

but you also cannot delete the page?  
yes this pages have a grey name and are not posible zu delete.  
I can move them in to a trash folder. 
I understand that discussion and bug report are somewhat mixed up here - sorry for that 


![Screenshot from 2022-12-19 21-48-12](https://user-images.githubusercontent.com/37078939/208521026-8d0b0f74-cdf2-4d25-82a0-a3e954c9d912.png)

**Comment by introt** [comment] 2022-12-21 17:44
The pages whose names appear in gray italics are "vivificated"; they represent paths that have been linked to, but for which pages do not exist. There are a few ways to get rid of them, off the top of my head:

1. With the BackLinks plugin enabled, open the page, open its BackLinks, and delete the links to it.
2. Create the page by writing something into it, then right-click its name in the index and choose Delete Page, making sure the "Remove links to page:name" box is ticked before clicking OK

On Zim 0.75.1 I do not need to create the page for number 2 to work, so I'm assuming you're running an older version. Hope this solves your issue.

**Comment by joe-pirat** [comment] 2022-12-21 17:54
I run  zim 0.75.1 
its nice that I have a way to delete but my way to move in to a trash folder woks also.  Way I cant disable a feature what I dont need is my main question. This would be preventing the emergence of such unwanted pages

**Comment by introt** [comment] 2022-12-21 18:28
I haven't worked on the code, but my best understanding is that _not_ having them would be a feature - the Page Index plugin (which itself can be disabled) simply exposes the internal link index, which includes both links to existing and non-existing pages, as a Gtk TreeView. Stylizing tree view nodes is simple, but our toolkit doesn't support hiding nodes by other means than collapsing their parent.

**Comment by introt** [comment] 2023-01-07 09:46
Duplicate of #834

**Closed as not planned by introt** 2023-01-07 09:46 UTC
Labels: duplicate
