### ISSUE TITLE
Possibility to add inline math

### ISSUE THREAD

**Issue by douglasrizzo** [zim-desktop-wiki/zim-desktop-wiki#527] opened 2018-09-10 02:27 UTC
Hey everyone, I wonder if it's possible to add inline math symbols and equations, just like when we use `\(x^2\)` in LaTeX. I know about the Insert Equation plugin, but it uses _dvipng_ to create an image that is not centralized vertically with the line and its default formatting is for _displayed math_ (the equivalent of `$$ x^2 $$` or `\[x^2\]`) and not _inline math_.

**Comment by jaap-karssenberg** [comment] 2019-02-11 12:35
Afraid this is won't fix. We do not render math directly but always rely on `latex` + `dvipng` to  render math. 

Only very simple examples can be rendered directly. E.g. the x^2 can be written in zim using the superscript formatting for the "2" -- or type "x^{2}" and reload the page. Also have a look at the "insert symbol" plugin for using math symbols in text.

**Closed by jaap-karssenberg** 2019-02-11 12:35 UTC

**Comment by rburkey2005** [comment] 2021-11-30 14:25
@jaap-karssenberg I understand why this can't be 100% fixed.

But I don't understand why an adjustment can't be made that would fix 90% of the annoyance.  It's the vertical alignment that's the annoying part.  At least for me (Zim 0.72, Linux Mint 20.1) the bottom of the equation aligns vertically with the centerline of the text as in the following screenshot:  

![now](https://user-images.githubusercontent.com/11841400/144063296-f36b1a23-e31a-40b8-987c-09e73ae2abf4.png)

To me, that makes the inlining unusable. Simply vertically aligning the middle of the generated png to the centerline of the text would take it (at least for for me) to being perfectly fine.  Even if the alignment weren't as perfect as in this sample image I photoshopped:

![improved](https://user-images.githubusercontent.com/11841400/144063452-8caa4a45-991f-45cb-bee9-154c4e1f9d36.png)

I wouldn't complain about this if Zim weren't so wonderful in almost every other respect.

**Comment by rburkey2005** [comment] 2021-11-30 19:13
I took a look at the Zim source code to get an idea what Gtk widget is involved, but the brief amount of time I had didn't allow me to work that out.  In spite of that, I do wonder:  Perhaps a bug report to could be sent upstream to the Gtk developers asking for an option to be added to that specific widget to allow a better vertical alignment?  It seems as though it would be a useful thing to have in general, and not just for Zim.

**Comment by dehesselle** [comment] 2021-11-30 19:41
Feel free to do talk to GTK @rburkey2005 , but, honestly, don't bother. This is "works as designed" from their point of view and with GTK3 being in maintenance mode, they won't accept new "features" (as in behavioral changes).

**Comment by rburkey2005** [comment] 2021-11-30 19:50
@dehesselle Do you happen to know off the top of your head which widget it is?  It would save me a little time.

**Comment by dehesselle** [comment] 2021-11-30 20:14
It's TextView. See https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/master/zim/gui/pageview/__init__.py#L3997

**Comment by rburkey2005** [comment] 2021-11-30 21:05
Thanks!  I expect you're probably right, but it won't hurt to look.

**Comment by rburkey2005** [comment] 2021-12-01 01:00
So ... admittedly I haven't gotten too far into direct experimentation with Gtk TextView yet, but I have been experimenting a little with fooling Zim into vertically aligning inline equations a bit better than it does now.  Here's another screenshot from Zim on my computer. It's directly from Zim, and _not_ photoshopped afterward by me:

![VirtualBox_Linux Mint 20](https://user-images.githubusercontent.com/11841400/144151816-eb9fa144-1925-4f45-bba8-fec2a15bec3e.png)

Method 2 produces an obviously-better result than Method 1 (the method used now).  In fact, the only thing that keeps it from being aligned pretty well is the descender on the _y_ character.

Method 3 is obviously better than Method 2 (and only does some processing on the PNG image generated by dvips that can be fully automated).

Admittedly, even Method 3 isn't perfect, but at least to me, it would be pretty usable.

**Comment by jaap-karssenberg** [comment] 2021-12-01 10:12
I can get rid of the border and shave a few pixels off the border. THis
will effectively give you the same look as "method 2". Maybe to push it
further, you could look into style settings for latex / dvi2png that make
the equation fit better inline.

**Comment by rburkey2005** [comment] 2021-12-01 12:19
Maybe there could be a preference setting for keeping or removing the border.  I can't speak for everyone, but in my own case (writing notes about mathematical topics) I'd expect to mimic the effect seen in math books and papers, wherein the math blends in as completely with the surrounding text as possible ... i.e., no borders.

Similarly, I'd expect the font size to be the same for the math as for the surrounding text, rather than bigger for the math (as it is right now).  I hadn't really noticed before that the Zim preferences have a font setting in them.  Just increasing the font size a little in the Zim preferences produces roughly the same effect as rescaling the equation PNGs did, making the rescaling unnecesary.

So maybe just getting rid of the borders (possibly via a preference) and mentioning these factoids in the documentation of the "insert equations" plugin is good enough.  

I'll look into latex/dvi2png settings, though.  Thanks!

**Comment by rburkey2005** [comment] 2021-12-01 13:04
It appears to me that the equation font size is controlled by the equationeditor plugin template.  The default is "12pt" in the template whereas the default for Zim itself is 10, so I guess that's why there's normally a size mismatch.

Apparently, the equationeditor template only allows values of 10, 11, and 12, because those are the only choices allowed by the underlying amsmath tex package.

Zim provides a way for the user to edit that template, although the changes don't seem to take effect until Zim is exited and restarted.

It might be a good idea for Zim to just automatically alter the size in the equationeditor template to match the overall font size selected in the preferences (limiting the equationeditor settings to the range 10, 11, 12, of course).  Failing that, it seems like it's something that should be explained in the equation editor documentation.

**Comment by rburkey2005** [comment] 2021-12-01 13:16
Another factoid conceivably of interest that might be documented for the equation editor plugin is that the Zim font that most-closely matches the equation font seems to be "C059 Roman".  Though that's just on my Linux Mint computer, and I admit that I don't understand if Zim has a different font selection on different platforms.

**Comment by dehesselle** [comment] 2021-12-01 13:23
In a gtkmm demo program for TextView (`gtkmm-3.24.4/demos/gtk-demo/example_textview.cc`) I found the following code:

```c
 refTag = refBuffer->create_tag("superscript");
 refTag->property_rise() = 10 * Pango::SCALE;    /* 10 pixels */
 refTag->property_size() = 8 * Pango::SCALE;     /* 8 points */
  
 refTag = refBuffer->create_tag("subscript");
 refTag->property_rise() = -10 * Pango::SCALE;   /* 10 pixels */
 refTag->property_size() = 8 * Pango::SCALE;      /* 8 points */
```

This is how they realize subscript/superscript. If this API is accessible from Python, maybe this can be leveraged?

**Comment by rburkey2005** [comment] 2021-12-01 13:31
You're suggesting that maybe it could be used to lower the latex-generated PNG image?  Sounds promising.

If it works, there's still a problem, in that math images with descenders (such as "_y_") would have to be lowered by a different amount than those without descenders (such as "_x_").  So there might have to be some kind of analysis of the original latex involved to find out if there were likely to be descenders.  I wonder if the generated PNG has that info stored in its metadata?

**Comment by jaap-karssenberg** [comment] 2021-12-01 13:41
Let's not over design. Don't expect zim rendering to be textbook perfect.

But I think what is achievable:
* remove border (or make it optional)
* use property to match font size in the template to font size in the
textview
* lowering the image might work, but is probably only correct 50% of the
time, so I guess we better leave that

-- Jaap

**Comment by rburkey2005** [comment] 2021-12-01 13:46
Not so fast :smile:!

dvipng has a command-line option ("--depth*"), not used by the equation-editor plug-in now, that "reports the number of pixels from the bottom of the image to the baseline of the image. This can be used for vertical positioning of the image in, e.g., web documents".

**Comment by jaap-karssenberg** [comment] 2021-12-03 18:07
Made some improvements in commit e920702a99977521d6c87043b44b6fdc8a266007. Let's close the discussion here, as it goes off topic compared with the parent issue. If someone wants to pick up further improvements, please open a new ticket or pull request.

Kind regards,

Jaap

**Comment by rburkey2005** [comment] 2021-12-03 19:18
Yes, I'd definitely call it an improvement.  Thanks!
