### ISSUE TITLE
History not keeping last page when quit (vs close) and called in background

### ISSUE THREAD

**Issue by reagle** [zim-desktop-wiki/zim-desktop-wiki#871] opened 2019-06-07 13:34 UTC
Zim 0.71.1 from github on MacOS Mojave.

I've noticed that after quitting zim on page N in the history and re-opening, the page is set at the *previous* page in the history N-1. Therefore, I went to `~/.cache/zim` and watched `state.conf` and noticed that as I browse, `list`, `recent`, and `current` are only updated with the current page upon leaving it.

**Comment by reagle** [comment] 2019-06-07 13:51
Here's a capture where you can see the history is lagging in state.conf relative to actual navigation. I noticed this problem because when I close and re-open zim, it only restores the state to the next-to-last page I was on, not the last one.

![](https://reagle.org/joseph/tmp/zim-history.gif]

**Comment by reagle** [comment] 2019-06-07 14:09
In `history.py` is current offset against `list` or `recent`?

**Comment by reagle** [comment] 2019-06-07 14:36
Here's a [link to a screen capture](https://reagle.org/joseph/tmp/zim-history.gif). The problem only seems to occur when I call it from a bash script that also asks zim to go into the background. You can see even though I navigated `/Home/System/Android` the last page was never recorded in `state.conf` when I exited.

**Comment by reagle** [comment] 2019-06-07 14:43
Here's the bash script. I send zim to the background because otherwise the script doesn't exit. (For some reason, the osascript commands prevent that... I use them because zim won't become the active window on MacOS otherwise...)

```
#!/bin/bash

/usr/local/bin/python3 $HOME/bin/zim-desktop-wiki/zim.py $HOME/joseph/plan/zim/ --standalone --geometry 900x1000-0-0 &

# run every half second since I don't know how long zim will take to appear
sleep 0.5
osascript -e 'tell application "Python" to activate windows where name contains "Zim"'
sleep 0.5
osascript -e 'tell application "Python" to activate windows where name contains "Zim"'
sleep 0.5
osascript -e 'tell application "Python" to activate windows where name contains "Zim"'
exit
```

**Comment by reagle** [comment] 2019-06-07 18:21
After more experimentation, the problem seems to arise when I **quit** zim running as a background process (`&`) from a shell script. If I close, instead, the last page is saved correctly to `state.conf`.

So, my workaround for this bug is to either: close with `super-w` or remove `&` background from shell script, which then means I can't make the program foreground.

**Comment by svenn71** [comment] 2019-06-13 06:32
On windows I have to quit zim by File-Quit to get the current state recorded for next session. If I let zim go down by a shutdown, some previous state of the history is used by next start. Quite annoying when I use zim as a work journal and want the last recorded day work be the initial page I see next time I open zim

**Comment by introt** [comment] 2021-12-15 09:02
Can reproduce this behavior with 0.74 on Linux by starting from the terminal (also in foreground) and pressing `Ctrl` + `C`:

```
^CERROR: KeyboardInterrupt
```

Closing from UI:

```
DEBUG: Action: close (delete-event)
DEBUG: Remove window: MainWindow
DEBUG: Last toplevel destroyed, quit
```

`pkill zim` (also retains state):
```
INFO: Got SIGTERM, quit
DEBUG: Remove window: MainWindow
DEBUG: Last toplevel destroyed, quit
```

Seems there are signals and/or interrupts that need handling.

**Comment by jaap-karssenberg** [comment] 2022-03-06 18:39
This issue can be considered a duplicate of #674. Fix is not in catching all signals and do work on the signal, rather just write the the history to disk when page is switched.

Also there is a plan to use the index to store the history, instead of the "uistate" file. This would also fix the issue if index is committed immediately to file.

**Comment by introt** [comment] 2022-03-10 07:57
Closing as a duplicate of #674

**Closed by introt** 2022-03-10 07:57 UTC
Labels: bug, duplicate
