### ISSUE TITLE
website link as a new page and can't be deleted

### ISSUE THREAD

**Issue by kashabech** [zim-desktop-wiki/zim-desktop-wiki#1324] opened 2020-11-17 11:39 UTC
Sometimes there are some links for websites that appear as shadowed pages and can't be deleted.
![zim](https://user-images.githubusercontent.com/9605092/99385820-a09b6780-2925-11eb-890b-9f652d96fe54.PNG)

**Comment by jaap-karssenberg** [comment] 2020-11-17 14:29
Try starting the links with "http://"

**Comment by kashabech** [comment] 2020-11-17 22:51
I did it, but I thought as it is a bug you may need to know about it.
Thank you very much.

**Comment by jaap-karssenberg** [comment] 2020-11-20 10:58
SOrry but this is not a bug, page names can have a "." in them, so you need to use proper URLs for external links

**Comment by jaap-karssenberg** [comment] 2020-12-30 19:35
Discussion on mailing list on this issue clarified that this also happens when "www." sequences are not explicitly marked as links. Regression due to new link matching regex. 

Sorry for not understanding the issue initially

**Closed** 2020-12-30 19:39 UTC
Labels: regression

**Comment by jaap-karssenberg** [comment] 2020-12-30 19:41
@rhertzog - thanks for clarifying - patch should arrive shortly
