### ISSUE TITLE
Disable automatic page generation when putting a colon inside a word

### ISSUE THREAD

**Issue by codedust** [zim-desktop-wiki/zim-desktop-wiki#1232] opened 2020-08-18 15:54 UTC
I couldn't find the option to disable the automatic creation of links to new pages when entering a colon inside words. This sometimes also happens when entering a URL (although I couldn't reproduce it yet).

![image](https://user-images.githubusercontent.com/7175914/90536026-d0e33680-e17b-11ea-98fc-886e2ad0bf73.png)

![image](https://user-images.githubusercontent.com/7175914/90535999-c6c13800-e17b-11ea-98b9-5698a9dbe0eb.png)

![image](https://user-images.githubusercontent.com/7175914/90535622-68945500-e17b-11ea-9321-614215edc6b1.png)

EDIT: (I'm using Zim Wiki 0.73.2)

(Also, a bit of-topic, but it would be great to see a free founding plattform like Liberapay and OpenCollective included in the donation options. See https://f-droid.org/en/2020/07/20/donations-with-free-software.html)

**Comment by codedust** [comment] 2020-08-24 08:50
I just found what caused the issue. A link in another page linked to "<https://www.governikus.de/osci-bibliothek/#osci-download" (including the `<`) created the page that could not be removed.

**Comment by sanjarcode** [comment] 2020-11-11 04:27
Duplicate of #1107 
Please search issues first

**Closed** 2021-12-15 17:04 UTC
