### ISSUE TITLE
"Zoom in" causes crash

### ISSUE THREAD

**Issue by jtietema** [zim-desktop-wiki/zim-desktop-wiki#2513] opened 2023-11-14 14:01 UTC
**Describe the bug**
I accidentally reset my zoom (Ctrl+0) and when trying to zoom again (both shortcut and view menu item) the app crashes with a segfault.
```
[1]    87452 segmentation fault (core dumped)  ./zim.py
```

**To Reproduce**
1. Go to 'view menu'
2. Click on 'Zoom In'
3. Crash :boom:

**Expected behavior**
My font gets bigger

**Environment (please complete the following information):**
 - Version 0.75.2 (both source from this repo and the packaged version from Fedora)
 - OS: Fedora linux 38
 - Language: english

**Additional context**
Zim -D output:
```
DEBUG: Loading config from: <ConfigFile: /home/jeroen/.config/zim/preferences.conf>
DEBUG: New extendable: <zim.plugins.InsertedObjectTypeMap object at 0x7f4eb3beb990>
DEBUG: Loading plugin: pageindex
DEBUG: Loading plugin: pathbar
DEBUG: Loading plugin: insertsymbol
DEBUG: Loading plugin: printtobrowser
DEBUG: Loading plugin: tasklist
DEBUG: Loading plugin: journal
DEBUG: Loading plugin: distractionfree
DEBUG: Loading plugin: backlinkpane
DEBUG: Loading plugin: sourceview
DEBUG: Load extension: <class 'zim.plugins.sourceview.SourceViewObjectType'>
DEBUG: register_object: "code"
DEBUG: Loading plugin: linkmap
INFO: This is zim 0.75.2
DEBUG: Python version is sys.version_info(major=3, minor=11, micro=6, releaselevel='final', serial=0)
DEBUG: Platform is posix
DEBUG: Running from a source dir: /home/jeroen/Develop/zim-desktop-wiki
DEBUG: Set XDG_DATA_HOME to /home/jeroen/.local/share
DEBUG: Set XDG_DATA_DIRS to [<LocalFolder: /home/jeroen/.local/share/flatpak/exports/share>, <LocalFolder: /var/lib/flatpak/exports/share>, <LocalFolder: /usr/local/share>, <LocalFolder: /usr/share>]
DEBUG: Set XDG_CONFIG_HOME to /home/jeroen/.config
DEBUG: Set XDG_CONFIG_DIRS to [<LocalFolder: /etc/xdg>]
DEBUG: Set XDG_CACHE_HOME to /home/jeroen/.cache
DEBUG: Connecting to /run/user/1000/zim-0.75.2-84875b2e
DEBUG: Got error in dispatch: Connection failed
DEBUG: Starting primary process
DEBUG: Start listening on: /run/user/1000/zim-0.75.2-84875b2e
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f4ea3cc7ed0>
DEBUG: Loading config from: /home/jeroen/Documents/Notes/Personal/notebook.zim
DEBUG: Loading config from: /home/jeroen/Documents/Notes/DNA/notebook.zim
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f4ea3789c90>
DEBUG: Loading config from: /home/jeroen/Documents/Notes/Personal/notebook.zim
DEBUG: Loading config from: /home/jeroen/Documents/Notes/DNA/notebook.zim
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7f4ea3bf9e50>
DEBUG: Loading config from: /home/jeroen/Documents/Notes/Personal/notebook.zim
DEBUG: Loading config from: /home/jeroen/Documents/Notes/DNA/notebook.zim
DEBUG: Opening dialog "Open Notebook"
DEBUG: Opening dialog "Open Notebook"
DEBUG: Dialog response OK
DEBUG: Closed dialog "Open Notebook"
DEBUG: Loading config from: /home/jeroen/Documents/Notes/DNA/notebook.zim
DEBUG: Connecting to database file: /home/jeroen/.cache/zim/notebook-home_jeroen_Documents_Notes_DNA/index.db
DEBUG: Loading config from: /home/jeroen/.cache/zim/notebook-home_jeroen_Documents_Notes_DNA/state.conf
DEBUG: New extendable: <Notebook: DNA.inc>
DEBUG: Load extension: <class 'zim.plugins.journal.JournalNotebookExtension'>
DEBUG: Load extension: <class 'zim.plugins.tasklist.TaskListNotebookExtension'>
DEBUG: Loading config from: <ConfigFile: /home/jeroen/.config/zim/style.conf>
DEBUG: Autosave interval: 15 - use threads: True
INFO: Page changed on disk: Journal:2023:Week 46
INFO: Open page: Journal:2023:Week 46 (Journal:2023:Week 46)
DEBUG: New extendable: <notebookview.NotebookView object at 0x7f4ea38fba40 (zim+gui+notebookview+NotebookView at 0x562f063343e0)>
DEBUG: Load extension: <class 'zim.plugins.backlinkpane.BackLinksPanePageViewExtension'>
DEBUG: Action: toggle_panes(False)
DEBUG: Action: toggle_panes(True)
DEBUG: Load extension: <class 'zim.plugins.insertsymbol.InsertSymbolPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.journal.JournalNotebookViewExtension'>
DEBUG: According to babel first day of week is 0
DEBUG: Load extension: <class 'zim.plugins.linkmap.LinkMapPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.pageindex.PageIndexNotebookViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.printtobrowser.PrintToBrowserPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.tasklist.TaskListNotebookViewExtension'>
WARNING: Invalid config value for task_status: "[0]"
DEBUG: New extendable: <mainwindow.MainWindow object at 0x7f4ea3cd66c0 (zim+gui+mainwindow+MainWindow at 0x562f0639e160)>
DEBUG: Load extension: <class 'zim.plugins.distractionfree.DistractionFreeMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.pathbar.PathBarMainWindowExtension'>
DEBUG: Accelmap: /home/jeroen/.config/zim/accelmap
DEBUG: Add window: MainWindow
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: Action: zoom_in
DEBUG: Switching to custom font implicitly because of zoom action
[1]    87706 segmentation fault (core dumped)  ./zim.py -D
```

**Comment by introt** [comment] 2023-11-19 16:43
Duplicate of #2421

**Closed as not planned by introt** 2023-11-19 16:43 UTC
Labels: bug, needs triage
