### ISSUE TITLE
Save GUI state more frequently

### ISSUE THREAD

**Issue by martinkoutecky** [zim-desktop-wiki/zim-desktop-wiki#493] opened 2018-07-17 19:04 UTC
When Zim is not closed properly (e.g. due to system crash) it restores the session from when it was last *properly* closed. By session I mean active page, pathbar, bookmarks. This is undesirable. Expected behavior would be autosaving the session similarly to autosaving the content. (Perhaps there is a hook which is called upen closing Zim which could be called during each autosave?)

Can be reproduced e.g. by opening a few pages to change the pathbar, or adding pages into bookmark. Observe difference between the results of "killall zim" (session is preserved on next start) and "killall -9 zim" (session is not preserved).

Version: Zim 0.68
Distro: Sabayon Linux
Happy to provide any other info.

**Comment by mikepyne** [comment] 2018-10-16 08:46
I see something similar in Windows version (0.68). The session is preserved for a normal exit, but cleared when killed via task manager.

After a normal exit, the window size is preserved, along with entries in the bookmark bar, the state of the index (collapsed, expanded), and the active page. This isn't the case after a hard exit.

**Comment by jaap-karssenberg** [comment] 2019-02-08 11:49
Need to have a look at places where the state files are edited and make sure they always call "write" immediatly

**Comment by vossenjp** [comment] 2019-04-06 20:57
I agree.  I'd say this "feels" even worse with 0.70 but that may be because 0.70 is crashing for me a lot because of #766.  0.70 is also not remembers my place when switching between pages *at all* which is a big problem (#770), but it's not clear if that's related to this.

**Comment by jaap-karssenberg** [comment] 2021-12-13 12:34
Consider this a duplicate of #674

**Closed by jaap-karssenberg** 2021-12-13 12:34 UTC
Labels: enhancement
