### ISSUE TITLE
No spelling suggestions

### ISSUE THREAD

**Issue by reagle** [zim-desktop-wiki/zim-desktop-wiki#2043] opened 2022-05-11 17:04 UTC
I'm using 0.74.3 (120) from homebrew on macOS 12.3.1 21E258 arm64. 

Spell checking correctly identifies misspellings, but cannot suggest the correct spelling; the bank is always empty.

<img width="643" alt="Screen Shot 2022-05-11 at 13 03 10" src="https://user-images.githubusercontent.com/596814/167906694-8eaf5c9e-36df-495a-aeb7-8464165fa322.png">

**Comment by introt** [comment] 2022-05-14 07:36
Related:  #1596

**Comment by introt** [comment] 2022-05-14 07:38
Keeping in mind that we don't officially support installing via Homebrew, do the suggestions show up with the official package?

**Comment by reagle** [comment] 2022-05-14 18:55
My apologies, this is with "0.74.3 (120)" from [the official download site](https://gitlab.com/dehesselle/zim_macos/-/releases).

@introt, could you do me a favor and see what the behavior with the words "oppurtunity" and "opportunito" are? The first offers no suggestion but the second does, though both are underlined as mispelled.

**Comment by dehesselle** [comment] 2022-05-14 19:57
Do you have the correct language selected for spell checking? (second item in the context menu of your screenshot)

**Comment by reagle** [comment] 2022-05-16 12:41
Weird, my language was set to Dutch/Flemish. I don't know why that language has the odd "oppurtunity" vs "opportunito" difference, but setting it to English solves my issue. Thank you @introt and @dehesselle .

**Comment by dehesselle** [comment] 2022-05-16 12:47
If it cannot detect the language, it will set Dutch as default.

I have changed the way how I'm setting the locale based on OS language for the next release.

**Comment by reagle** [comment] 2022-05-16 12:51
Actually, after quitting Zim and returning, my language is no longer set. Also, I noted that my `preferences.conf` and `notebook.zim` read 

	[SpellPlugin]
	language=

But I'm not sure why....

**Comment by dehesselle** [comment] 2022-05-16 12:56
Can you test how this development version behaves?
https://gitlab.com/dehesselle/zim_macos/-/jobs/2457197934/artifacts/raw/Zim_arm64.dmg

**Comment by reagle** [comment] 2022-05-16 12:59
Using older version still: in a text editor, I can set `language=en_US`, but any change I make in the Zim GUI is not retained in the `notebook.zim`.

**Comment by introt** [comment] 2022-05-16 16:57
> "oppurtunity" vs "opportunito"

upstream issue, feel free to ask over at [koehlma](https://github.com/koehlma) /
[pygtkspellcheck](https://github.com/koehlma/pygtkspellcheck)

**Comment by reagle** [comment] 2022-05-16 17:34
Changing the language does seem to have an effect with respect to the suggestions given, but shouldn't obvious French words, including *baleine*, *chaleur*, and *empêchement* not be highlighted as mispelled?

**Comment by introt** [comment] 2022-05-21 06:53
Since spelling suggestions are showing up and there's another ticket open for being unable to set the language, I'm going to close this one.

I'm not one to comment on the obviousness of French words, but since we're only checking against a single language's dictionary, this is intended behavior; you may either start a feature request for multi-language spell checking etc over at [discussions](https://github.com/zim-desktop-wiki/zim-desktop-wiki/discussions), or ask about it [upstream](https://github.com/koehlma/pygtkspellcheck).

**Closed by introt** 2022-05-21 06:53 UTC
Labels: bug, needs info
