### ISSUE TITLE
Can't copy link of image with relative path on Windows

### ISSUE THREAD

**Issue by tehkonst** [zim-desktop-wiki/zim-desktop-wiki#382] opened 2018-03-13 16:07 UTC
There's the problem with copying images with relatives paths. On Windows I can't even edit this path. When I try to do edit properties, the program changes the path back.

Here, I created a gif to demonstrate the issue:
![zim_relative_paths_issue](https://user-images.githubusercontent.com/2618162/37598867-7b513f22-2b94-11e8-8f29-f31fa0044e0e.gif)

**Comment by genodeftest** [comment] 2018-03-18 13:09
The link you've sent is dead. You may want to upload the file directly into github instead of posting it on a 3rd party server.

**Comment by tehkonst** [comment] 2018-03-19 13:43
I updated.

**Comment by jaap-karssenberg** [comment] 2019-01-31 20:05
Duplicate of #45

**Closed by jaap-karssenberg** 2019-01-31 20:05 UTC
