### ISSUE TITLE
Index tree drag and drop reordering doesn't work

### ISSUE THREAD

**Issue by alk0** [zim-desktop-wiki/zim-desktop-wiki#722] opened 2019-03-28 22:55 UTC
Linux Mint 19.1 Cinnamon, zim 0.70~ubuntu18.04.1 from ppa:jaap.karssenberg/zim

Index tree drag and drop reordering doesn't work - nodes can be selected and dragged, but dropping them does no effect.

**Comment by jaap-karssenberg** [comment] 2019-04-01 12:08
Duplicate of #390

**Closed by jaap-karssenberg** 2019-04-01 12:08 UTC
