### ISSUE TITLE
Attachment Browser: bad element tiling with scrollbars

### ISSUE THREAD

**Issue by EvgenyD** [zim-desktop-wiki/zim-desktop-wiki#1388] opened 2021-02-02 17:22 UTC
it is not a critical issue, but a really annoying unusual behavior.
Win10, version 0.73.4
When attachment manager has enough space to show all the elements - everything is just perfect:
![image](https://user-images.githubusercontent.com/7352805/106637033-954df480-6582-11eb-941f-fe76736e9e93.png)

But if I put one more attachment, both vertical and horizontal scrollbar appear and the new item (highlighted on the screenshot below) is added from the right side. Additionally an empty line appears from below:
![image](https://user-images.githubusercontent.com/7352805/106637563-258c3980-6583-11eb-993c-20ca07413db0.png)

I assume that the new extra icon should be placed from below in that empty line, and the horizontal scrollar should not appear at all.

**Comment by jaap-karssenberg** [comment] 2021-02-03 10:56
Yes this is a known issue that is probably due to a bug upstream in the Gtk
library. Haven't found a work around yet :(

Op di 2 feb. 2021 18:23 schreef EvgenyD <notifications@github.com>:

**Comment by introt** [comment] 2021-12-15 17:45
Duplicate of #389

**Closed by introt** 2021-12-15 17:45 UTC
