### ISSUE TITLE
Issue reported by the application "Looks like you found a bug"

### ISSUE THREAD

**Issue by uirejfdpsairyuoewjkfldsa** [zim-desktop-wiki/zim-desktop-wiki#714] opened 2019-03-19 17:06 UTC
I was creating a multi-level, numbered list and the numbered ceased to work after pressing "Enter". After a couple attempts to make it work (joining with the previous line and pressing "Enter" again, I was presented with the message "Looks like you found a bug", the cause seems to be described below. After acknowledging the dialog, the bug seems to have resolved itself.

This is zim 0.69
Platform: posix
Locale: en_US UTF-8
FS encoding: UTF-8
Python: (2, 7, 5, 'final', 0)
Gtk: (2, 24, 31)
Pygtk: (2, 24, 0)
No bzr version-info found

======= Traceback =======
  File "/usr/lib/python2.7/site-packages/zim/actions.py", line 157, in do_activate
    self.__get__(instance, instance.__class__)()
  File "/usr/lib/python2.7/site-packages/zim/actions.py", line 140, in func
    self.func(instance, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/zim/gui/pageview.py", line 6056, in apply_format_numbered_list
    self._apply_bullet(NUMBER_BULLET)
  File "/usr/lib/python2.7/site-packages/zim/gui/pageview.py", line 6065, in _apply_bullet
    buffer.foreach_line_in_selection(buffer.set_bullet, bullet_type)
  File "/usr/lib/python2.7/site-packages/zim/gui/pageview.py", line 1955, in foreach_line_in_selection
    func(line, *args, **kwarg)
  File "/usr/lib/python2.7/site-packages/zim/gui/pageview.py", line 1242, in set_bullet
    indent = self.get_indent(line)
  File "/usr/lib/python2.7/site-packages/zim/gui/pageview.py", line 1748, in get_indent
    assert len(tags) == 1, 'BUG: overlapping indent tags'
AssertionError: BUG: overlapping indent tags

**Comment by Osndok** [comment] 2019-03-19 23:18
If the page does not have any sensitive information on it, can you provide the page file?

**Comment by uirejfdpsairyuoewjkfldsa** [comment] 2019-03-20 12:45
Unfortunately, it does have sensitive information, plus I've modified it
extensively since.

Jim Koelkebeck
IT-PnT
<https://red.ht/sig>
100 East Davie Street
Raleigh, NC 27601
614-450-2212

**Comment by jaap-karssenberg** [comment] 2019-04-30 15:15
Dev notes:
  * Related to "arithmetic" function print statements in combination with locale
  * Change inc/arithmetic to log warnings instead of printing

**Comment by jaap-karssenberg** [comment] 2019-05-19 12:31
Duplicate of #624

**Closed by jaap-karssenberg** 2019-05-19 12:31 UTC
Labels: bug
