### ISSUE TITLE
Unable to copy-paste from LibreOffice Calc to Zim on GNOME desktop (but was possible with Unity)

### ISSUE THREAD

**Issue by barrel0luck** [zim-desktop-wiki/zim-desktop-wiki#673] opened 2019-02-14 14:03 UTC
Before Ubuntu switched to the GNOME desktop, Zim on Unity could paste tables copied from LibreOffice Calc as an image. However, in 18.04, with the GNOME desktop, this does not work anymore. Instead I'm reduced to taking screenshots of tables and then embedding them into Zim, which takes longer and is more annoying.

**Comment by jaap-karssenberg** [comment] 2019-02-14 19:00
What is your version of zim?

**Comment by barrel0luck** [comment] 2019-02-15 19:01
![screenshot from 2019-02-15 11-29-52](https://user-images.githubusercontent.com/44344748/52878241-0efd3580-3154-11e9-9e6e-04020e7235b1.png)

**Comment by barrel0luck** [comment] 2019-02-15 19:02
![screenshot-20190215185910-423x260](https://user-images.githubusercontent.com/44344748/52878323-394ef300-3154-11e9-8d16-c47ea4a0b739.png)

**Comment by barrel0luck** [comment] 2019-02-15 19:03
Sorry, I accidentally closed the issue.

**Comment by e3rd** [comment] 2019-03-11 15:28
Works for me perfectly, Zim 0.70-rc3, Ubuntu 18.10.

**Comment by barrel0luck** [comment] 2019-03-13 19:48
I'm on Ubuntu 18.04 LTS. I don't have that version of Zim. Even the flathub version is 0.69.1.
And it doesn't work on my system.

**Comment by e3rd** [comment] 2019-03-13 21:28
I am sorry for you then. :( I'm not sure there will be a patch backported to this version. You may either wait Jaap release a new version or try deploy the actual repository. It's in fact very easy: 

1. You just download the [whole repository](https://github.com/zim-desktop-wiki/zim-desktop-wiki/archive/master.zip)
2. Put the contents of the `data` folder to `/usr/share/zim/`
3. Put the contents of the `zim` folder to `/usr/lib/python3.6/`
4. Put the contents of the `zim.py` file as `/usr/bin/zim` file

(This is unofficial but that worked for me.)

**Comment by barrel0luck** [comment] 2019-03-14 18:00
Thanks, I was not even sure if someone was aware of this bug. If it's been fixed already, I can wait for the new version.

**Comment by jaap-karssenberg** [comment] 2019-03-14 19:00
Not sure this depends on the zim version. Please let us know if it works again after the 0.70 release.

**Comment by barrel0luck** [comment] 2019-03-15 21:08
Okay, I will, thanks.

**Comment by barrel0luck** [comment] 2019-05-15 14:10
Hi, so I was testing this issue again and I have an update.
I'm on Zim version 0.71 now.
I still have the issue (but read further). 
Since @e3rd commented that he did not, I decided to test if my notebook had the problem.
So I made a new one and there copy pasting worked perfectly.
However, copy pasting does not work in my previous notebook.
All I can think of is that my notebook is really really really long. It's just a single page notebook and I enter a new date as a new heading and not a separate page (I needed scrollable continuity between dates). So maybe after copy-pasting many many images in my notebook, I reached a point where this feature broke - and I thought at that time that it had something to do with updating the distro.
That being said, I'm still able to add images using Insert -> Image... in my previous notebook, but the shortcut Ctrl V does not work.
Hope this helps!

**Comment by jaap-karssenberg** [comment] 2019-05-15 14:21
Can't think immediately of a way how the length of the page would affect
the paste behavior.

However in general Zim is optimized for many small to medium pages rather
than a few very large pages.

Regards,

Jaap

Op wo 15 mei 2019 16:10 schreef barrel0luck <notifications@github.com>:

**Comment by barrel0luck** [comment] 2019-05-15 17:54
Alright! Thanks!
You can do as you see fit with this issue.

**Comment by e3rd** [comment] 2019-07-26 18:58
What's the size of the big file and of the images?  
Would you be able to re-make such a broken file with no personal traces in order to be uploaded here and tested by the community?

**Comment by barrel0luck** [comment] 2019-07-27 15:51
I tried to, but got tired and bored right away :)
I don't know how I can do what you are asking for.
My notebook has labnotes accumulated over years in it. So it's really big and has loads of images...

**Comment by e3rd** [comment] 2019-07-27 18:08
Every Zim page is stored as a `pagename.txt` file + `pagename` folder on the disk. Couldn't you check the folder and tell us what is the size of the file and size of the folder + number of files (images) in the folder? :)

**Comment by barrel0luck** [comment] 2019-07-28 21:04
Sure:
size of pagename.txt file: 681.1 kB
size of folder: 211.6 MB
number of files: 1964 files (all png images of screenshots or copy paste images from spreadsheets).

**Comment by e3rd** [comment] 2019-07-29 09:07
Thanks for the info, this may help in the future testing! :)

**Comment by jaap-karssenberg** [comment] 2021-12-13 13:46
Will close this issue unless there is a way to reproduce

**Closed** 2022-05-22 08:59 UTC
Labels: needs testing
