### ISSUE TITLE
Ctrl-navigation works in opposite direction in right-to-left text

### ISSUE THREAD

**Issue by mehdisadeghi** [zim-desktop-wiki/zim-desktop-wiki#229] opened 2017-11-14 11:57 UTC
When writing right-to-left text in Zim (Pesian, Arabic, Hebrew) the behavior of cursor word-by-word movement (by holding down Ctrl and pressing arrow keys) is wrong. This was a well known and very old bug in GTK. Any GUI based on GTKTextView and GTKSourceView was affected, such as gedit. The good news is, however, this bug is fixed, more than six months ago. Programs based on recent GTK releases work properly, including gedit.

Zim, however, still has this problem, even though it is fixed in GTK.

I looked at the source code in order to figure out how Zim uses GTK but was lost in the code. I appreciate any comments on this problem and I am ready to help fix it.

Here are some debug information:

This is zim 0.67
Platform: posix (Archlinux)
Locale: en_US UTF-8
FS encoding: UTF-8
Python: (2, 7, 14, 'final', 0)
Gtk: (2, 24, 31)
Pygtk: (2, 24, 0)
No bzr version-info found

For more information on the fixed GTK bug see: https://bugzilla.gnome.org/show_bug.cgi?id=136059

I had initially opened this bug on Launchpad: https://bugs.launchpad.net/zim/+bug/1731771

P.S. I fixed that bug with help from GNOME people.

**Comment by mehdisadeghi** [comment] 2017-11-14 19:39
Most probably the bug is within pygtk toolkit. I opened [bug report](https://bugzilla.gnome.org/show_bug.cgi?id=790341) there.

**Comment by jaap-karssenberg** [comment] 2017-12-11 16:49
The issue is that zim is still on Gtk2 - the fix you refer to is probably in Gtk3.

Either way, pygtk is no longer maintained and limitted to older versions of Gtk2. Zim is being ported to Gtk3, work in progress.

**Comment by jaap-karssenberg** [comment] 2019-01-27 11:41
Closing this one because the bug is resolved in Gtk and we are now up to date with latest Gtk version again. Please re-open if still application work remaining in zi, 0.70 or newer

**Closed by jaap-karssenberg** 2019-01-27 11:41 UTC
Labels: bug

**Comment by mehdisadeghi** [comment] 2019-01-28 09:54
@jaap-karssenberg thanks for updating the issue. Actually after discovering this bug in Zim we worked with GNOME people (which are actively developing GTK) to resolve the underlying bug which is now upstream.
