### ISSUE TITLE
not installing through brew in a mac m1

### ISSUE THREAD

**Issue by sebapizard** [zim-desktop-wiki/zim-desktop-wiki#1398] opened 2021-02-12 18:23 UTC
Hi!
I have this message while installing through brew.

Error: zim: no bottle available!
You can try to install from source with:
  brew install --build-from-source zim
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.

Can anyone help me?
Sebastián

**Comment by kevindalias** [comment] 2021-02-20 02:15
Same issue here. Attempting to build from source with `brew install --build-from-source zim` fails with the following unspecified AssertionError:
```
Last 15 lines from ~/Library/Logs/Homebrew/zim/02.python3:
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/Pango.py", line 41, in <module>
    FontDescription = override(FontDescription)
  File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError

Do not report this issue to Homebrew/brew or Homebrew/core!
```

The dependencies appear to be installed via homebrew, so I'm stuck. Any advice?

**Comment by kevindalias** [comment] 2021-02-20 02:22
This appears to be related to [issue 1383](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1383). I have Pygobject3 and Pango installed, but `from gi.repository import Gtk` fails with what appears to be the same `AssertionError`.
```
Python 3.9.1 (default, Feb  2 2021, 22:54:59) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Gtk

** (process:37532): WARNING **: 18:16:15.186: Failed to load shared library 'libpango-1.0.0.dylib' referenced by the typelib: dlopen(libpango-1.0.0.dylib, 9): image not found
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.1_8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/Pango.py", line 41, in <module>
    FontDescription = override(FontDescription)
  File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError
```

**Comment by ragu-manjegowda** [comment] 2021-03-04 00:18
I am facing similar issue,

`brew upgrade zim` fails with following error

```
==> /Users/ragu/Documents/homebrew/opt/python@3.9/bin/python3 ./setup.py install --prefix=/Users/ragu/Docu
ments/homebrew/Cellar/zim/0.73.5/libexec                                                                  
                                                                                                          
** (process:92448): WARNING **: 15:48:32.702: Failed to load shared library 'libpango-1.0.0.dylib' referen
ced by the typelib: dlopen(libpango-1.0.0.dylib, 9): image not found                                      
Traceback (most recent call last):                                                                        
  File "/private/tmp/zim-20210303-92426-4a9n29/zim-desktop-wiki-0.73.5/./setup.py", line 25, in <module>  
    import makeman # helper script
```

However I do not see the error here,
```
ragu:~$ python3.9
Python 3.9.2 (default, Feb 25 2021, 17:10:26) 
[Clang 10.0.0 (clang-1000.10.44.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Gtk
<stdin>:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
>>> 
```

**Comment by dehesselle** [comment] 2021-03-24 01:01
Hi,
I do not have access to Apple Silicon based hardware - can I interest you to test my build (see https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/990)? I'd like to know if Rosetta 2 makes it work. (There's still a chance it breaks because of other issues.)

**Comment by pwac092** [comment] 2021-05-06 01:35
hiya! any news on this front? I am a heavy zim user and we are being issued these machines at work..

**Comment by reagle** [comment] 2021-06-10 20:43
I don't see any *entry* in brew for zim-desktop-wiki. BTW: I tested @dehesselle's build (downloaded from dropbox) which worked fine running on Rosetta2.

**Comment by reagle** [comment] 2021-06-29 01:08
This is the only thing holding all of my homebrew installs back. Has anyone had any luck?

**Comment by dehesselle** [comment] 2021-06-29 21:43
Are you generally asking because you want a native arm version or is something missing from my build that keeps you from using that instead?

**Comment by Fededon13** [comment] 2021-09-13 13:11
Same problem...

`brew install --build-from-source zim`

After install:
`zsh: segmentation fault  zim`

**Comment by murattepegoz** [comment] 2021-10-07 16:15
Is there anyone able to install zim on mac without rosetta2? If yes, I would highly appreciate if you write down the steps.

**Comment by dehesselle** [comment] 2021-10-15 20:40
No, still not possible.

For reference, this is (at least part of) what's blocking us from running Zim natively on arm:
https://gitlab.gnome.org/GNOME/pygobject/-/issues/455

**Comment by YURll** [comment] 2021-11-12 12:42
Hi @reagle @murattepegoz ,
As far as I understand Rosetta is just like a WINE on Ubuntu, isn't it? 
I am a new Mac user, so could you be so kind to provide instructions on how it's possible to run Zim on Mac M1? I'm OK to run it via Rosetta or any other options.

**Comment by reagle** [comment] 2021-11-12 13:16
@YURll, honestly, maintaining two versions of homebrew for x86 (Rosetta) and arm64 (M1) python and GTK libraries is a pain. @dehesselle is working on an [easy to use](https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1712#issuecomment-955543094) Mac app, which works for me and I recommend.

**Comment by YURll** [comment] 2021-11-12 14:01
@reagle, many thanks for the link, and many thanks for @dehesselle for his fork. This app is a really powerful helper!
Also, thank all of you for your time and this soft.

**Comment by dehesselle** [comment] 2021-11-17 18:26
I'm closing this as a duplicate in favor of another issue as that reflects the current state of things best (IMHO).
Thank you for your understanding.

**Comment by dehesselle** [comment] 2021-11-17 18:26
Duplicate of #1517

**Closed by dehesselle** 2021-11-17 18:26 UTC
