### ISSUE TITLE
Use case project directory wiki

### ISSUE THREAD

**Issue by rjmaris** [zim-desktop-wiki/zim-desktop-wiki#306] opened 2018-01-30 22:18 UTC
Apart from having one or two global wikis on my desktop (one for private stuff, one for professional stuff) I also use a couple of ZIM wikis in some project directories. For this, the only requirement is to create an empty <_projectname_>.zim file.
When I double-click on this file, while working on the project, I get this project wiki opened.
There are some minor issues that makes working with it suboptimal. Notably directories and text files that are not related to wiki content.
A solution could be the introduction of a sort of **.zimignore** file. Further, Zim could automatically ignore files that do not expose the header info in the first line.

If the use case sounds interesting, some more discussion would make sense, though.

**Comment by Osndok** [comment] 2018-01-30 22:42
I'm interested to learn more about the *.zim files, I thought that was an entirely separate thing (libzim). ATM, the best solution would probably be to put them into there own directories. It would be an extra layer of clicks, but then you wouldn't have to maintain the .zimignore file as the project changed.

On a completely separate note, I think that .zimignore file is a great idea, and I'm pretty sure I have seen it floating around here or launchpad.

**Comment by rjmaris** [comment] 2018-01-30 22:56
Hm, if you create a ZIM notebook the traditional way, you don't have anything to do with - default - notebook.zim in ~/notebooks/Notebookname/

Try it in any directory. touch a xxxx.zim, double click on it and you see the tree filled with content. A text file with the same name is created, too (start page). If you create links to local documents in a wiki text page, you can open them instantly all via short, relative links. The same applies to images, e.g. measurement screenshots. All of this is relocatable to another directory path.

**Comment by jaap-karssenberg** [comment] 2019-01-15 07:20
Please turn this ticket in a more concrete proposal

**Comment by rjmaris** [comment] 2019-01-15 10:19
You're right. My proposal is somewhat vague.
Let me focus on the .zimignore idea since this would explicitly support the creation of project specific wikis in project directories that contain a lot of other files. The purpose of .zimignore is only apparent in this context to prevent bloating the tree section of the GUI with files that are not related to the Wiki. That's all (upon the intended usage of ZIM, in a ZIM-specific one, the tree consists naturally of Wiki documents only).

Instead of .zimignore, other methods can be implemented:
- all of the wiki text files can also be defined as to start with a header line in order to be recognized as a wiki specific file (suffers of need to automatic text file modification upon zim software update).
- instead of .zimignore, a file could be established that simply lists all of the text files that are created in the zimwiki (at the directory level where  <projectname>.zim exists. The list could even be part of this file, and - for backward compatibility - be interpreted as "old style" if empty. If desired, existing project related text files can be manually added in this list. It is then up to the user to ensure that an already existing text file has utf-8 encoding.

**Comment by jaap-karssenberg** [comment] 2019-01-15 10:54
In the current master branch already the index ignores all folders that do
not contain "*.txt" files, so clutter should be less.

Future plan is indeed to check the file header and exclude files that are
not formatted as wiki pages. This is needed as solution for issue #164 as
well.

I'm also open to a patch that supports ".zimignore". My preferred would be
to make it same or similar to format supported by ".gitignore" because that
is what users expect.

**Comment by jaap-karssenberg** [comment] 2020-11-20 11:14
Consider this duplicate of #164 for now - long term solution might be to natively support markdown with ".md" file extensions instead

**Closed by jaap-karssenberg** 2020-11-20 11:14 UTC
Labels: needs info
