### ISSUE TITLE
text color

### ISSUE THREAD

**Issue by catalinterpeziceanuosf** [zim-desktop-wiki/zim-desktop-wiki#1063] opened 2020-04-27 14:17 UTC
Thanks for the great app.

Is it possible to improve it by adding the possibility to change the text colour?
Let's say I need one word to be blue, and another to be red.
Can you add such a feature?

Thanks,
Catalin

**Comment by introt** [comment] 2021-12-05 12:58
Duplicate of #268

**Closed** 2021-12-15 10:29 UTC
Labels: duplicate
