### ISSUE TITLE
Help Window is blocked when called from the settings

### ISSUE THREAD

**Issue by tehkonst** [zim-desktop-wiki/zim-desktop-wiki#1805] opened 2021-12-14 14:18 UTC
**Describe the bug**
When I'm in the settings window and click anywhere the `Help` button, I can't scroll and close the help window, until I close the settings. 
It's annoying.

**To Reproduce**
1. Go to `Edit` > `Templates` (or `Preferences`)
2. Click on `Help` button
3. Try to close or scroll the Help Window

**Expected behavior**
The help window has to be active when called from dialogs.

**Environment (please complete the following information):**
 - Version 0.74.3 -- ppa
 - linux xUbuntu 20.04

**Comment by introt** [comment] 2021-12-15 16:01
Related to, if not a duplicate of, #1166

**Comment by jaap-karssenberg** [comment] 2022-05-24 18:48
Re-opened as I believe this should be fixed. Only way to get this working is to make settings dialog a window instead of a dialog. This then requires some work on how submitting a "form" works in the UI.

**Comment by jaap-karssenberg** [comment] 2022-05-24 18:50
Sorry for the noise - agree it is duplicate of #1166 - acted on the last comment saying "not planned"

**Closed by jaap-karssenberg** 2022-05-24 18:50 UTC
Labels: bug, duplicate

**Comment by introt** [comment] 2022-05-25 11:57
No worries. GitHub recently introduced a second close button (`Close as not planned (Won't fix, can't repro, duplicate, stale)` vs. `Close as completed (Done, closed, fixed, resolved)`) so I've been trying to press it where appropriate to mark duplicates and stale issues as such while reserving the "old close" for stuff that's confirmed to have been taken care off.

Also sorry for extra noise, but I haven't tried closing a closed issue before, so I've got to try it out here :)
