### ISSUE TITLE
Large non-zim .txt files break or catastrophically slow new indexing / Zim injects page headers into non-zim .txt files

### ISSUE THREAD

**Issue by BehindTheBrain** [zim-desktop-wiki/zim-desktop-wiki#472] opened 2018-06-21 23:27 UTC
Part 1: (fairly serious bug)

Zim attempting to index very large non-zim text files in the notebook directory cause catastrophic slowdown during re-indexing or initial indexing. For some notebooks, indexing never completes (3+ days), breaking the notebook entirely. 

There are two potential fixes:

1) During indexing, checking page headers before processing the txt file for links, etc., (which should be done anyway for correctness and efficiency). Zim's ability to metabolize new manually written text files intended to be using as notebook would be impacted, but that's a pretty nitch case, and arguably much less important, and is easily overcome by including the headers manually. 

2) Offering the option of changing the default extension for note pages by updating /notebook/layout.py: default_extension = '.txt' to '.zxt' or user-defined value. I have done basic testing of this and it seems to work flawlessly; thanks to Jaap for the clean modular code that makes this single character change possible! With only GUI updates, a menu option would allow this file extension to be user-defined by setting this value. The only thing that I can find that breaks is the viewing of the Zim help notebook (which is still in *.txt). I also tested export, which still works as before.

Part 2: (potentially dangerous bug, if you're a programmer)

Zim also regularly injects page headers into my non-zim text files. Systematically reproducing this indicates that Zim only injects headers if some edit has been made to the txt file via Zim's interface, though in practice, I end up with many more non-zim text files having injected page headers at the top than desired or intended... These have been config files for scripts, etc., which can be quite problematic, especially if they're not ascii/utf-8?

Potential fix: 2) above of the extension, also addresses this issue, and already trivially works. It just needs a menu option and a little more thorough testing to confirm nothing breaks. In general, it is a cleaner isolation and simpler to code than page headers, but I understand if it is not desired as the default. This could still easily be a user-defined option though.

**Comment by Osndok** [comment] 2018-06-21 23:47
I run into this kind of thing quite regularly, and sometimes resort to keeping stuff zipped up so zim won't munge around in them... which is a shame, because I think Zim (because of its better and seamless model) could truly compete with the heavyweight file browsers, and this adds a lengthy unzip/zip workaround.

IMO, this is solid indication that we should use a special file extension, as has been discussed in the past (#54, #164, #449 ?), and (apart from a horrible transition/migration) would be a straight-forward change.

**Comment by BehindTheBrain** [comment] 2018-06-21 23:56
I fully agree. Zim also serves as a great general file browser with annotation, and used to work wonderfully for this purpose. Since the latest indexing change,s I have also been using the same crutch you mention of archiving stuff that shouldn't be, to continue using Zim. It is great that notepages are ASCII/UTF and Zim keeps "text" as the backend, for lack of lock-in, simplicity, robustness, and generally good unix-coding text-where-possible philosophy, but the extension would be much better changed.

**Comment by BehindTheBrain** [comment] 2018-06-22 03:10
As mentioned, put this into a zim_txt_to_whatever.py file, make it executable, and run:

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
To convert Zim notebooks in .txt file-extension format to default of .zxt or user-defined value

To execute, put this script just above your notebook directory, and either:
    $ chmod +x zim_txt_to_whatever.py
    $ ./zim_txt_to_whatever.py
    
    or 
    $ ./zim_txt_to_whatever.py yourchosenextension
    
    $ python3 zim_txt_to_whatever.py
    
    or 
    
    $ python3 zim_txt_to_whatever.py yourchosenextension

It defaults to .zxt if you don't supply a command line argument
"""

from glob import glob
import shutil
import sys


if(1 < len(sys.argv)):
    extension = '.' + sys.argv[1]
else:
    # Or, make the students directory the relative path to cwd
    extension = '.zxt'

filenames = glob('**/*.txt', recursive = True)

for file in filenames:
    rename = False
    with open(file) as f:
        first_line = f.readline()
        if 'Content-Type: text/x-zim-wiki' in first_line:
            rename = True
    if rename:
        shutil.move(file, file.split('.')[0] + extension)

I wonder what the likelihood of future-proofness on the continued use of the modular .txt implementation as it currently stands is, such that we'd be safe switching without the project going that way?

**Comment by Osndok** [comment] 2018-06-22 05:32
I see you already found it, I don't know why the search wasn't working for me! ... but I'm just going to leave a note with it's number too... in a vain effort to make future searches more fruitful... #366

**Comment by BehindTheBrain** [comment] 2018-06-22 08:59
After a full conversion to *.zxt, and more testing, this seems to work wonderfully. It allowed me to see which files Zim had injected, which it turns out was ~8,000 of my old non-zim *.txt data and log files now having Zim headers. These were surely not all accidentally clicked on and edited (the supposed mechanism by which Zim would hijack a txt file). The only "fix" needed to work with zxt was to convert the "Manual" notebook to zxt as well in /usr/share/zim/manual/

**Comment by jaap-karssenberg** [comment] 2019-02-07 19:37
I consider this a duplicate of #164

**Closed by jaap-karssenberg** 2019-02-07 19:37 UTC

**Comment by BehindTheBrain** [comment] 2020-10-01 08:46
#907 is relevant here. #164 was just export I think.
