### ISSUE TITLE
Zim fails to attach an image

### ISSUE THREAD

**Issue by Alienheartbeat** [zim-desktop-wiki/zim-desktop-wiki#576] opened 2018-12-05 13:25 UTC
zim	0.68
os	Xubuntu

When I attempt to drag a png or jpg image into zim, it fails silently.
When I use "Insert/Image" it fails with the following in the text box.

> This is zim 0.68
> Platform: posix
> Locale: en_US UTF-8
> FS encoding: UTF-8
> Python: (2, 7, 15, 'candidate', 1)
> Gtk: (2, 24, 32)
> Pygtk: (2, 24, 0)
> No bzr version-info found

	
```
======= Traceback =======
  File "/usr/lib/python2.7/dist-packages/zim/gui/widgets.py", line 3211, in do_response
destroy = self.do_response_ok()
  File "/usr/lib/python2.7/dist-packages/zim/gui/pageview.py", line 6611, in do_response_ok
src = self.notebook.relative_filepath(file, self.path) or file.uri
  File "/usr/lib/python2.7/dist-packages/zim/notebook/notebook.py", line 1083, in relative_filepath
document_root = LocalFolder(self.document_root.path) if self.document_root else None# XXX
  File "/usr/lib/python2.7/dist-packages/zim/newfs/local.py", line 47, in init
FSObjectBase.init(self, path, watcher=watcher)
  File "/usr/lib/python2.7/dist-packages/zim/newfs/base.py", line 392, in init
FilePath.init(self, path)
  File "/usr/lib/python2.7/dist-packages/zim/newfs/base.py", line 280, in init
self.pathnames = _splitnormpath(path)
  File "/usr/lib/python2.7/dist-packages/zim/newfs/base.py", line 152, in _splitnormpath
elif makeroot and os.name != 'nt' and names[0][0] != '/':
IndexError: string index out of range
```

**Comment by pdwilso** [comment] 2018-12-06 12:57
do you have bzr installed?

**Comment by Alienheartbeat** [comment] 2018-12-06 14:42
no, I have never used version control.

**Comment by jaap-karssenberg** [comment] 2019-02-11 13:34
Duplicate of #550

**Closed by jaap-karssenberg** 2019-02-11 13:34 UTC
