### ISSUE TITLE
Bug - link to a notebook

### ISSUE THREAD

**Issue by j41rj** [zim-desktop-wiki/zim-desktop-wiki#1179] opened 2020-07-12 12:57 UTC
I tried create a link to a notebook without specify a note inside it, using only "name?", then show up a msg with this text:

This is zim 0.72.1
Platform: posix
Locale: en_US UTF-8
FS encoding: utf-8
Python: (3, 6, 9, 'final', 0)
PyGObject: (3, 26, 1)

======= Traceback =======
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 5816, in do_activate_link
    self._do_activate_link(link, hints)
  File "/usr/lib/python3/dist-packages/zim/gui/pageview.py", line 5840, in _do_activate_link
    ZIM_APPLICATION.run('--gui', uri, pagename)
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 684, in run
    self._run_cmd(cmd, args) # test seam
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 695, in _run_cmd
    w = cmd.run()
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 267, in run
    notebook, page = self.build_notebook()
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 226, in build_notebook
    notebookinfo, page = self.get_notebook_argument()
  File "/usr/lib/python3/dist-packages/zim/main/__init__.py", line 164, in get_notebook_argument
    pagename = Path.makeValidPageName(args[1])
  File "/usr/lib/python3/dist-packages/zim/notebook/page.py", line 158, in makeValidPageName
    raise ValueError('Not a valid page name: %s (was: %s)' % (newname, name))
ValueError: Not a valid page name:  (was: )

**Comment by introt** [comment] 2021-12-15 16:47
Duplicate of  #965

**Closed by introt** 2021-12-15 16:47 UTC
