### ISSUE TITLE
Verbatim text is unreadable on Linux Mint, using Dark Themes

### ISSUE THREAD

**Issue by wiebow** [zim-desktop-wiki/zim-desktop-wiki#2343] opened 2023-04-07 11:19 UTC
**Describe the bug**
Verbatim styled text is unreadable on Linux Mint, using a dark theme. Probably on other Linux distributions with dark themes. I myself use Linux Mint 21.1 Cinnamon with the Dark Aqua theme.

**To Reproduce**
1. Use a dark theme on Linux
2. Select text and use the Verbatim style
3. Watch the text go dark

**Expected behavior**
The text will get the correct markup but it will be too dark to read. See screenshot.

**Screenshots**
![Screenshot from 2023-04-07 13-14-22](https://user-images.githubusercontent.com/1338966/230599888-b17ad4c8-5845-479a-995f-9a5ae0524516.png)

**Environment (please complete the following information):**
 - Version 0.75.1
 - OS: Linux Mint 21.1 Cinnamon
 - Language: englisch

**Additional context**
None.

**Comment by introt** [comment] 2023-04-11 19:16
Duplicate of #1727 - please see links therein for editing `style.conf` in the meantime

**Closed as not planned by introt** 2023-04-11 19:16 UTC
Labels: duplicate
