### ISSUE TITLE
Open Another Notebook... is not working

### ISSUE THREAD

**Issue by VpGitHub231** [zim-desktop-wiki/zim-desktop-wiki#2207] opened 2022-10-24 11:55 UTC
**Describe the bug**
When i try to open another Notebook via the Menu File - Open Another Notebook ... i get the following error message:

This is zim 0.75.0
Platform: nt
Locale: de_AT cp1252
FS encoding: utf-8
Python: (3, 10, 7, 'final', 0)
PyGObject: (3, 42, 1)

======= Traceback =======
  File "zim/actions.py", line 159, in _on_activate
  File "zim/actions.py", line 130, in __call__
  File "zim/gui/uiactions.py", line 126, in show_open_notebook
  File "zim/gui/widgets.py", line 2825, in unique
  File "zim/gui/notebookdialog.py", line 318, in __init__
  File "zim/gui/notebookdialog.py", line 174, in __init__
  File "zim/gui/notebookdialog.py", line 97, in __init__
  File "zim/notebook/info.py", line 26, in get_notebook_list
  File "zim/notebook/info.py", line 244, in __init__
  File "zim/notebook/info.py", line 255, in read
  File "zim/notebook/info.py", line 330, in parse
  File "zim/notebook/info.py", line 164, in __init__
  File "zim/newfs/base.py", line 249, in __init__
  File "zim/newfs/base.py", line 172, in _joinabspath
ValueError: Not an absolute path: .\pic_logo_infineon.gif

Double Click on the notebook.zim file in the Notebook folder works perfectly and opens the Notebook.
I'm not 100% sure if this is really a Bug or just a problem with my Paths. But i checked all Paths and they seem correct, also it worked without any issues on the previous version of ZIM.

**To Reproduce**
1. Go to 'File'
2. Click on 'Open Another Notebook'
3. See error

**Expected behavior**
Open the Dialog for opening another Notebook as it was in the previous ZIM version.

**Environment (please complete the following information):**
 - Version 0.75.0 installed over 0.74.5
 - OS: Windows 10 Enterprise 64-bit
 - Language: English

**Additional context**
I have the same error on my Debian (Testing) Linux machine with the development version from around three weeks ago. So i guess it's a more general error and not just Windows specific.
I can try the newest development version on my Linux machine today evening and report the outcome if needed.

Thanks for your Work!

**Comment by ClaudeErpSystem** [comment] 2022-10-24 18:57
I have the same issue with 0.75.0 release.

**Comment by jaap-karssenberg** [comment] 2022-10-25 18:47
Duplicate of #2165

**Closed as completed by jaap-karssenberg** 2022-10-25 18:47 UTC
Labels: bug, needs triage
