### ISSUE TITLE
Mouse copy broken to and from zim

### ISSUE THREAD

**Issue by aurisnoctis** [zim-desktop-wiki/zim-desktop-wiki#719] opened 2019-03-26 09:39 UTC
#### Problem copying to zim

1. mark text e.g. in shell with left mouse button
2. go to zim window and press middle mouse button --> text inserted
3. instead of step 2. go to zim window and first format some text that is already there, e.g., pressing Strg+2 to make a headline and then press middle mouse button --> nothing inserted; check with `xclip -o`: `Error: target STRING not available`

#### Problem copying from zim

1. mark text in zim with left mouse button
2. go to, e.g., shell and press middle mouse button --> marked text inserted 
3. instead of step 2. first format text in zim, e.g., press Strg+2 to make a headline; then go to shell and press middle mouse button --> nothing inserted; check with `xclip -o`: `Error: target STRING not available`

May be related to #326 ?

System: Linux Mint 19 (in English) and OpenSUSE 15.0 (in German)
gtk versions on openSUSE 15.0 (Linux Mint not here to check): 2.24.32 and 3.22.30

Thanks for your help!

**Comment by jaap-karssenberg** [comment] 2019-03-26 09:58
What version of zim are you testing?


Op di 26 mrt. 2019 10:39 schreef aurisnoctis <notifications@github.com>:

**Comment by aurisnoctis** [comment] 2019-03-26 11:38
On OpenSUSE 15.0 it is zim version 0.67 (zim-0.67-2.1.noarch).
Can't check Mint 19 right now.

**Comment by jaap-karssenberg** [comment] 2019-03-28 20:11
Then it is not related to #326 as that is a Gtk3 specific issue while zim 0.67 is still using Gtk2.

Testing with zim 0.70 under Gtk3 I cannot reproduce

**Comment by jaap-karssenberg** [comment] 2019-04-30 15:14
Closing for now. Please open a new issue if similar issues are observed in zim >= 0.70

**Closed by jaap-karssenberg** 2019-04-30 15:15 UTC
Labels: bug, needs testing
