### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jcjessen** [zim-desktop-wiki/zim-desktop-wiki#1132] opened 2020-06-19 20:57 UTC
Add Murat's advanced "tasklist" plugin features into zim.

**Comment by muguu** [comment] 2020-06-22 12:25
features are:
- history of ticked tasks (with ticked date)
- collect and view comments to tasks (with the comments plugin)
- tick open tasks / untick ticked tasks directly in task list

**Comment by introt** [comment] 2021-09-28 18:37
@muguu May I ask why you haven't submitted any of [your features](https://gist.github.com/muguu) upstream? The PRs are open and many would appreciate your work!

**Comment by introt** [comment] 2021-09-28 18:41
This issue is a duplicate of #1128

**Comment by jaap-karssenberg** [comment] 2021-11-23 20:14
Closing this issue for now, if there is an update somewhere, please file it as a pull request.

**Closed by jaap-karssenberg** 2021-11-23 20:14 UTC
