### ISSUE TITLE
Task view crashes

### ISSUE THREAD

**Issue by allenj7** [zim-desktop-wiki/zim-desktop-wiki#677] opened 2019-02-15 17:59 UTC
Get the following when trying to launch the task view:

This is zim 0.68
Platform: nt
Locale: en_US cp1252
FS encoding: mbcs
Python: (2, 7, 14, 'final', 0)
Gtk: (2, 24, 10)
Pygtk: (2, 24, 0)
No bzr version-info found

======= Traceback =======
  File "zim\actions.pyo", line 157, in do_activate
  File "zim\actions.pyo", line 140, in func
  File "zim\plugins\tasklist\__init__.pyo", line 169, in show_task_list
  File "zim\gui\widgets.pyo", line 2973, in unique
  File "zim\plugins\tasklist\gui.pyo", line 124, in __init__
  File "zim\plugins\tasklist\gui.pyo", line 476, in __init__
  File "zim\plugins\tasklist\gui.pyo", line 496, in refresh
KeyError: u'M_T_Th_F'

Only in 1 notebook. Others work. Any help would be appreciated! Thanks

**Comment by jaap-karssenberg** [comment] 2019-02-18 12:58
Duplicate of #484

**Closed by jaap-karssenberg** 2019-02-18 12:58 UTC
