### ISSUE TITLE
Support Apple Silicon

### ISSUE THREAD

**Issue by chenrui333** [zim-desktop-wiki/zim-desktop-wiki#1383] opened 2021-01-31 06:41 UTC
👋  it looks like right now the build failed on apple silicon right now.

<details>
<summary>build failure on 11-arm</summary>

```
==> /opt/homebrew/opt/python@3.9/bin/python3 ./setup.py install --prefix=/opt/homebrew/Cellar/zim/0.73.5/libexec

** (process:20188): WARNING **: 22:08:47.954: Failed to load shared library 'libpango-1.0.0.dylib' referenced by the typelib: dlopen(libpango-1.0.0.dylib, 9): image not found
Traceback (most recent call last):
  File "/private/tmp/zim-20210130-20169-t4ssig/zim-desktop-wiki-0.73.5/./setup.py", line 25, in <module>
    import makeman # helper script
  File "/private/tmp/zim-20210130-20169-t4ssig/zim-desktop-wiki-0.73.5/makeman.py", line 13, in <module>
    from zim.main import HelpCommand
  File "/private/tmp/zim-20210130-20169-t4ssig/zim-desktop-wiki-0.73.5/zim/main/__init__.py", line 31, in <module>
    from zim.notebook import Notebook, Path, \
  File "/private/tmp/zim-20210130-20169-t4ssig/zim-desktop-wiki-0.73.5/zim/notebook/__init__.py", line 43, in <module>
    from .info import NotebookInfo, NotebookInfoList, \
  File "/private/tmp/zim-20210130-20169-t4ssig/zim-desktop-wiki-0.73.5/zim/notebook/info.py", line 18, in <module>
    from .notebook import NotebookConfig, _resolve_relative_config
  File "/private/tmp/zim-20210130-20169-t4ssig/zim-desktop-wiki-0.73.5/zim/notebook/notebook.py", line 17, in <module>
    import zim.templates
  File "/private/tmp/zim-20210130-20169-t4ssig/zim-desktop-wiki-0.73.5/zim/templates/__init__.py", line 61, in <module>
    from zim.templates.functions import build_template_functions
  File "/private/tmp/zim-20210130-20169-t4ssig/zim-desktop-wiki-0.73.5/zim/templates/functions.py", line 24, in <module>
    from zim.formats.html import html_encode
  File "/private/tmp/zim-20210130-20169-t4ssig/zim-desktop-wiki-0.73.5/zim/formats/__init__.py", line 78, in <module>
    from zim.plugins import PluginManager
  File "/private/tmp/zim-20210130-20169-t4ssig/zim-desktop-wiki-0.73.5/zim/plugins/__init__.py", line 50, in <module>
    from zim.actions import hasaction
  File "/private/tmp/zim-20210130-20169-t4ssig/zim-desktop-wiki-0.73.5/zim/actions.py", line 36, in <module>
    PRIMARY_MODIFIER_MASK = _get_modifier_mask()
  File "/private/tmp/zim-20210130-20169-t4ssig/zim-desktop-wiki-0.73.5/zim/actions.py", line 31, in _get_modifier_mask
    from gi.repository import Gtk
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/opt/homebrew/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 144, in load_module
    importlib.import_module('gi.repository.' + dep.split("-")[0])
  File "/opt/homebrew/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "/opt/homebrew/lib/python3.9/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.1_6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/Pango.py", line 41, in <module>
    FontDescription = override(FontDescription)
  File "/opt/homebrew/lib/python3.9/site-packages/gi/overrides/__init__.py", line 195, in override
    assert g_type != TYPE_NONE
AssertionError
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/runs/1800108963
relates to https://github.com/Homebrew/homebrew-core/pull/70087

**Comment by jaap-karssenberg** [comment] 2021-01-31 07:30
I think this is not a Zim issue but an issue with the dependencies. Please
verify that the python gtk libraries load correctly before building Zim.

E.g. in python 3 command line try "from gi.repository import Gtk"

Op zo 31 jan. 2021 07:41 schreef rui <notifications@github.com>:

**Comment by ragu-manjegowda** [comment] 2021-03-04 09:15
I am facing similar issue,

`brew upgrade zim -v` fails with following error

```
==> /Users/ragu/Documents/homebrew/opt/python@3.9/bin/python3 ./setup.py install --prefix=/Users/ragu/Docu
ments/homebrew/Cellar/zim/0.73.5/libexec                                                                  
                                                                                                          
** (process:92448): WARNING **: 15:48:32.702: Failed to load shared library 'libpango-1.0.0.dylib' referen
ced by the typelib: dlopen(libpango-1.0.0.dylib, 9): image not found                                      
Traceback (most recent call last):                                                                        
  File "/private/tmp/zim-20210303-92426-4a9n29/zim-desktop-wiki-0.73.5/./setup.py", line 25, in <module>  
    import makeman # helper script
```

However I do not see the error here,

```
Python 3.9.2 (default, Feb 25 2021, 17:10:26) 
[Clang 10.0.0 (clang-1000.10.44.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from gi.repository import Gtk
<stdin>:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
>>> 
```

**Comment by murattepegoz** [comment] 2021-10-07 16:09
Is there anyone able to install zim on mac without rosetta2? If yes, I would highly appreciate if you write down the steps.

**Comment by dehesselle** [comment] 2021-11-17 18:20
I'm closing this as a duplicate of https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/1517 where you can track further progress on the matter. I favored that specific issue because it reflects the current state of things best.  
Thank you for your understanding.

**Closed by dehesselle** 2021-11-17 18:20 UTC

**Comment by dehesselle** [comment] 2021-11-17 18:24
Duplicate of #1517
