### ISSUE TITLE
[abrt] Zim: do_populate_popup(): pageview.py:5779:do_populate_popup:TypeError: Argument 2 does not allow None as a value

### ISSUE THREAD

**Issue by cheese** [zim-desktop-wiki/zim-desktop-wiki#835] opened 2019-05-09 08:31 UTC
https://bugzilla.redhat.com/show_bug.cgi?id=1708122

```
Description of problem:
Starting the computer.
Closing Zim after making an entry.

Version-Release number of selected component:
Zim-0.70-1.fc30

Additional info:
reporter:       libreport-2.10.0
cmdline:        /usr/bin/python3 /usr/bin/zim
crash_function: do_populate_popup
exception_type: TypeError
executable:     /usr/bin/zim
interpreter:    python3-3.7.3-1.fc30.x86_64
kernel:         5.0.10-300.fc30.x86_64
runlevel:       N 5
type:           Python3
uid:            1000

Truncated backtrace:
pageview.py:5779:do_populate_popup:TypeError: Argument 2 does not allow None as a value

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/zim/gui/pageview.py", line 5779, in do_populate_popup
    iter = buffer.get_iter_at_mark(buffer.get_mark('zim-popup-menu'))
TypeError: Argument 2 does not allow None as a value

Local variables in innermost frame:
self: <pageview.PageView object at 0x7fdbb51a4708 (zim+gui+pageview+PageView at 0x560bd1159700)>
menu: <Gtk.Menu object at 0x7fdbb499cf30 (GtkMenu at 0x560bd1405400)>
buffer: <pageview.TextBuffer object at 0x7fdbb4f14630 (zim+gui+pageview+TextBuffer at 0x560bd12abb90)>


```

**Comment by jaap-karssenberg** [comment] 2019-05-09 08:53
Duplicate of #807 fixed in release 0.71

**Closed** 2019-05-24 01:56 UTC
