### ISSUE TITLE
Keyboard binding for ToC widget

### ISSUE THREAD

**Issue by unformatted** [zim-desktop-wiki/zim-desktop-wiki#1458] opened 2021-05-03 16:13 UTC
Would it be possible to have a keyboard binding to toggle the ToC widget like clicking with the mouse folds up the ToC and another click unfolds it.

**Comment by introt** [comment] 2021-12-15 18:00
Duplicate of #201 (see second comment)

**Closed by introt** 2021-12-15 18:00 UTC
Labels: enhancement, needs triage
