### ISSUE TITLE
undo history dissapears when changing notes

### ISSUE THREAD

**Issue by quesada** [zim-desktop-wiki/zim-desktop-wiki#872] opened 2019-06-07 21:29 UTC
To reproduce:
- do work on note A
- go to note B
- go back to A. try to undo. Nothing happens.

This is a bit dangerous. I'm sure there's no easy fix, but bringing the issue up anyway just in case.

**Comment by quesada** [comment] 2019-07-08 03:21
Quick ping to remind everyone that this one can bite you.

**Comment by jsosulski** [comment] 2020-01-10 10:20
Lost a bit of work to this. Fortunately, I had a more or less recent git commit.

Anyone know where the issue is? Have not developed in python-gtk before.

**Comment by introt** [comment] 2021-12-15 08:50
This should be fixed in the recent versions - IIRC undo stack is preserved for the last 10 pages. Please open a new issue if the problem persists. Thanks!

**Closed by introt** 2021-12-15 08:50 UTC
