### ISSUE TITLE
links with ":" do not work

### ISSUE THREAD

**Issue by CRZeiss** [zim-desktop-wiki/zim-desktop-wiki#1402] opened 2021-02-17 14:39 UTC
Links like 

superoffice:contact.personarchive?db_id=1061008106&person_id=3312&contact_id=1157

do not work.

ZIM creates a new sub-page "contact.personarchive?db_id=1061008106&person_id=3312&contact_id=1157"
I assume the ":" cases ZIM to link a subpage

Same problem with Onenote-Links like 
onenote:https://d.docs.live.net/513e1f314a45940e/Dokumente/Handbuch/Verwaltung.one#ZIM&section-id={AC468AF2-8DD0-49DA-8436-B52F5CFC3C12}&page-id={58F20194-4998-4756-86E9-D043DCC57BA0}&end

**Comment by jaap-karssenberg** [comment] 2021-02-23 18:51
Yes, Zim only recognizes page links, file links and url links. There is no
link syntax like to examples you give in Zim.
Maybe you can use a url instead?

Op wo 17 feb. 2021 15:40 schreef CRZeiss <notifications@github.com>:

**Comment by introt** [comment] 2021-12-15 17:43
Duplicate of #513

**Closed by introt** 2021-12-15 17:43 UTC
