### ISSUE TITLE
In 'Jump to page' dialog select the first item automatically 

### ISSUE THREAD

**Issue by tehkonst** [zim-desktop-wiki/zim-desktop-wiki#1874] opened 2022-01-17 01:44 UTC
When I press `ctrl+j` and start typing I need to press `Down` button to choose the page, even if it's the first page in the list.
It will be much more convenient if the first element of the list is active immediately.

**Comment by sojusnik** [comment] 2022-01-17 08:54
Yes to this 100x, but I'm afraid this is a technical limitation, according to Jaap.

**Comment by introt** [comment] 2022-01-19 14:40
Duplicate of #1242

**Closed by introt** 2022-01-19 14:40 UTC
Labels: duplicate, enhancement, needs triage
