### ISSUE TITLE
Linux: ctrl-w "close" shortcut closes the whole program

### ISSUE THREAD

**Issue by jcelerier** [zim-desktop-wiki/zim-desktop-wiki#2226] opened 2022-11-15 19:40 UTC
**Describe the bug**
- I hit ctrl-w or the "close" button in the file menu (not the "quit" one).
- I expect this to close the currently opened tab
- This closes the whole program

Basically it seems like there is currently no way to close a single tab anymore

zim 0.75.1 on Arch Linux (also tried rebuilding it from git - eea32ce7 which seems to be the same)

**Comment by aqeeliz** [comment] 2022-11-16 06:12
As far as I understand, "close" doesn't close current tab, it closes the current notebook.

If you have multiple notebooks open, "quit" will quit zim, closing all notebooks, "close" will only close the selected notebook.

**Comment by jaap-karssenberg** [comment] 2022-11-16 09:02
Yes, this is intended behavior, Ctrl-W closes the main window of a
notebook, effectively closing that notebook. Ctrl-Q closes all notebooks.

There are no "tabs" in zim.

-- Jaap

**Closed as not planned** 2022-11-20 07:12 UTC
Labels: invalid

**Comment by jcelerier** [comment] 2022-11-28 02:05
Hmm weird, I was sure that at some point I could close one of the "tabs" / documents. But I cannot find how in the current version:

![x](https://user-images.githubusercontent.com/2772730/204176336-ab5f7026-d787-4a1f-8a12-7984c8209c89.png)

**Comment by introt** [comment] 2022-11-29 17:28
You might have been using the BookmarksBar - it's visually very similar (identical besides the green `+`), and does have an option to remove items.

Ps. Thanks for nudging me into enabling and using the BookmarksBar - found a bug similar to one I've fixed in the PathBar :)
