### ISSUE TITLE
Cannot open cross-notebook links without explicit page

### ISSUE THREAD

**Issue by ironfroggy** [zim-desktop-wiki/zim-desktop-wiki#1281] opened 2020-10-05 22:45 UTC
All my Notebooks have a list of each other interlinking. These are not to specific pages, they are all just links to `NotebookName?` and this worked fine in 0.68, the last version I used since updating. I've now upgraded to 0.73.2 and these links no longer work.

I can work around this by adding the home page of course, but it would be nice to let that be ambiguous or determined by teh target notebook.

```This is zim 0.73.2
Platform: nt
Locale: en_US cp1252
FS encoding: utf-8
Python: (3, 8, 3, 'final', 0)
PyGObject: (3, 36, 1)

======= Traceback =======
  File "zim/gui/pageview.py", line 6003, in do_activate_link
  File "zim/gui/pageview.py", line 6027, in _do_activate_link
  File "zim/main/__init__.py", line 687, in run
  File "zim/main/__init__.py", line 698, in _run_cmd
  File "zim/main/__init__.py", line 268, in run
  File "zim/main/__init__.py", line 227, in build_notebook
  File "zim/main/__init__.py", line 165, in get_notebook_argument
  File "zim/notebook/page.py", line 156, in makeValidPageName
ValueError: Not a valid page name:  (was: )```

**Comment by jaap-karssenberg** [comment] 2020-10-07 08:09
Bit of a corner case, don't think it was ever intended to work. Would need
a test case to cover this to make sure it does not break again.

**Comment by introt** [comment] 2021-12-15 16:48
Duplicate of  #965

**Closed by introt** 2021-12-15 16:48 UTC
