### ISSUE TITLE
display subpages in link autocomplete suggestions

### ISSUE THREAD

**Issue by mooseyboots** [zim-desktop-wiki/zim-desktop-wiki#1102] opened 2020-06-02 14:43 UTC
it would be great if the link autocomplete suggestions would display the subpages of a page that matches my search. 

eg i have a master page with an author's name, then subpages of their different texts with notes on them. i would like to search author name, and in the autocomplete suggestions all the subpages of their various texts would appear. that way i can think of the author name, and then decide which specific text to link to based on the list of suggestions.

this would seem trivial given that the full path currently already appears for any search matches.

**Comment by Nick222** [comment] 2020-06-03 00:03
You must start link from enter ":" - and it can see list of pages...

And ":" between pages...

**Comment by mooseyboots** [comment] 2020-06-03 00:57
yeah i understand how the syntax works.

the cool thing about the search now is that you don't have to start with : and then type the top-level page, then :, then the next level page, then : then next level page, you can just start typing and it will match a page. 

my use case is a list of annotations sorted by author, then book. but the author isn't the top level page, it's the second level. it is even slower for me to follow your suggestion and type out :, then the title of the top level page, then : , then author, then : again. 

my thought was to be able to display sub-pages of whatever matches roughly, so you only type author name, and all the sub-pages also appear. after all, the author name also appears in the full path of those sub pages, so they should be search results too.

**Comment by fdt-dev** [comment] 2020-06-03 19:18
Seems like a very narrow use case. I can understand how this would make your life easier, but it would make it less comfortable to use for many others including me.
You can type any page name anyway, you don't have to start with the author page in your use case. You must know which annotation you're looking for, so just type that name, the rest comes up automatically. The beauty of Zim is its simplicity. I hope it stays simple.

**Comment by introt** [comment] 2021-12-15 15:27
Considering this as a duplicate of #189, please continue discussion there

**Closed by introt** 2021-12-15 15:27 UTC
