### ISSUE TITLE
The "justify" property in style.conf has no effect

### ISSUE THREAD

**Issue by cheap-glitch** [zim-desktop-wiki/zim-desktop-wiki#1088] opened 2020-05-18 15:19 UTC
Hi,

in the config file `style.conf`, setting the value of the key `justify` has no effect on the text in the GUI:
```
[TextView]
justify=JUSTIFY_FILL
```

Whether the property is set to `JUSTIFY_LEFT`, `JUSTIFY_RIGHT` or `JUSTIFY_FILL`, the text always stays left-aligned.

I'm using Zim 0.72.1 with GTK 3.24.20 on ArchLinux.

**Comment by Nick222** [comment] 2021-02-23 19:35
Confirm - Zim 0.73.5 Xubuntu 20.10

**Comment by introt** [comment] 2022-05-22 15:40
Duplicate of #849, fixed by #1875

**Closed by introt** 2022-05-22 15:40 UTC
Labels: bug, needs triage
