### ISSUE TITLE
Pound sign (#) in file:/// link is being replaced by %23

### ISSUE THREAD

**Issue by 20NE** [zim-desktop-wiki/zim-desktop-wiki#488] opened 2018-07-14 14:56 UTC
Unlike in http:// URL link, pound sign (#) in **file:///** link is being replaced by **%23** automatically.

For example:
`file:///usr/share/doc/arch-wiki/html/en/Wake-on-LAN.html#Software_configuration`
become
`file:///usr/share/doc/arch-wiki/html/en/Wake-on-LAN.html%23Software_configuration`

result in "no such file" error when open/click the link. 

How do I keep it as #? 

Thanks in advance.

**Comment by jaap-karssenberg** [comment] 2019-02-11 20:26
In what part of the application is it replaced?  If I just type in this link in a page and click it, there is no "%23"

Be aware though that "#" is a valid file character, so result is always a "file not found". So probably need to improve the code that checks whether a file exists to check with and without the "#" part (and in that order).

**Comment by 20NE** [comment] 2019-02-12 03:53
Yes,"file not found"
Thanks

**Comment by myrdd** [comment] 2019-05-13 17:00
@20NE are you still able to reproduce the `%23` behavior? If so, what steps do you take to do so?

**Comment by jaap-karssenberg** [comment] 2021-12-13 12:28
Consider this a duplicate of #1412

**Closed by jaap-karssenberg** 2021-12-13 12:28 UTC
Labels: enhancement, good first issue
