### ISSUE TITLE
Symlink in attachment directory

### ISSUE THREAD

**Issue by phi-mah** [zim-desktop-wiki/zim-desktop-wiki#540] opened 2018-09-28 13:42 UTC
Trying to delete a zim-page whose attachment directory contains a symlink to an other directory triggers the following error:
```
This is zim 0.68
Platform: posix
Locale: en_US UTF-8
FS encoding: UTF-8
Python: (2, 7, 13, 'final', 0)
Gtk: (2, 24, 31)
Pygtk: (2, 24, 0)
No bzr version-info found

======= Traceback =======
  File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 157, in do_activate
    self.__get__(instance, instance.__class__)()
  File "/usr/lib/python2.7/dist-packages/zim/actions.py", line 140, in func
    self.func(instance, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 1095, in delete_page
    DeletePageDialog(self, path).run()
  File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 2797, in __init__
    text = self._get_file_tree_as_text(dir)
  File "/usr/lib/python2.7/dist-packages/zim/gui/__init__.py", line 2824, in _get_file_tree_as_text
    path = child.relpath(self)
  File "/usr/lib/python2.7/dist-packages/zim/newfs/base.py", line 366, in relpath
    names = start.pathnames
AttributeError: 'DeletePageDialog' object has no attribute 'pathnames'
```

I disabled the trash functionality:
```
cat notebook.zim                                                                                                                                                                
[Notebook]
version=0.4
name=Analysis
interwiki=
home=Home
icon=
document_root=
shared=True
endofline=unix
disable_trash=True
profile=
```

Btw, I tried to understand how zim is handling symlinked directories in general, but I do not get my head around it. In particular I am wondering what is supposed to happen with the files **within** a symlinked directory, if I delete:

1. a page whose attachment directory has been replaced by a symlink
2. a page with an attachment directory containing itself a symlink

from the tree view of the wiki?

I would understand if in case 1 the symlink is  transparent, i.e. a page delete affects the symlink as well as the content below it. However in my current workflow, the same behavior for case 2 would lead to rather dangerous situations, as I am using a symlink here to point to external files (i.e. as a shortcut) I do not want to touch at all from the desktop wiki.

**Comment by jaap-karssenberg** [comment] 2019-02-11 12:48
Duplicate of #420

**Closed by jaap-karssenberg** 2019-02-11 12:48 UTC
