### ISSUE TITLE
Notebook specific Interwiki Links

### ISSUE THREAD

**Issue by ChristianSilvermoon** [zim-desktop-wiki/zim-desktop-wiki#1870] opened 2022-01-15 20:40 UTC
The interwiki links system appears to be tied to a user-specific file on the user's system. This means custom interwiki links to external wikis on the web will not work across different systems and for multiple users collaborating on a notebook.

**Is your feature request related to a problem? Please describe.**
It will make sharing a notebook across multiple systems and users very frustrating when linking to external wikis with shortcuts such as `[[sw?Page]]` for example.

**Describe the solution you'd like**
The `notebook.zim` file for the specific notebook should be able to store a list of these shortcuts for external wikis.

**Describe alternatives you've considered**
Storing a separate file in the notebook folder to house a list of these shortcuts

**Additional context**
If someone were writing a wiki concerning a particular subject that already has its own dedicated wiki, it would be easier to link to that wiki with `[[external_wiki_shortcut_here?Page_Here]]` than it would be to manually pull up and copy/paste the link **EVERY** time. The Interwiki URLS file is neither user friendly nor discoverable unless you dig through the help menu, and is not friendly for those who use multiple devices and/or share a project with other users.

**Comment by introt** [comment] 2022-01-16 14:52
Thanks for the report! Unfortunately, it's a duplicate of #601

**Closed by introt** 2022-01-16 14:52 UTC
Labels: duplicate, enhancement
