### ISSUE TITLE
The Index sidebar scrolls together with the position of the mouse

### ISSUE THREAD

**Issue by leafcutterant** [zim-desktop-wiki/zim-desktop-wiki#362] opened 2018-02-28 21:55 UTC
0.67, Windows

I have enough items in the Index sidebar so that it can be scrolled. The Zim window doesn't need to have focus to do this, it should just not be minimized. If I move my mouse to the upper 25% of the screen (anywhere on any of the connected screens), Zim's Index bar starts to scroll up and continues to do so until it can scroll up no more. The same in the other direction.

This is distracting because it generates animations in the Zim window while I'm working in another window. It also makes me lose the last position I held in the Index bar.

**Comment by leafcutterant** [comment] 2018-03-01 17:22
It's unclear what triggers this behavior and can't be always replicated. A restart of Zim stopped it for now, but it's been recurring for months for me.

**Comment by Osndok** [comment] 2018-03-01 17:39
This sounds so crazy, that I doubt the issue is actually a problem with zim "holding onto the focus". Maybe gtk-for-windows (on the outside), but more likely interference from 3rd party software (like a smooth scrolling hack installed by your system manufacturer).

**Comment by jaap-karssenberg** [comment] 2019-01-15 12:53
Closing for now as I don't believe this is an issue with zim itself. Might indeed be an issue with the gtk library. New 0.70 release uses newer versions of the libraries, so would anyway need to retest with latest versions.

**Closed by jaap-karssenberg** 2019-01-15 12:53 UTC
