### ISSUE TITLE
Copying text out of Zim now loses formatting

### ISSUE THREAD

**Issue by dmaltschul** [zim-desktop-wiki/zim-desktop-wiki#1557] opened 2021-08-25 17:43 UTC
Previously, I swear I had no trouble copying text straight out of Zim and into other word processors (let's say MS Word) without losing formatting like italics and bold. However, I am no longer able to do this.
The Copy As functions aren't immediately useful for this, they paste symbols like * around words in programs like Word.

I've updated Zim, so this is now happening with 0.73.5 on Windows 10. I can't think of anything that changed around Zim, so maybe a Windows update impacted the behavior of the clipboard?

**Comment by jaap-karssenberg** [comment] 2021-08-31 14:24
I believe you are seeing this issue: Gtk3: rich copy-paste from zim to
clipboard broken with port to Gtk3 · Issue #326 ·
zim-desktop-wiki/zim-desktop-wiki · GitHub
<https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/326>

**Comment by dmaltschul** [comment] 2021-09-06 09:11
Hmmm, that seems like the most likely issue, yes, though the function was working for me in 2020, still a bit baffled as to why the issue kicked in for me now. I am trying to work around this with @e3rd 's https://github.com/e3rd/zim-plugin-copy-rich

**Comment by introt** [comment] 2021-12-15 18:29
Duplicate of #326 - most likely

**Closed by introt** 2021-12-15 18:29 UTC
