### ISSUE TITLE
distutils is deprecated and it was removed in python 3.12

### ISSUE THREAD

**Issue by topazus** [zim-desktop-wiki/zim-desktop-wiki#2420] opened 2023-07-19 01:15 UTC
**Describe the bug**

The distutils is deprecated and it was removed in python 3.12.
The Python 3.12 is available in Fedora Rawhide.

https://github.com/python/cpython/issues/92584
https://fedoraproject.org/wiki/Changes/Python3.12

**Comment by jaap-karssenberg** [comment] 2023-07-19 08:23
This is in scope of #2209

**Comment by introt** [comment] 2023-07-21 20:29
Duplicate of #2296 which in turn is in scope of #2209

**Closed as not planned by introt** 2023-07-21 20:29 UTC
Labels: bug, needs triage
