### ISSUE TITLE
Allow combining formatting like italic, bold, underline

### ISSUE THREAD

**Issue by rjmaris** [zim-desktop-wiki/zim-desktop-wiki#305] opened 2018-01-30 21:11 UTC
In practice, I experience that e.g. italic & bold cannot be mixed, i.e. nested behaviour is not supported.

Version: V0.65 (Ubuntu).

**Comment by Osndok** [comment] 2018-01-30 21:35
Correct. All formatting in zim is intended to be mutually exclusive by design (there are actually a few broken edge cases where formats temporarily mix). Do you have any thoughts on this, or how it can be better communicated?

**Comment by rjmaris** [comment] 2018-01-30 22:10
Well, regarding thoughts on this: some time ago I came across this while creating a simple wiki syntax based text widget in Tcl/Tk, and learnt that the only viable method to to this is recursive handling of //, ** and __ sequences. Perhaps, code snippets from other open source wiki code can be used as inspiration.
If desired, I could attach the Tcl code - but it woudn't be that easy to transfer it in python.

**Comment by jaap-karssenberg** [comment] 2019-12-16 14:29
Fix merged in develop as commit 52554cc7e610000b3e1777b46367487f23692e7a

**Comment by sojusnik** [comment] 2019-12-23 17:57
After the multiformatting was merged, removing a format with a keyboard shortcut isn't possible any more when the cursor is in the middle of a word. Applying a format still works though. But when the word is completely selected (f.i. by double-clicking on it), then both – applying and removing – with one shortcut is working.

To reproduce: click in the middle of a word, format it with a shortcut (f.i. strg+b), use the shortcut again and you'll see that the formatting remains.

Happens with the current Zim Development PPA on Ubuntu 19.04.

**Comment by sojusnik** [comment] 2020-01-11 12:39
Is it intended that multiformatting isn't working in the latest 0.72.1 release, while it was working in the 0.72.0 snapshot release in Ubuntu?

**Closed** 2020-06-06 13:20 UTC
Labels: enhancement, fix available
