### ISSUE TITLE
missing curly brackets

### ISSUE THREAD

**Issue by stiglitzkleiber** [zim-desktop-wiki/zim-desktop-wiki#2353] opened 2023-04-27 08:43 UTC
**Describe the bug**
PROBLEM:  Using mac osx (m1, Ventura), square brackets and curly brackets can't be utilised in Zim, because the key bindings do not work.

**Expected behavior**
type <option + 8> for curly bracket open (etc)

**SOLUTION**
This is a bug that comes in with the plugin BookmarksBar – not loading this plugin solves the problem.

**Environment (please complete the following information):**
 - Version 0.75.1 (Homebrew installation)
 - mac osx (m1, Ventura)
 - Language: en

**Comment by reagle** [comment] 2023-04-27 20:06
Dup of #2335 ?

**Comment by stiglitzkleiber** [comment] 2023-04-28 07:14
correct, same problem, now with a remedy

Kaspar Schwarzenbach

Am 27. Apr. 2023, 22:06 +0200 schrieb Joseph Reagle ***@***.***>:

**Comment by introt** [comment] 2023-06-11 09:27
Thank you for identifying the cause @stiglitzkleiber , I'll close this ticket in favor of the older one.

**Closed as completed by introt** 2023-06-11 09:27 UTC
Labels: bug, duplicate
