### ISSUE TITLE
Drag & Drop pages from Sidebar does not work from v0.70

### ISSUE THREAD

**Issue by Alienheartbeat** [zim-desktop-wiki/zim-desktop-wiki#1699] opened 2021-10-21 23:26 UTC
**Describe the bug**
Up to v0.69 I could move pages by dragging and dropping using the left side pane.
From 0.70 this no longer worked,
but I can still drag and drop pages by getting a page into the pathbar,
then dragging from there to the sidebar.

**To Reproduce**
1. Attempt to drag and drop a page from one location in sidebar to another - nok.
This appears in debug log lines 324 - 327.

2. Drag and drop a page from pathbar to a location in the sidebar - ok.
This appears in debug log lines 328 - 361.

**Expected behavior**
Both 1 & 2 should work.
Only 2. works.  

**Environment (please complete the following information):**
Xubuntu 18.04
All versions of zim from 0.70.
English

Debug Log:
[zim-211022a.log](https://github.com/zim-desktop-wiki/zim-desktop-wiki/files/7393357/zim-211022a.log)

**Comment by jaap-karssenberg** [comment] 2021-11-30 20:15
Consider duplicate of #390

**Closed by jaap-karssenberg** 2021-11-30 20:15 UTC
Labels: bug, needs triage

**Comment by dreua** [comment] 2021-12-04 09:50
Just in case I'm not the only one landing here with a totally different issue: Be aware that Drag and Drop in the "Index" Sidebar plugin has been disabled by default in the upgrade from 0.74.1 to 0.74.2 for safety reasons, see #1443 .

If you are willing to take the risks, got to Edit, Preferences, Plugins, Page Index, Configure and check "Use drag&drop to move pages in notebook"
