### ISSUE TITLE
Special folders for attachments

### ISSUE THREAD

**Issue by KatjaD-CH** [zim-desktop-wiki/zim-desktop-wiki#466] opened 2018-06-11 00:16 UTC
**Situation**
There are several issues with attaching files with `txt` extension.

I stumbled over the same problem when I attached 8000 RFCs in text format. Zim went realy busy with indexing these files.

There is a proposal to change the filename from `test.txt` to `!test.txt`.
Others propose that Zim checkes the file header to check whether it's a Zim-file or not.

In my opinion both variants ar not satisfying, additionaly I don't like the medley of pages and attachments in the same folder.

**My proposal**
I would suggest to make, only when necessary, a folder with a name in the form `!` + `pagefile-name` especially for attachments.

`test.txt`  - the file for the page
`!test.txt` - the folder for the attachments

**Remarks**
Can be realized already manually. The folder and the attachments therein aren't visible in the page tree. The attachments can be linked with the help of the `Link` button.

At the moment attachments can't be placed with the `Attach File` button.

Attachments in these folders aren't visible in the attachment browser.

Zim wouldn't have the check each file to handle it correctly.

As Zim already has functions builtin to move files and update links to these, it shouldn't be a big problem to provide an option to convert existing wikis.

**Comment by jaap-karssenberg** [comment] 2019-02-07 19:40
See also #164

**Comment by jaap-karssenberg** [comment] 2021-12-13 12:19
Considering this a duplicate of #164 

Please note that the notebook API allows for different layouts, will accept pull requests for these (optional / configurable in addition to default layout) but won't work on it myself.

**Closed** 2022-05-22 08:56 UTC
Labels: duplicate, enhancement
