### ISSUE TITLE
feature: make the "Move selected text" popup/context menu option keyboard-accessible

### ISSUE THREAD

**Issue by Osndok** [zim-desktop-wiki/zim-desktop-wiki#1023] opened 2020-02-23 16:38 UTC
I find myself shuffling data between pages quite frequently, and particularly for cases where a list of items needs to be "dispatched" to various pages, I find the "move selected text" feature to be quite useful... but a bit tedious, and requiring more effort than it ought to... but only because I have to continuously transition between the keyboard & mouse.

It would help me if there were some way to access this feature from the keyboard. Either by creating a conventional menu option for it, a direct keyboard shortcut, or maybe a keyboard shortcut to simply open the context menu as if a right-click event had occurred at the present selection (as then the option would only be a few arrow keys & enter away from activation).

**Comment by Osndok** [comment] 2020-02-29 13:46
For reference:
https://github.com/zim-desktop-wiki/zim-desktop-wiki/blob/master/zim/gui/pageview.py#L5907

**Comment by introt** [comment] 2021-12-15 10:26
Duplicate of #1793, excuse us for the order!

**Closed by introt** 2021-12-15 10:26 UTC
