### ISSUE TITLE
Tasklist Zim 0.75 bugs ?

### ISSUE THREAD

**Issue by reagle** [zim-desktop-wiki/zim-desktop-wiki#2299] opened 2023-01-19 12:28 UTC
### Discussed in https://github.com/zim-desktop-wiki/zim-desktop-wiki/discussions/2173

<div type='discussions-op-text'>

<sup>Originally posted by **Nick222** October  3, 2022</sup>
1) Task list settings are not saved after the list window is closed.

2) Dates of closed tasks remain red.

Xubuntu 22.04</div>

**Comment by reagle** [comment] 2023-04-25 15:22
@jaap-karssenberg, I wonder if you can confirm this? I see there's been a 0.751 release but I can't migrate to 0.75* because the task manager doesn't remember I prefer active tasks only.

**Comment by introt** [comment] 2023-05-06 10:14
I can confirm that selecting the Active list is not saved between closing and opening the task list window and that dates of closed tasks are indeed red on the latest commit 4110a13c391c24aa92c8b4edfc77bb79563d4368

**Comment by jaap-karssenberg** [comment] 2023-05-24 06:37
Afraid I cannot reproduce this. My steps are as follows:

1. open the task window from the toolbar or menu,
2. select "active" tasks list in the sidebar
3. close the task window
4. open task window again from the toolbar or menu
5. see "active" still selected

Be aware that when you open the task window from the tasklist side pane
"popout" button, you get the selection that was active in the side pane.

Regards,

Jaap

**Comment by reagle** [comment] 2023-05-24 12:30
Hi @jaap-karssenberg, I downloaded the latest dev copy and, for me, the setting does survive closing the task window but **not** closing the Zim window/app. Does it for you?

> If I set to show to "Active" only, and then terminate and rerun, the setting has been lost. This should be moved to issues. (I don't understand/use point 2?)

**Comment by jaap-karssenberg** [comment] 2023-05-24 13:52
Yes, if you close the notebook, this state is not saved. This is expected
behavior in the current implementation. Will have a look if I can add that
to the uistate.

-- Jaap

**Comment by reagle** [comment] 2023-05-24 14:26
Okay then. This was not the case in the previous task plugin and this was a significant issue for me that I stayed back on the earlier version.

**Closed as completed** 2023-06-06 17:31 UTC
Labels: bug, usability, regression
