### ISSUE TITLE
Whenever I type past a certain limit (before creating a new paragraph), the text turn into boxes!

### ISSUE THREAD

**Issue by train-con** [zim-desktop-wiki/zim-desktop-wiki#2086] opened 2022-06-15 21:54 UTC
I'm a new user of zimwiki that started today. I use a 2020 Macbook Pro that runs Monterey.

As the title states, the text turn into boxes whenever I'm typing past a certain limit, and it only happens when I don't press the return key and start a new paragraph. When I select the altered text and highlight it, I can see what the text looks without the boxes, but the boxes stay and I can't see the original text without deleting some of it.

<img width="1251" alt="Screen Shot 2022-06-15 at 5 35 05 PM" src="https://user-images.githubusercontent.com/107587112/173936902-bb5faa2a-c782-47ef-a010-09771e28925f.png">
<img width="1262" alt="Screen Shot 2022-06-15 at 5 55 55 PM" src="https://user-images.githubusercontent.com/107587112/173938315-95916bc0-10a4-4850-9167-4893b9e61a21.png">

**Comment by nelas** [comment] 2022-06-16 08:46
Hi, welcome to Zim, and thanks for reporting. This looks similar to #2082

**Comment by train-con** [comment] 2022-06-16 22:34
> Hi, welcome to Zim, and thanks for reporting. This looks similar to #2082

Ah! Downloading the new version v0.74.3_80 seemed to fix it. Thank you for replying. :)

**Comment by dehesselle** [comment] 2022-06-17 00:24
Yes, this is a duplicate of the aforementioned issue. Closing.

**Closed by dehesselle** 2022-06-17 00:24 UTC
Labels: bug, needs triage
