### ISSUE TITLE
[pageview] Paste loses indentation

### ISSUE THREAD

**Issue by lorenrosen** [zim-desktop-wiki/zim-desktop-wiki#1751] opened 2021-11-18 22:47 UTC
If text is pasted into an apparently empty but indented line (so actually the line may not be empty but might just have tabs or spaces), the pasted text ends up with no indentation.

1. On a zim page, create an empty line (via the return key)
2. Indent the insertion point via the tab key (not the space key)
3. Paste some text
4. The text will be pasted with no margin

**Expected behavior**
The pasted text inserted but indented.

**Environment (please complete the following information):**
 - Version 0.74.2 via ppa -- though the problem is not new
 - OS: ubuntu 20.04
 - Language: english. haven't tried a RTL lang.

I have a partial fix, which I'll submit as a response.

**Comment by lorenrosen** [comment] 2021-11-19 01:20
Here's my partial fix. I'm just making a comment for it, because it's quite simple, and it may not be the right fix.

In the function force_line_start (in gui/pageview.__init__.py) there's an if
        if 'indent' in element.attrib
Remove (or just comment out) the corresponding else, and the statement in the else. Thus
        if 'indent' in element.attrib:
		set_indent(int(element.attrib['indent']))
	#else:
		#set_indent(None)

One reason this may not be quite right is that there may be a reason the 'else' was there.

**Comment by ainoneko** [comment] 2023-11-04 14:55
I had the same problem in Zim 0.73.* and 0.74.*
In 0.72.1 (and older) and 0.75.2 it works OK (though, I have not used 0.75.2 a lot).
I don't see mentioning it being fixed in the CHANGELOG, but it may have been fixed somehow?

**Comment by introt** [comment] 2023-11-05 11:50
Fixed in ee5dce5b0a08394630f6d9e2851e86e7099507f4; the commit message refers to #1934 which is a duplicate of this issue.

**Closed by introt** 2023-11-05 11:50 UTC
Labels: bug
