### ISSUE TITLE
Sidepanes have no horizontal scroll bar (0.73.x)

### ISSUE THREAD

**Issue by fdt-dev** [zim-desktop-wiki/zim-desktop-wiki#1171] opened 2020-07-10 16:35 UTC
The side panes have no horizontal scroll bars. For example if there are many levels of documents within a Wiki the Index sidepane can not be scrolled sideways to show the lower levels. Instead the names of the lower levels are truncated with three dots at the end.

I think for large wikis (and I have quite a large one with more than 3000 partly nested pages) there should be the possibility to scroll the sidepanes not just vertically but also horizontally.

The only current option is to pull out the sidepanes and make them larger, which takes away from the usable space in the middle.

The attachment demonstrates that. The vertical scrollbar is visible. There is no horizontal scrollbar.

![Bildschirmfoto von 2020-07-10 18-32-59](https://user-images.githubusercontent.com/35032197/87177445-ec853280-c2db-11ea-90de-655373b55f3d.png)

It affects Linux and Windows versions.

**Comment by fdt-dev** [comment] 2020-11-02 21:52
Just a small reminder: Is this a feature that could be useful? Is it possible to implement? I'm not sure that it is. I tried to mess around in the source code; couldn't get it to work.
I think it'd be very nice to have a horizontal scrollbar in the sidepanes. Just now I have the issue with long page names that if I have several of those which are prefixed identically, it is rather hard to find the correct one. If I could scroll over to the right, it'd be very helpful.
Thank you.

**Comment by jaap-karssenberg** [comment] 2020-11-03 10:35
In code just disabling the "ellipsize" in the column rendering should
result in horizontal bar showing up.

Usability wise I'm undecided. Agree that at some point you'll need the
scrollbar to show content to far out to the right. However for notebooks
with limited nesting levels, the ellipsize works better.

Not sure what a good rule  would be to make the behavior OK in all cases.
Could make it optional, but that just puts the burden to the user.

-- Jaap

**Comment by fdt-dev** [comment] 2020-11-03 11:55
Hi Jaap,

thank you. Just for my understanding: I thought that the scrollbars (both vertical and horizontal) will only be displayed if they're really necessary. What would be the downside of having one? You seem to have a reason in terms of design of the application why you didn't want a horizontal scrollbar.

Not sure whether I understand what the ellipsize property does. I assume it truncates the text at some point to make it fit the widget. But that's exactly my point: if there are several entries and they all begin in a similar way, they become very nearly impossible to discern. For example (and I know, I'm doing it wrong, don't be angry), I use Zim to keep track of correspondence with friends (I really should use a real e-mail client for that, I know). The way I do it is to prefix the letter I received with the name of the sender -- let's say "Elizabeth" -- and then immediately after that I put the date when I received it -- let's say today: 20201103. The entry would read: "Elizabeth20201103". It's easy to see that if I have received ten messages from this hypothetical Elizabeth, I'd have ten entries all beginning in "Elizabeth" and the pane usually isn't wide enough to show the date trailing behind.

But I mean, this problem really applies to many use cases.

The side panes are sepratate plugins as of 0.7x.y Would it be a terrible burden for the user to have an additional checkbox in the configuration of the plugin? Maybe, since there are several of those side pane plugins. Useability-wise I think not having horizontal scrollbars is worse than having them. But that's my opinion.

Thank you for taking the time to respond.

Fabian
________________________________
Von: Jaap Karssenberg <notifications@github.com>
Gesendet: Dienstag, 3. November 2020 11:35
An: zim-desktop-wiki/zim-desktop-wiki <zim-desktop-wiki@noreply.github.com>
Cc: fdt-dev <fdtdev@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [zim-desktop-wiki/zim-desktop-wiki] Sidepanes have no horizontal scroll bar (0.73.x) (#1171)


In code just disabling the "ellipsize" in the column rendering should
result in horizontal bar showing up.

Usability wise I'm undecided. Agree that at some point you'll need the
scrollbar to show content to far out to the right. However for notebooks
with limited nesting levels, the ellipsize works better.

Not sure what a good rule would be to make the behavior OK in all cases.
Could make it optional, but that just puts the burden to the user.

-- Jaap

**Comment by jaap-karssenberg** [comment] 2020-11-03 14:45
THe "ellipsize" property is responsible for the "..." truncation you see in
the screenshot. Without this property the truncation does not happen and
scrollbars are used when the column doesn't fit.

Ideally I would want these to play together such that truncation and
scrollbar work at the same time, but that is not how it works in the
toolkit.

-- Jaap

**Comment by fdt-dev** [comment] 2020-11-03 16:51
Thank you for the explanation. Sorry for being so insistent on this topic. It's just that I really miss the scrollbar. The horizontal scrollbar would make the side panel even more useful. What am I supposed to do with entries which are beyond the right border of the panel?

Why do you need the truncation? For cosmetic purposes, probably. But the right most border of the panel would automatically truncate text anyway. So, again: why the explicit truncation when an implicit truncation would happen by the border of the column?

I maintain that the horizontal scrollbar is essential if the text grows beyond the right border of the panel. I just don't understand what a truncation does in terms of usability vs. a horizontal toolbar.

I'd rather forgo the cosmetics of the three-dot-truncation and be able to scroll to the right to actually be able to read the entries there. The three dots do nothing in terms of usability, and frankly the truncation annoys me to no end. I can't imagine that I am the only one with this problem. I really don't want to make the panel wider than in the screenshot above. Not by much anyway. The main part is the center panel with the actual text, but the side panel is needed for navigation. I am running older netbooks and they have displays at 1280x768 pixel resolution. But even at 1920x1080 it's not much better. If I had a 4K display, I'd make the side panel larger, but as it is a scrollbar is the only real option.

Truncation in conjunction with a scrollbar would probably cost a lot of performance because every pixel column scrolled would require a redraw of everything in the panel. That's probably why the framework doesn't support it in the first place. What's the appeal of this truncation anyway? :D Sorry, I don't get it.

I'm really sorry if I don't understand your reasons. I'll leave it at that. Thank you for your time!

**Comment by fdt-dev** [comment] 2020-11-04 17:14
I'm really sorry, but I can't let it stand as it is. I'm just again working in my notebook and this truncation is driving me up the wall. I believe that a horizontal scrollbar is necessary. You said: 

> Usability wise I'm undecided. Agree that at some point you'll need the
> scrollbar to show content to far out to the right. However for notebooks
> with limited nesting levels, the ellipsize works better.

I disagree. Maybe I can't see it. My questions would therefore be:

- Why would ellipsize work better for notebooks with limited nesting levels? Better than a horizontal scrollbar? And why would that be the case? That makes no sense to me, because for notebooks with limited nesting levels the truncation isn't needed anyway. Or the other way around: as soon as the text goes beyond the width of the widget the truncation makes everything worse. I mean,  it really hasn't anything to do with the number of nesting levels, but only with the length of the page titles. :)

- Why is the truncation for notebooks with limited nesting levels good in regards to usability? That would needlessly limit the usability without giving any advantage.

I understand that this is your project and you can do whatever you want with it. So, I don't want to impose but since apparently it's such a minor change in the code I think it would be beneficial. Am I really the only one who thinks this is an issue?

Please consider changing the behaviour of the side panes.

If not I will have to manually change the code myself every time there's a new release. That's fine, I can do that, too. I am assuming that I have to remove line 391 in the file __init__.py in the folder plugins/pageindex  Is that correct? Seems so, because  it worked. Thank you for the suggestion! I'm learning every day. It looks and works much better with the horizontal scrollbar than with the truncation. Please try it yourself and compare. I think the horizontal scollbar is the better option.

Thank you.

**Comment by oscarbidabehere** [comment] 2021-06-17 11:58
+1 I agree the horizontal scrollbar is needed

**Comment by jaap-karssenberg** [comment] 2021-06-18 19:33
Still feel we need a complete different widget for deep nested trees. With horizontal scrolling you miss the context where you are in the tree. But added a patch with the option so you can at least try it. It's a bit flacky though, rendering does not refresh immediately, might require a re-start of the application before it works correctly.

**Comment by fdt-dev** [comment] 2021-06-18 21:33
> Still feel we need a complete different widget for deep nested trees. With horizontal scrolling you miss the context where you are in the tree. But added a patch with the option so you can at least try it. It's a bit flacky though, rendering does not refresh immediately, might require a re-start of the application before it works correctly.

Jaap, thank you for that.

But still for the rest of the text: What are you talking about? Without the scrollbar you miss the context to the other side, too. That's the whole point. The scrollbar is a non-issue. It is not possible to make the widget wide enough (because when push comes to shove it's never going to be wide enough).
Prioritizing: The center widget containing the text is the most important thing. The left and right panels have simply a supporting role. The scrollbar is not a problem, because the whole point of a scrollbar is to be able to scroll. So in order to get the context, why not scroll back the other way. I like scrollbars.

Conversely: What would this "completely different" widget look like? It's a tree that needs visualizing. What would you possibly use other than a tree? 

Until now I kept removing the ellipsize line. Rendering has been immediate and flawless. It seems like a perfectly easy fix to a problem that is bothersome. Seems like the new option is doing exactly that. Thank you very much. I hope this will come up in the PPA?

Look, sorry if I am enthusiastic about that point. I respect your decisions. Thank you again for this great application that has been very helpful to me over the last eight years and hopefully in years to come. But that's exactly why I am enthusiastic about these things, because this in particular has been a usability issue so far.

**Comment by sojusnik** [comment] 2021-06-19 20:46
Can we have the same setting for the tag sidebar? ATM, the horizontal scrollbar is activated there by default, which I would prefer to deactivate.

**Comment by jaap-karssenberg** [comment] 2021-06-26 17:59
Also added for tags plugin in commit e3147

**Comment by sojusnik** [comment] 2021-06-27 09:31
@jaap-karssenberg Many thanks!

If it is not too laborious, can you please add the remaining two settings from the index side pane to the tags side pane, namely:

> The option **Automatically expand sections on open page** determines whether the section for the current page is automatically expanded.

> The option **Automatically collapse sections on close page** determines whether sections that are automatically expanded are also collapsed again on moving away from the page. It does not affect sections that were expanded manually by clicking on the expand arrow.

**Comment by sojusnik** [comment] 2021-07-07 06:35
> @jaap-karssenberg Many thanks!
> 
> If it is not too laborious, can you please add the remaining two settings from the index side pane to the tags side pane, namely:
> 
> > The option **Automatically expand sections on open page** determines whether the section for the current page is automatically expanded.
> 
> > The option **Automatically collapse sections on close page** determines whether sections that are automatically expanded are also collapsed again on moving away from the page. It does not affect sections that were expanded manually by clicking on the expand arrow.

@jaap-karssenberg Thanks for adding those settings too!

**Comment by introt** [comment] 2021-08-10 18:30
> With horizontal scrolling you miss the context where you are in the tree

> Without the scrollbar you miss the context to the other side, too

What are your opinions on word wrap? That'd keep the context on both sides for arbitrarily long page names[0] with the downside of making the list much longer. Coupled with bullets for pages without subpages this makes for a (in my opinion) very fashionable alternative[1].

0. Unless, of course, the nesting goes so deep you can't fit multiple characters, but at that point it sounds like the information contained in the page names should be stored in pages instead
1. https://i.stack.imgur.com/vQwmi.png shows one implementation of such a TreeView; I'd add bullets to differentiate between multiple leaf nodes so they don't end up like this: https://i.stack.imgur.com/5dr6N.png

**Comment by fdt-dev** [comment] 2021-08-10 19:58
I'm not a fan of word wrapping. I'd rather have the option for the panels to turn on scrolling (I think that has been implemented. If someone feels like they lose the context by scrolling horizontally, then they can turn off scrolling. And by the way: What kind of an argument is that anyway? You do know that you can scroll both ways with a horizontal scrollbar? So, if you scrolled to the right and "lost the context" then you can scroll back to the left. That's the beauty of it.

As for deep nesting and why you have to mock it: It makes sense to do it, trust me. I'm using nesting as a form of classification of the things that I do. I go from the general to the specific. It helps to use that in order to structure information when working at the office. I really don't get why you mock that. Please don't. How deep the nesting has to go until it becomes unfeasible to use word wrap depends mostly on how wide you can make the left panel. So ... what was your point again? I don't have any 4K displays available (and even if, that'd only delay the problem). I don't use Zim in full-screen if possible (and even if, that'd only delay the problem). The left panel will always have a limited width. For everyone. I already mentioned that: No matter how wide the left panel is, there will always come a point where either the nesting level becomes invisible (for lack of a much needed horizontal scrollbar) or the word wrapping becomes unfeasible. The latter will become a problem sooner. So, we're back at horizontal scrollbars again. Why are they such a big problem? I don't get it.

For example: I am maintaining project documentation for my work in the excess of 4000 articles in Zim. As part of this documentation I have meeting minutes that go back seven years on 20+ projects. So, in order to structure those I for example had to split project category, project name, topic "meeting minutes", year, month, day (and sometimes time of day) as separate nesting levels. (It actually goes one nesting level below that, because I have "attendees" and "notes" on the same level but one below that previously noted level.) Does it make sense? It does to me, yes, because it is logically structured and it is helpful. Would it make sense to store this information as page contents? No, because then the structure would be lost. Would word wrapping help? Well, have you ever word wrapped "2018"? I hope that I got my point across. Thank you. I know that maybe I am misusing Zim. Sorry. It's the way I am using it. And it works. It just would work better with a horizontal scrollbar.
Of course that way I'm using it the nesting goes deep and beyond the limited size of the left panel. Please seriously consider the possibility that somebody makes a deep nesting structure that actually makes sense. I know very well that a horizontal scrollbar is really the only option to deal with that. Losing the context is a strange and moot argument (sorry Jaap). Just try it, thank you.

I have argued very clearly why horizontal scrollbars are a necessity. See my comment from June 18th. Word wrapping is worse because it makes the panel even less usable, less well arranged. To me anyway. I don't understand why it is such a terrible thing to have a horizontal scrollbar. I really don't get why everyone seems to see it as a downside. I see it as a plus. But if it can't be done because it isn't liked, then fine ... Zim is modular enough that I may make my own panel for that. It's just a terrible hassle to keep it up to date whenever a new version of Zim is being released. Mostly because it doesn't work properly to keep plugins in the user's folder. But that'd be another issue to post.

This is my last comment on this topic. I have made my case clear enough. I have to accept that nobody else sees the benefit of horizontal scrolling. A simple option in the preferences dialogue window of the panel would have sufficed. It's not much code. Why not give users the option to turn on the horizontal scrollbar as needed? I thought that Jaap has an implementation for exactly that in the development branch. I'd consider that the solution, so please Jaap merge it into the master branch. This is a good solution.

**Comment by introt** [comment] 2021-08-11 13:37
Greetings, @fdt-dev!

I'd like to start by the way of apology. I came across this issue while filing other ones and didn't read all the prior discussion, just skimmed the beginning and Ctrl+F:d for wrap after coming up with the idea. This was foolish of me and I regret the fact I hurt your feelings and made you feel mocked.

I am not a representative of the project; my collaborator status is due to just a few contributions, but I'd like to point out that Jaap has already implemented the horizontal scroll bars for you and they will be included in all the future releases starting with 0.74.

I imagine Jaap hasn't merged this with the master branch as between 0.73.5 and the develop branch there has been a major rewrite for moving to GTK3 – as well as the fact that you've stated you've been able to make the current version accommodate your needs.

You may not agree with the way releases handled, and I know how that feels: a workflow-breaking regression that I personally took the time to fix, #1452, hasn't landed either- though I'm at fault there for preferring to patch the develop branch.

With your need for horizontal scrollbar being taken care of, I'd like to address your questions about the explicit truncation before proposing (to Jaap) another solution for the more general problem.

I've gotten the impression that Jaap deeply cares about the quality of the Zim user experience and would rather provide complete solutions later than partial solutions right now. If I've understood the design philosophy regarding context correctly, it basically boils down to these two rules:

1. Don't hide things from the user.
2. If you must hide things, indicate that they are hidden.

This is oversimplified and doesn't cover eg. the right-click menu or keybindings; though everything in those is usually available elsewhere. However, it does cover for example why tabs stay behind when closing the panels and **the reason for ellipsis**: they tell the user that something is hidden. You'll also see them used for menu items that open dialog windows and other things; compare "Find..." with "Find Next", for example.

Why the explicit truncation? To show the user that the title doesn't fit- just cutting it off at the edge bodes badly for page titles with spaces as there's nothing to indicate whether the title continues beyond the edge, and that disqualifies it from being good UX. The presence of the horizontal scroll bar at the bottom doesn't fix it either, as it doesn't indicate _which_ title gets cut short.

So, the downside of having a horizontal scroll bar _without ellipsis_, the missing context, is that there's no indication whether a specific page name continues off-screen. You may be okay with that, and Jaap has conceded to give the users the option, but there's no argument whether it breaks the UX. Without a way to give the users the aforementioned context, it does. With the ellipses, it would not.

**Comment by introt** [comment] 2021-08-11 14:45
I'd also like to share my POV about wiki organization; feel free to disagree!

Large wikis, like Wikipedia, don't rely on folder structure to organize information- at some point, which varies a lot depending on the use case, it just doesn't make sense. The problem isn't nesting depth; it's the fact that our lives are but a struggle against entropy, and most information doesn't follow a neat hierarchical model. There's a solution to this, but let me preface it with how I came across it while faced with a related problem.

When I started studying anatomy, I imagined most structures could be neatly organized into more general sets with just a few exceptions, but as it later turned out this is hardly the case. Failing to fit every muscle into a larger group made me miss the forest for the trees- they're all connected! Not literally, of course, but in a lot of ways that a single hierarchical structure simply couldn't portray. So, what's the solution?

Links. But not just single links between pages; _pages of links_. Wikipedia is a great example of this: most pages are simply under the wiki/ path, and there are separate pages called categories as well as other page types like list articles (articles that list other articles, like [this favourite of mine](https://en.wikipedia.org/wiki/List_of_inventors_killed_by_their_own_inventions)). Those categories can and do overlap and thus better represent the various ways we humans categorize things; for example the animal cow can be categorized as a mammal and a food source as well as an animal with significance in various traditions- that simply can't represented with nested, exclusive categories.

With Zim, you aren't limited to using either one. Mix and match them all you want!

I don't mean to take a jab at your style -as long as it works for your use case, there's nothing inherently wrong with it- but I would like to suggest an alternative workflow combining links and a little nesting with a core plugin.

> For example (and I know, I'm doing it wrong, don't be angry), I use Zim to keep track of correspondence with friends (I really should use a real e-mail client for that, I know). The way I do it is to prefix the letter I received with the name of the sender -- let's say "Elizabeth" -- and then immediately after that I put the date when I received it -- let's say today: 20201103. The entry would read: "Elizabeth20201103". It's easy to see that if I have received ten messages from this hypothetical Elizabeth, I'd have ten entries all beginning in "Elizabeth" and the pane usually isn't wide enough to show the date trailing behind.

This is a completely valid use case for Zim! However, I'd use a combination of the Journal plugin and links (as the tag plugin doesn't show the page count, but that's a separate issue); the workflow could then look something like this:

1. Receive a letter
2. Open Zim
3. Open today's journal page with Alt+D OR select a date by clicking the journal plugin's calendar OR jump to Journal (can be renamed):year:month:date(:(Letter from )Elizabeth (subject))
4. Create either a sub page or a header to separate multiple letters arriving on the same day
5. Add a link to `:letters:Elizabeth`
6. Done!

If you aren't putting other things into that notebook's journal, the days when you've received letters are now bolded. You can open `letters:Elizabeth` to view the (number of) BackLinks to each and every one of Elizabeth's letters. There's [an option for showing the full paths](https://github.com/zim-desktop-wiki/zim-desktop-wiki/pull/1479) (containing the dates) in the development branch's BackLinks plugin, but lacking that you can use `Search` > `Search BackLinks...` in the current stable release.

I'd recommend a similar workflow for your other use case; though please do make backups and take the time to familiarize yourself with different wiki organization methods before settling on a new system. I went through a whole bunch of them before finding the one that suits me, even going as far as temporarily replacing Zim with TiddlyWiki, which has a completely flat note hierarchy.

**Comment by introt** [comment] 2021-08-11 15:24
>> 2. If you must hide things, indicate that they are hidden.

> We're already at the point of hiding information.

> The ellipsize function causes loss of context and it does not provide the user with any way to get the missing information back. That's definitely terrible. That's what I try to get across here.

My bad; I forgot to mention that the full title is visible my mousing over it. It's not perfect, but no information is lost and you won't get a WPOE (explained later). (Edit: unless you nest really deep, but we'll get to that later. By the way, have you tried configuring the index panel to be at either the top or the bottom of the screen, instead of either side?)

> And if your UI isn't entirely broken you can also see that there is a horizontal scrollbar, therefore you immediately know that there is potentially hidden information.

I personally think having two scroll bars, regardless of their orientation, belongs to canvases and other rectangular things, which a tree view is not in my opinion. A single top-level page with a long name will introduce a wide horizontal scrollable area, which combined with a vertical scroll bar introduces the possibility of scrolling to a screen full of white. Also,

> And also: What about vertical scrollbars?

Regardless of direction, with a single scroll bar there's no possibility of getting a screen full of white.

I don't know what you run Zim on, but my GTK theme has a dotted line, kinda like a horizontal version of the ellipsis, to indicate that you're not seeing the full list. Thus it's immediately clear which way the content continues, unlike with two scroll bars which only give you an idea of how big a rectangle you'd need to fit that content.

> See: I don't get why the horizontal scrollbar would make anything worse.

To reiterate: the problem isn't the scrolling direction; it's the additional degree of freedom, which breaks the above rule 2 as well as introduces unusable states like the White Panel Of Emptyness.

> Why does a horizontal scrollbar break the UX? If that were the case there were no horizontal scrollbars anywhere. Is that the case? No. Conversely: Why does ellipsize not break the UX? That makes no sense.
Also: You want context? I understand, I want that, too. The scrollbar itself is giving the context. It clearly shows that there is more. Ellipsize breaks the UX for me, because despite making it blatantly obvious that there is information missing, it still does not provide the user with any way to get this information back. No matter how you try to talk around that point: That's worse!

I think I've answered all of these above; if not, please allow me to retry.

> So either we live with the fact that things have to be truncated (which I really dislike) or we introduce a horizontal scrollbar.

This isn't a new problem, and there are various other ways to solve it. The notes are mere files and folders on the disk, after all. We can take a look at existing tools for the job for inspiration. I'll leave that to another comment, as this one is primarily a reply to yours.

**Comment by introt** [comment] 2021-08-11 15:25
# A "completely new" widget - How to view a tree?

Zim stores notes and their structure with text files and folders, respectively. Thus, we can look at other file system browsing tools for inspiration for such a widget that supports arbitrary nesting depths.

Most solve the problem of context with a path bar. This scales well from the prompt of UNIX shells to fully-featured file managers. But how to we handle moving between nested pages? Does one need to list the sub-pages of the current page's sub-pages one by one?

My suggestion is combining a path bar with a partial tree view, as can be seen in this Finder screenshot[0]. Eg. having the current page as the root node of the tree view, with a path bar for context. Such a view brings the added benefit of searches limited to the current page and it's sub-pages without bringing up the search dialog.

[0] https://i1.wp.com/ravingroo.com/wp-content/uploads/2015/12/mac-os-x-finder-show-hidden-files.png

**Comment by introt** [comment] 2021-08-13 12:38
> Usability wise I'm undecided. Agree that at some point you'll need the
scrollbar to show content to far out to the right. However for notebooks
with limited nesting levels, the ellipsize works better.
> 
> Not sure what a good rule  would be to make the behavior OK in all cases.
Could make it optional, but that just puts the burden to the user.

The "Moodle sidebar way" is to wrap the titles to the max width of the sidebar and provide horizontal scrolling (only) if something doesn't fit. Using wrapping like this solves two problems at once:

1. A single long title doesn't make the scroll bar appear (unless unwrappable)
2. The user knows whether a title has more words after the cut-off (though it isn't immediately obvious whether there are more letters to a given wrapped word)

That leaves us with "just" one problem: what to do with deep nesting?

I propose having a minimum wrapped width per level, as pseudocoded below. This way the horizontal scroll bar only/always appears when an unwrappable string in a page name doesn't fit in the view, and the wrapping doesn't become obnoxious in the deeper levels.

```
visible_width = panel_width - (depth * indent)
wrapping_width = visible_width if visible_width > min_width else min_width
```

What should the minimum width be? `panel_width - page_count_width - n * (indent)` with `n` of 4 leaves about half of the current side panel minimum width for words before the horizontal scroll bar appears. That should be plenty for most English words and allows users using limited nesting levels and long words to choose between making the panel wider or making the scroll bar appear.

**Closed** 2021-09-14 19:25 UTC
